CastorUtils: castor::NamedBase< T > Class Template Reference
castor::NamedBase< T > Class Template Reference
Class for named elements.
Public Member Functions
NamedBase (T const &p_name)
Constructor.
NamedBase (NamedBase const &p_named)=default
Copy Constructor.
NamedBase (NamedBase &&p_named)=default
Move Constructor.
~NamedBase ()=default
Destructor.
NamedBase & operator= (NamedBase const &p_named)=default
Copy Constructor.
NamedBase & operator= (NamedBase &&p_named)=default
Move Constructor.
T const & getName () const
Retrieves the name.
void setName (T const &p_name)
sets the name
Protected Attributes
T m_name
Detailed Description
template<typename T = String>
class castor::NamedBase< T >
Class for named elements.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Remarks
The name type is a template argument so anything can be a name for this class (default is castor::String)
Constructor & Destructor Documentation
NamedBase() [1/3]
template<typename T = String> castor::NamedBase< T >::NamedBase (T const & p_name) inline explicit
Constructor.
Parameters
[in] p_name The name
References castor::NamedBase< T >::operator=(), and castor::NamedBase< T >::~NamedBase().
NamedBase() [2/3]
template<typename T = String> castor::NamedBase< T >::NamedBase (NamedBase< T > const & p_named) default
Copy Constructor.
Parameters
[in] p_named The object to copy
NamedBase() [3/3]
template<typename T = String> castor::NamedBase< T >::NamedBase (NamedBase< T > && p_named) default
Move Constructor.
Parameters
[in] p_named The object to move
~NamedBase()
template<typename T = String> castor::NamedBase< T >::~NamedBase () default
Destructor.
Referenced by castor::NamedBase< T >::NamedBase().
Member Function Documentation
getName()
template<typename T = String> T const& castor::NamedBase< T >::getName () const inline
Retrieves the name.
Returns
The name
References castor::NamedBase< T >::m_name.
operator=() [1/2]
template<typename T = String> NamedBase& castor::NamedBase< T >::operator= (NamedBase< T > const & p_named) default
Copy Constructor.
Parameters
[in] p_named The object to copy
Referenced by castor::NamedBase< T >::NamedBase().
operator=() [2/2]
template<typename T = String> NamedBase& castor::NamedBase< T >::operator= (NamedBase< T > && p_named) default
Move Constructor.
Parameters
[in] p_named The object to move
setName()
template<typename T = String> void castor::NamedBase< T >::setName (T const & p_name) inline
sets the name
Parameters
[in] p_name The name
References castor::NamedBase< T >::m_name.
Member Data Documentation
m_name
template<typename T = String> T castor::NamedBase< T >::m_name protected
Referenced by castor::NamedBase< T >::getName(), and castor::NamedBase< T >::setName().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Design/Named.hpp