CastorUtils: castor::AngleT< Type > Class Template Reference
castor::AngleT< Type > Class Template Reference
Angle helper class.
Public Member Functions
AngleT () noexcept
Default constructor.
~AngleT () noexcept
Destructor.
Type degrees () const noexcept
Conversion to degrees.
Type radians () const noexcept
Conversion to radians.
Type grads () const noexcept
Conversion to gradients.
void degrees (double p_rAngle) noexcept
sets this angle value from degrees
void radians (double p_rAngle) noexcept
sets this angle value from radians
void grads (double p_rAngle) noexcept
sets this angle value from gradients
Type cos () const
Trigonometric cosine.
Type sin () const
Trigonometric sine.
Type tan () const
Trigonometric tangent.
Type cosh () const
Hyperbolic cosine.
Type sinh () const
Hyperbolic sine.
Type tanh () const
Hyperbolic tangent.
void acos (double p_rValue)
Computes this angle's value from the given cosine value.
void asin (double p_rValue)
Computes this angle's value from the given sine value.
void atan (double p_rValue)
Computes this angle's value from the given tangent value.
AngleT< Type > & operator- () noexcept
Negation operator.
AngleT< Type > & operator+= (AngleT< Type > const &p_rhs) noexcept
addition assignment operator
AngleT< Type > & operator-= (AngleT< Type > const &p_rhs) noexcept
Substraction assignment operator.
AngleT< Type > & operator*= (AngleT< Type > const &p_rhs) noexcept
Multiplication assignment operator.
AngleT< Type > & operator/= (AngleT< Type > const &p_rhs) noexcept
Division assignment operator.
AngleT< Type > & operator*= (double p_rhs) noexcept
Multiplication assignment operator.
AngleT< Type > & operator/= (double p_rhs) noexcept
Division assignment operator.
Static Public Member Functions
template<typename T >
static AngleT< Type > fromDegrees (T p_degrees) noexcept
Named constructor, from a degrees angle.
template<typename T >
static AngleT< Type > fromRadians (T p_radians) noexcept
Named constructor, from a radians angle.
template<typename T >
static AngleT< Type > fromGrads (T p_grads) noexcept
Named constructor, from a gradients angle.
Static Public Attributes
static CU_API const Type RadianToDegree
Radian to degree conversion constant.
static CU_API const Type RadianToGrad
Radian to gradient conversion constant.
static CU_API const Type DegreeToRadian
Degree to radian conversion constant.
static CU_API const Type DegreeToGrad
Degree to gradient conversion constant.
static CU_API const Type GradToDegree
Gradient to degree conversion constant.
static CU_API const Type GradToRadian
Gradient to radian conversion constant.
static CU_API const Type Pi
Pi constant, expressed in real.
static CU_API const Type PiMult2
Pi * 2 constant.
static CU_API const Type PiDiv2
Pi / 2 constant.
Friends
template<typename T >
bool operator== (AngleT< T > const &p_lhs, AngleT< T > const &p_rhs) noexcept
template<typename T >
bool operator< (AngleT< T > const &p_lhs, AngleT< T > const &p_rhs) noexcept
template<typename T >
bool operator> (AngleT< T > const &p_lhs, AngleT< T > const &p_rhs) noexcept
Detailed Description
template<typename Type>
class castor::AngleT< Type >
Angle helper class.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Remarks
Used to manage angles without taking care of degrees or radians
Constructor & Destructor Documentation
AngleT()
template<typename Type > castor::AngleT< Type >::AngleT () inline noexcept
Default constructor.
Referenced by castor::AngleT< Type >::fromGrads().
~AngleT()
template<typename Type > castor::AngleT< Type >::~AngleT () inline noexcept
Destructor.
Referenced by castor::AngleT< Type >::fromGrads().
Member Function Documentation
acos()
template<typename Type > void castor::AngleT< Type >::acos (double p_rValue) inline
Computes this angle's value from the given cosine value.
Parameters
[in] p_rValue The cosine value
Referenced by castor::AngleT< Type >::fromGrads().
asin()
template<typename Type > void castor::AngleT< Type >::asin (double p_rValue) inline
Computes this angle's value from the given sine value.
Parameters
[in] p_rValue The sine value
Referenced by castor::AngleT< Type >::fromGrads().
atan()
template<typename Type > void castor::AngleT< Type >::atan (double p_rValue) inline
Computes this angle's value from the given tangent value.
Parameters
[in] p_rValue The tangent value
Referenced by castor::AngleT< Type >::fromGrads().
cos()
template<typename Type > Type castor::AngleT< Type >::cos () const inline
Trigonometric cosine.
Returns
Cosine of this angle
Referenced by castor::AngleT< Type >::fromGrads().
cosh()
template<typename Type > Type castor::AngleT< Type >::cosh () const inline
Hyperbolic cosine.
Returns
Hyperbolic cosine of this angle
Referenced by castor::AngleT< Type >::fromGrads().
degrees() [1/2]
template<typename Type > Type castor::AngleT< Type >::degrees () const inline noexcept
Conversion to degrees.
Returns
Angle value, in degrees
Referenced by castor::AngleT< Type >::fromGrads().
degrees() [2/2]
template<typename Type > void castor::AngleT< Type >::degrees (double p_rAngle) inline noexcept
sets this angle value from degrees
Parameters
[in] p_rAngle Angle in degrees
fromDegrees()
template<typename Type > template<typename T > static AngleT< Type > castor::AngleT< Type >::fromDegrees (T p_degrees) inline static noexcept
Named constructor, from a degrees angle.
Parameters
[in] p_degrees The angle in degrees
Returns
The built angle
References castor::AngleT< Type >::DegreeToRadian.
Referenced by operator"" _degrees().
fromGrads()
template<typename Type > template<typename T > static AngleT< Type > castor::AngleT< Type >::fromGrads (T p_grads) inline static noexcept
Named constructor, from a gradients angle.
Parameters
[in] p_grads The angle in gradients
Returns
The built angle
References castor::AngleT< Type >::acos(), castor::AngleT< Type >::AngleT(), castor::AngleT< Type >::asin(), castor::AngleT< Type >::atan(), castor::AngleT< Type >::cos(), castor::AngleT< Type >::cosh(), castor::AngleT< Type >::degrees(), castor::AngleT< Type >::grads(), castor::AngleT< Type >::GradToRadian, castor::operator!=(), castor::operator*(), castor::AngleT< Type >::operator*=(), castor::operator+(), castor::AngleT< Type >::operator+=(), castor::AngleT< Type >::operator-(), castor::AngleT< Type >::operator-=(), castor::operator/(), castor::AngleT< Type >::operator/=(), castor::AngleT< Type >::operator==, castor::AngleT< Type >::operator>, castor::operator>=(), castor::AngleT< Type >::radians(), castor::AngleT< Type >::sin(), castor::AngleT< Type >::sinh(), castor::AngleT< Type >::tan(), castor::AngleT< Type >::tanh(), and castor::AngleT< Type >::~AngleT().
fromRadians()
template<typename Type > template<typename T > static AngleT< Type > castor::AngleT< Type >::fromRadians (T p_radians) inline static noexcept
Named constructor, from a radians angle.
Parameters
[in] p_radians The angle in radians
Returns
The built angle
Referenced by operator"" _radians().
grads() [1/2]
template<typename Type > Type castor::AngleT< Type >::grads () const inline noexcept
Conversion to gradients.
Returns
Angle value, in gradients
Referenced by castor::AngleT< Type >::fromGrads().
grads() [2/2]
template<typename Type > void castor::AngleT< Type >::grads (double p_rAngle) inline noexcept
sets this angle value from gradients
Parameters
[in] p_rAngle Angle in gradients
operator*=() [1/2]
template<typename Type > AngleT< Type >& castor::AngleT< Type >::operator*= (AngleT< Type > const & p_rhs) inline noexcept
Multiplication assignment operator.
Parameters
[in] p_rhs Angle to multiply to this one
Returns
A reference to this angle
Referenced by castor::AngleT< Type >::fromGrads().
operator*=() [2/2]
template<typename Type > AngleT< Type >& castor::AngleT< Type >::operator*= (double p_rhs) inline noexcept
Multiplication assignment operator.
Parameters
[in] p_rhs Scalar to multiply to this one
Returns
A reference to this angle
operator+=()
template<typename Type > AngleT< Type >& castor::AngleT< Type >::operator+= (AngleT< Type > const & p_rhs) inline noexcept
addition assignment operator
Parameters
[in] p_rhs Angle to add to this one
Returns
A reference to this angle
Referenced by castor::AngleT< Type >::fromGrads().
operator-()
template<typename Type > AngleT< Type >& castor::AngleT< Type >::operator- () inline noexcept
Negation operator.
Returns
A reference to this angle.
Referenced by castor::AngleT< Type >::fromGrads().
operator-=()
template<typename Type > AngleT< Type >& castor::AngleT< Type >::operator-= (AngleT< Type > const & p_rhs) inline noexcept
Substraction assignment operator.
Parameters
[in] p_rhs Angle to subtract to this one
Returns
A reference to this angle
Referenced by castor::AngleT< Type >::fromGrads().
operator/=() [1/2]
template<typename Type > AngleT< Type >& castor::AngleT< Type >::operator/= (AngleT< Type > const & p_rhs) inline noexcept
Division assignment operator.
Parameters
[in] p_rhs Angle divider of this one
Returns
A reference to this angle
Referenced by castor::AngleT< Type >::fromGrads().
operator/=() [2/2]
template<typename Type > AngleT< Type >& castor::AngleT< Type >::operator/= (double p_rhs) inline noexcept
Division assignment operator.
Parameters
[in] p_rhs Scalar divider of this one
Returns
A reference to this angle
radians() [1/2]
template<typename Type > Type castor::AngleT< Type >::radians () const inline noexcept
Conversion to radians.
Returns
Angle value, in radians
Referenced by castor::AngleT< Type >::fromGrads().
radians() [2/2]
template<typename Type > void castor::AngleT< Type >::radians (double p_rAngle) inline noexcept
sets this angle value from radians
Parameters
[in] p_rAngle Angle in radians
sin()
template<typename Type > Type castor::AngleT< Type >::sin () const inline
Trigonometric sine.
Returns
sine of this angle
Referenced by castor::AngleT< Type >::fromGrads().
sinh()
template<typename Type > Type castor::AngleT< Type >::sinh () const inline
Hyperbolic sine.
Returns
Hyperbolic sine of this angle
Referenced by castor::AngleT< Type >::fromGrads().
tan()
template<typename Type > Type castor::AngleT< Type >::tan () const inline
Trigonometric tangent.
Returns
Tangent of this angle
Referenced by castor::AngleT< Type >::fromGrads().
tanh()
template<typename Type > Type castor::AngleT< Type >::tanh () const inline
Hyperbolic tangent.
Returns
Hyperbolic tangent of this angle
Referenced by castor::AngleT< Type >::fromGrads().
Friends And Related Function Documentation
operator<
template<typename Type > template<typename T > bool operator< (AngleT< T > const & p_lhs, AngleT< T > const & p_rhs) friend
operator==
template<typename Type > template<typename T > bool operator== (AngleT< T > const & p_lhs, AngleT< T > const & p_rhs) friend
Referenced by castor::AngleT< Type >::fromGrads().
operator>
template<typename Type > template<typename T > bool operator> (AngleT< T > const & p_lhs, AngleT< T > const & p_rhs) friend
Referenced by castor::AngleT< Type >::fromGrads().
Member Data Documentation
DegreeToGrad
template<typename Type > CU_API const Type castor::AngleT< Type >::DegreeToGrad static
Degree to gradient conversion constant.
DegreeToRadian
template<typename Type > CU_API const Type castor::AngleT< Type >::DegreeToRadian static
Degree to radian conversion constant.
Referenced by castor::AngleT< Type >::fromDegrees().
GradToDegree
template<typename Type > CU_API const Type castor::AngleT< Type >::GradToDegree static
Gradient to degree conversion constant.
GradToRadian
template<typename Type > CU_API const Type castor::AngleT< Type >::GradToRadian static
Gradient to radian conversion constant.
Referenced by castor::AngleT< Type >::fromGrads().
Pi
template<typename Type > CU_API const Type castor::AngleT< Type >::Pi static
Pi constant, expressed in real.
PiDiv2
template<typename Type > CU_API const Type castor::AngleT< Type >::PiDiv2 static
Pi / 2 constant.
PiMult2
template<typename Type > CU_API const Type castor::AngleT< Type >::PiMult2 static
Pi * 2 constant.
RadianToDegree
template<typename Type > CU_API const Type castor::AngleT< Type >::RadianToDegree static
Radian to degree conversion constant.
RadianToGrad
template<typename Type > CU_API const Type castor::AngleT< Type >::RadianToGrad static
Radian to gradient conversion constant.
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/CastorUtilsPrerequisites.hpp
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Math/Angle.hpp