CastorUtils: castor Namespace Reference
castor Namespace Reference
Namespaces
Debug
details
format
manip
matrix
Matrix basic operations.
PF
point
Point helper functions.
string
String functions namespace.
System
Classes
class AlignedMemoryAllocator
Memory allocator.
struct AlignedMemoryDataTyper
The aligned object pool typer.
struct AlignedMemoryDataTyper< Object, Align, MemoryDataType::eFixed >
Specialisation for MemoryDataType::eFixed.
struct AlignedMemoryDataTyper< Object, Align, MemoryDataType::eFixedGrowing >
Specialisation for MemoryDataType::eFixedGrowing.
class AlignedObjectPool
The aligned objects pool.
class AngleT
Angle helper class.
class ArrayView
Templated class that provide std::array style buffer view.
struct BaseTypeFromSize
Templated class that retrieves the integral base type from a size.
struct BaseTypeFromSize< 1u >
Templated class that retrieves the integral base type from a size.
struct BaseTypeFromSize< 2u >
Templated class that retrieves the integral base type from a size.
struct BaseTypeFromSize< 4u >
Templated class that retrieves the integral base type from a size.
struct BaseTypeFromSize< 8u >
Templated class that retrieves the integral base type from a size.
class BinaryFile
User friendly File class.
class BinaryLoader
Partial castor::Loader specialisation for binary files.
class BinaryWriter
Partial castor::Loader specialisation for binary files.
struct BlockGuard
Allows to declare a scoped variable with an action on construction
and an action on destruction.
class BlockTimer
Helper class, used to time a block's execution time.
class BlockTracker
Helper class, used to track entering and leaving a block.
class BuddyAllocatorT
Buddy allocator implementation.
struct BuddyAllocatorTraits
struct CallTraits
Struct used to select best way to put type in parameter : 'value' or 'const reference'.
class ChangeTracked
Templated class that provide std::array style buffer view.
class Collection
Element collection class.
class ColourComponent
Defines a colour PixelComponents (R, G, B or A) to be used in castor::Colour.
class ColourT
RGBA colour representation.
class Connection
Connection to a signal.
class ConsoleImpl
Console info class, platform dependent.
struct ConstPixelIterator
class ContainerBox
Box container class.
class Coords
Templated static dimensions point representation.
class CpuInformations
Retrieves the basic CPU informations.
class CubeBox
Combo box container class.
struct DummyDtor
Dummy destructor.
class DynamicLibrary
Platform independant library.
struct Error
Error text and report function.
struct Error< PoolErrorType::eCommonMemoryLeaksDetected >
Specialisation for PoolErrorType::eCommonMemoryLeaksDetected.
struct Error< PoolErrorType::eCommonNotFromRange >
Specialisation for PoolErrorType::eCommonNotFromRange.
struct Error< PoolErrorType::eCommonOutOfMemory >
Specialisation for PoolErrorType::eCommonOutOfMemory.
struct Error< PoolErrorType::eCommonPoolIsFull >
Specialisation for PoolErrorType::eCommonPoolIsFull.
struct Error< PoolErrorType::eGrowingNotFromRanges >
Specialisation for PoolErrorType::eGrowingNotFromRanges.
struct Error< PoolErrorType::eMarkedDoubleDelete >
Specialisation for PoolErrorType::eMarkedDoubleDelete.
struct Error< PoolErrorType::eMarkedLeakAddress >
Specialisation for PoolErrorType::eMarkedLeakAddress.
struct Error< PoolErrorType::eMarkedNotFromPool >
Specialisation for PoolErrorType::eMarkedNotFromPool.
struct Error< PoolErrorType::eSTLAllocatorUnique >
Specialisation for PoolErrorType::eSTLAllocatorUnique.
class Exception
More verbose exception class.
struct Fact
Factorial recursive case.
struct Fact< T, 0 >
Factorial end case.
class Factory
Factory concept implementation.
class File
User friendly File class.
class FileParser
"Brace file" parser base class
class FileParserContext
The context used into file parsing functions.
struct FileTyper
Helper structure to find File type (BinaryFile or TextFile) from FileType.
struct FileTyper< FileType::eBinary >
Helper structure to find File type (BinaryFile or TextFile) from FileType.
struct FileTyper< FileType::eText >
Helper structure to find File type (BinaryFile or TextFile) from FileType.
class FixedGrowingSizeMarkedMemoryData
Memory allocation policy. It can grow of a fixed objects count.
class FixedGrowingSizeMemoryData
Memory allocation policy. It can grow of a fixed objects count.
class FixedSizeMarkedMemoryData
Memory allocation policy.
class FixedSizeMemoryData
Memory allocation policy.
class FlagCombination
Templated class that provides implicit conversion from scoped enum to integral base type.
class Font
Font resource.
class FontCache
Font manager.
class Glyph
Font character (glyph) representation.
class GroupChangeTracked
Templated class that provide std::array style buffer view.
struct HasBaseParameterType
Structure used to tell if an ParameterType has a base parameter type.
struct HasBaseParameterType< ParameterType::eBitwiseOred32BitsCheckedText >
HasBaseParameterType specialisation for ParameterType::eBitwiseOred32BitsCheckedText.
struct HasBaseParameterType< ParameterType::eBitwiseOred64BitsCheckedText >
HasBaseParameterType specialisation for ParameterType::eBitwiseOred64BitsCheckedText.
struct HasBaseParameterType< ParameterType::eCheckedText >
HasBaseParameterType specialisation for ParameterType::eCheckedText.
struct HasBaseParameterType< ParameterType::eName >
HasBaseParameterType specialisation for ParameterType::eName.
class HdrColourComponent
Defines a HDR colour PixelComponents (R, G, B or A) to be used in castor::HdrColour.
class Image
Image resource.
class ImageCache
Image manager.
struct IsArithmeticType
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eDouble >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eFloat >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eInt16 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eInt32 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eInt64 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eInt8 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eLongDouble >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eUInt16 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eUInt32 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eUInt64 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eUInt8 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsColourFormat
Helper struct to tell if a pixel format represents a colour.
struct IsColourFormat< PixelFormat::eD16 >
struct IsColourFormat< PixelFormat::eD24 >
struct IsColourFormat< PixelFormat::eD24S8 >
struct IsColourFormat< PixelFormat::eD32 >
struct IsColourFormat< PixelFormat::eD32F >
struct IsColourFormat< PixelFormat::eD32FS8 >
struct IsColourFormat< PixelFormat::eS1 >
struct IsColourFormat< PixelFormat::eS8 >
struct IsDepthFormat
Helper struct to tell if a pixel format represents a depth pixel.
struct IsDepthFormat< PixelFormat::eD16 >
struct IsDepthFormat< PixelFormat::eD24 >
struct IsDepthFormat< PixelFormat::eD24S8 >
struct IsDepthFormat< PixelFormat::eD32 >
struct IsDepthFormat< PixelFormat::eD32F >
struct IsDepthFormat< PixelFormat::eD32FS8 >
struct IsDepthStencilFormat
Helper struct to tell if a pixel format represents a depth or stencil pixel.
struct IsDepthStencilFormat< PixelFormat::eD16 >
struct IsDepthStencilFormat< PixelFormat::eD24 >
struct IsDepthStencilFormat< PixelFormat::eD24S8 >
struct IsDepthStencilFormat< PixelFormat::eD32 >
struct IsDepthStencilFormat< PixelFormat::eD32F >
struct IsDepthStencilFormat< PixelFormat::eD32FS8 >
struct IsDepthStencilFormat< PixelFormat::eS1 >
struct IsDepthStencilFormat< PixelFormat::eS8 >
struct IsStencilFormat
Helper struct to tell if a pixel format represents a stencil pixel.
struct IsStencilFormat< PixelFormat::eD24S8 >
struct IsStencilFormat< PixelFormat::eD32FS8 >
struct IsStencilFormat< PixelFormat::eS1 >
struct IsStencilFormat< PixelFormat::eS8 >
class Line2D
2D line equation
class Line3D
3D line equation
struct Ln
Neperian Logarithm using template implementation.
class Loader
Main resource loader class.
class LoaderException
Resource loading exception.
class Logger
Log management class.
class LoggerImpl
Helper class for Logger, level dependant.
struct LogN
Neperian Logarithm recursive case.
struct LogN< 0, T >
Neperian Logarithm end case.
class Matrix
Templated column major matrix representation.
struct MatrixDataAllocator
struct MaxValue
Used to have the maximum value of two, at compile time.
struct MemoryDataNamer
The MemoryData namer.
struct MemoryDataTyper
The object pool typer.
struct MemoryDataTyper< Object, MemoryDataType::eFixed >
Specialisation for MemoryDataType::eFixed.
struct MemoryDataTyper< Object, MemoryDataType::eFixedGrowing >
Specialisation for MemoryDataType::eFixedGrowing.
struct MemoryDataTyper< Object, MemoryDataType::eFixedGrowingMarked >
Specialisation for MemoryDataType::eFixedGrowingMarked.
struct MemoryDataTyper< Object, MemoryDataType::eMarked >
Specialisation for MemoryDataType::eMarked.
struct Message
Message representation.
struct MinValue
Used to have the minimum value of two, at compile time.
struct enable_if<(A<=B) >::type >
Used to have the minimum value of two, at compile time.
struct enable_if<(B< A) >::type >
Used to have the minimum value of two, at compile time.
class NamedBase
Class for named elements.
struct NewDeletePolicy
Policy used to construct/destruct object if needed.
struct NoInit
Structure used to construct objects but without initialisation.
class NonAlignedMemoryAllocator
Memory allocator.
class NonCopyable
The non-copyable concept implementation.
class ObjectPool
The objects pool.
class OwnedBy
Class used to have an object owned by another one.
class ParserParameter
Specified parser parameter.
class ParserParameter< ParameterType::eBitwiseOred32BitsCheckedText >
ParserParameter specialisation for ePARAMETER_TYPE_BITWISE_ORED_CHECKED_TEXT.
class ParserParameter< ParameterType::eBitwiseOred64BitsCheckedText >
ParserParameter specialisation for ParameterType::eBitwiseOred64BitsCheckedText.
class ParserParameter< ParameterType::eCheckedText >
ParserParameter specialisation for ParameterType::eCheckedText.
class ParserParameter< ParameterType::eName >
ParserParameter specialisation for ParameterType::eName.
class ParserParameter< Type, typename std::enable_if< !HasBaseParameterType< Type >::value &&!IsArithmeticType< Type >::value >::type >
Specified parser parameter.
class ParserParameter< Type, typename std::enable_if< IsArithmeticType< Type >::value >::type >
Specified parser parameter.
class ParserParameterBase
Template structure holding parameter specific data.
struct ParserParameterHelper
Parser parameter helper structure.
struct ParserParameterHelper< ParameterType::eBitwiseOred32BitsCheckedText >
ParserParameterHelper specialisation for ParameterType::eBitwiseOred32BitsCheckedText.
struct ParserParameterHelper< ParameterType::eBitwiseOred64BitsCheckedText >
ParserParameterHelper specialisation for ParameterType::eBitwiseOred64BitsCheckedText.
struct ParserParameterHelper< ParameterType::eBool >
ParserParameterHelper specialisation for ParameterType::eBool.
struct ParserParameterHelper< ParameterType::eCheckedText >
ParserParameterHelper specialisation for ParameterType::eCheckedText.
struct ParserParameterHelper< ParameterType::eColour >
ParserParameterHelper specialisation for ParameterType::eColour.
struct ParserParameterHelper< ParameterType::eDouble >
ParserParameterHelper specialisation for ParameterType::eDouble.
struct ParserParameterHelper< ParameterType::eFloat >
ParserParameterHelper specialisation for ParameterType::eFloat.
struct ParserParameterHelper< ParameterType::eHdrColour >
ParserParameterHelper specialisation for ParameterType::eHdrColour.
struct ParserParameterHelper< ParameterType::eInt16 >
ParserParameterHelper specialisation for ParameterType::eInt16.
struct ParserParameterHelper< ParameterType::eInt32 >
ParserParameterHelper specialisation for ParameterType::eInt32.
struct ParserParameterHelper< ParameterType::eInt64 >
ParserParameterHelper specialisation for ParameterType::eInt64.
struct ParserParameterHelper< ParameterType::eInt8 >
ParserParameterHelper specialisation for ParameterType::eInt8.
struct ParserParameterHelper< ParameterType::eLongDouble >
ParserParameterHelper specialisation for ParameterType::eLongDouble.
struct ParserParameterHelper< ParameterType::eName >
ParserParameterHelper specialisation for ParameterType::eName.
struct ParserParameterHelper< ParameterType::ePath >
ParserParameterHelper specialisation for ParameterType::ePath.
struct ParserParameterHelper< ParameterType::ePixelFormat >
ParserParameterHelper specialisation for ParameterType::ePixelFormat.
struct ParserParameterHelper< ParameterType::ePoint2D >
ParserParameterHelper specialisation for ParameterType::ePoint2D.
struct ParserParameterHelper< ParameterType::ePoint2F >
ParserParameterHelper specialisation for ParameterType::ePoint2F.
struct ParserParameterHelper< ParameterType::ePoint2I >
ParserParameterHelper specialisation for ParameterType::ePoint2I.
struct ParserParameterHelper< ParameterType::ePoint3D >
ParserParameterHelper specialisation for ParameterType::ePoint3D.
struct ParserParameterHelper< ParameterType::ePoint3F >
ParserParameterHelper specialisation for ParameterType::ePoint3F.
struct ParserParameterHelper< ParameterType::ePoint3I >
ParserParameterHelper specialisation for ParameterType::ePoint3I.
struct ParserParameterHelper< ParameterType::ePoint4D >
ParserParameterHelper specialisation for ParameterType::ePoint4D.
struct ParserParameterHelper< ParameterType::ePoint4F >
ParserParameterHelper specialisation for ParameterType::ePoint4F.
struct ParserParameterHelper< ParameterType::ePoint4I >
ParserParameterHelper specialisation for ParameterType::ePoint4I.
struct ParserParameterHelper< ParameterType::ePosition >
ParserParameterHelper specialisation for ParameterType::ePosition.
struct ParserParameterHelper< ParameterType::eRectangle >
ParserParameterHelper specialisation for ParameterType::eRectangle.
struct ParserParameterHelper< ParameterType::eSize >
ParserParameterHelper specialisation for ParameterType::eSize.
struct ParserParameterHelper< ParameterType::eText >
ParserParameterHelper specialisation for ParameterType::eText.
struct ParserParameterHelper< ParameterType::eUInt16 >
ParserParameterHelper specialisation for ParameterType::eUInt16.
struct ParserParameterHelper< ParameterType::eUInt32 >
ParserParameterHelper specialisation for ParameterType::eUInt32.
struct ParserParameterHelper< ParameterType::eUInt64 >
ParserParameterHelper specialisation for ParameterType::eUInt64.
struct ParserParameterHelper< ParameterType::eUInt8 >
ParserParameterHelper specialisation for ParameterType::eUInt8.
class ParserParameterTypeException
Exception thrown when the user tries to retrieve a parameter of a wrong type.
class Path
Path management class.
class Pixel
Pixel definition.
struct PixelComponents
Holds colour/depth/stencil PixelComponents helper functions.
struct PixelDefinitions
Helper struct that holds pixel size, toString and converion functions.
struct PixelIterator
class PlaneEquation
Plane equation.
class Point
Templated static dimensions point representation.
class PointDataHolder
Holds the point coords, and can be specialised to customise the behaviour.
class PoolManagedObject
Pool managed object.
class PoolMemoryException
Pool exception.
class Position
Position class.
struct Power
Power recursive case.
struct Power< T, 0 >
Power end case.
struct Power< T, 1 >
Power end case.
class PreciseTimer
Millisecond precise timer representation.
class ProgramConsole
Console base class.
struct PtAssignOperators
Point assignment operators.
struct PtOperators
Point operators.
class PxBuffer
Pixel buffer class, with pixel format as a template param.
class PxBufferBase
Pixel buffer base definition.
class QuaternionT
Quaternion representation class.
class Range
A range class.
class RangedValue
A value inside a range.
class Rectangle
Rectangle class.
struct RegexFormat
Gives the regex format for given type.
struct RegexFormat< Colour >
RegexFormat specialisation for Colour.
struct RegexFormat< double >
RegexFormat specialisation for double.
struct RegexFormat< float >
RegexFormat specialisation for float.
struct RegexFormat< HdrColour >
RegexFormat specialisation for Colour.
struct RegexFormat< int16_t >
RegexFormat specialisation for int16_t.
struct RegexFormat< int32_t >
RegexFormat specialisation for int32_t.
struct RegexFormat< int64_t >
RegexFormat specialisation for int64_t.
struct RegexFormat< int8_t >
RegexFormat specialisation for int8_t.
struct RegexFormat< long double >
RegexFormat specialisation for long double.
struct RegexFormat< uint16_t >
RegexFormat specialisation for uint16_t.
struct RegexFormat< uint32_t >
RegexFormat specialisation for uint32_t.
struct RegexFormat< uint64_t >
RegexFormat specialisation for uint64_t.
struct RegexFormat< uint8_t >
RegexFormat specialisation for uint8_t.
class Resource
External resource representation.
class ScopeGuard
Class used to execute code at scope exit.
class Signal
Basic signal class.
class Size
Size class.
class SphereBox
Sphere container class.
class SphericalVertex
Vertex, expressed in rho theta and phi (Euler angles)
class SquareMatrix
Templated column major square matrix representation.
class TextFile
Text file class.
class TextLoader
Partial castor::Loader specialisation for text files.
class TextWriter
Partial castor::Writer specialisation for text files.
class ThreadPool
Thread pool implementation, using WorkerThreads.
class UnicityException
Unicity exception.
class Unique
Representation of a Unique instance class.
class UniqueAlignedObjectPool
Unique pool instance.
class UniqueObjectPool
Unique pool instance.
class UnsupportedFormatException
Unsupported format exception.
struct ValueParser
Helper structure to parse a value.
class WorkerThread
Implementation of a worker thread to place in a thread pool.
class Writer
Main resource writer class.
class ZipArchive
Zip archive class.
Typedefs
using real = float
using String = std::basic_string< xchar >
using Regex = std::basic_regex< xchar >
using RegexIterator = std::regex_iterator< String::const_iterator >
using MatchResults = std::match_results< String::const_iterator >
using StringStream = std::basic_stringstream< xchar >
using OutputStringStream = std::basic_ostringstream< xchar >
using InputStringStream = std::basic_istringstream< xchar >
using OutputStream = std::basic_ostream< xchar >
using InputStream = std::basic_istream< xchar >
using Seconds = std::chrono::seconds
using Milliseconds = std::chrono::milliseconds
using Microseconds = std::chrono::microseconds
using Nanoseconds = std::chrono::nanoseconds
using Colour = ColourT< ColourComponent >
using HdrColour = ColourT< HdrColourComponent >
using PixelBuffer = PxBuffer< PixelFormat::eA8R8G8B8 >
Typedef over a buffer of pixels in format A8R8G8B8.
template<typename T >
using Point2 = Point< T, 2 >
template<typename T >
using Point3 = Point< T, 3 >
template<typename T >
using Point4 = Point< T, 4 >
template<typename T >
using Coords2 = Coords< T, 2 >
template<typename T >
using Coords3 = Coords< T, 3 >
template<typename T >
using Coords4 = Coords< T, 4 >
using Angle = AngleT< real >
using Quaternion = QuaternionT< real >
using MessageQueue = std::deque< Message >
The message queue.
using LogCallback = std::function< void(String const &text, LogType type, bool newLine) >
Logging callback function.
typedef NamedBase< String > Named
typedef std::function< bool(castor::FileParser *p_parser, ParserParameterArray const &p_params) > ParserFunction
Parser function definition.
using ContainerBox2D = ContainerBox< 2 >
Typedef on a 2 dimensions ContainerBox.
using ContainerBox3D = ContainerBox< 3 >
Typedef on a 3 dimensions ContainerBox.
typedef Pixel< PixelFormat::eA8R8G8B8 > UbPixel
Typedef over a pixel in A8R8G8B8 format.
using BuddyAllocator = BuddyAllocatorT< BuddyAllocatorTraits >
Enumerations
enum FileType : uint8_t { FileType::eBinary, FileType::eText }
castor::Loader supported file types enumeration
enum PixelFormat : uint8_t {
PixelFormat::eL8, PixelFormat::eL16F32F, PixelFormat::eL32F, PixelFormat::eA8L8,
PixelFormat::eAL16F32F, PixelFormat::eAL32F, PixelFormat::eA1R5G5B5, PixelFormat::eA4R4G4B4,
PixelFormat::eR5G6B5, PixelFormat::eR8G8B8, PixelFormat::eB8G8R8, PixelFormat::eR8G8B8_SRGB,
PixelFormat::eB8G8R8_SRGB, PixelFormat::eA8R8G8B8, PixelFormat::eA8B8G8R8, PixelFormat::eA8R8G8B8_SRGB,
PixelFormat::eA8B8G8R8_SRGB, PixelFormat::eRGB16F, PixelFormat::eRGBA16F, PixelFormat::eRGB16F32F,
PixelFormat::eRGBA16F32F, PixelFormat::eRGB32F, PixelFormat::eRGBA32F, PixelFormat::eDXTC1,
PixelFormat::eDXTC3, PixelFormat::eDXTC5, PixelFormat::eYUY2, PixelFormat::eD16,
PixelFormat::eD24, PixelFormat::eD24S8, PixelFormat::eD32, PixelFormat::eD32F,
PixelFormat::eD32FS8, PixelFormat::eS1, PixelFormat::eS8
}
Pixel format enumeration.
enum Intersection : uint8_t { Intersection::eIn, Intersection::eOut, Intersection::eIntersect }
Intersection types.
enum MemoryDataType { MemoryDataType::eFixed, MemoryDataType::eMarked, MemoryDataType::eFixedGrowing, MemoryDataType::eFixedGrowingMarked }
Supported MemoryData types.
enum UnicityError { UnicityError::eNoInstance, UnicityError::eAnInstance }
Unicity errors enumeration.
enum ParameterType : uint8_t {
ParameterType::eText, ParameterType::eName, ParameterType::ePath, ParameterType::eCheckedText,
ParameterType::eBitwiseOred32BitsCheckedText, ParameterType::eBitwiseOred64BitsCheckedText, ParameterType::eBool, ParameterType::eInt8,
ParameterType::eInt16, ParameterType::eInt32, ParameterType::eInt64, ParameterType::eUInt8,
ParameterType::eUInt16, ParameterType::eUInt32, ParameterType::eUInt64, ParameterType::eFloat,
ParameterType::eDouble, ParameterType::eLongDouble, ParameterType::ePixelFormat, ParameterType::ePoint2I,
ParameterType::ePoint3I, ParameterType::ePoint4I, ParameterType::ePoint2F, ParameterType::ePoint3F,
ParameterType::ePoint4F, ParameterType::ePoint2D, ParameterType::ePoint3D, ParameterType::ePoint4D,
ParameterType::eSize, ParameterType::ePosition, ParameterType::eRectangle, ParameterType::eColour,
ParameterType::eHdrColour
}
Parser function parameter types enumeration.
enum PredefinedColour : uint32_t {
PredefinedColour::eTransparentBlack = 0x00000000, PredefinedColour::eLowAlphaBlack = 0x00000040, PredefinedColour::eMedAlphaBlack = 0x0000007F, PredefinedColour::eHighAlphaBlack = 0x000000BF,
PredefinedColour::eOpaqueBlack = 0x000000FF, PredefinedColour::eTransparentDarkBlue = 0x00007F00, PredefinedColour::eLowAlphaDarkBlue = 0x00007F40, PredefinedColour::eMedAlphaDarkBlue = 0x00007F7F,
PredefinedColour::eHighAlphaDarkBlue = 0x00007FBF, PredefinedColour::eOpaqueDarkBlue = 0x00007FFF, PredefinedColour::eTransparentBlue = 0x0000FF00, PredefinedColour::eLowAlphaBlue = 0x0000FF40,
PredefinedColour::eMedAlphaBlue = 0x0000FF7F, PredefinedColour::eHighAlphaBlue = 0x0000FFBF, PredefinedColour::eOpaqueBlue = 0x0000FFFF, PredefinedColour::eTransparentDarkGreen = 0x007F0000,
PredefinedColour::eLowAlphaDarkGreen = 0x007F0040, PredefinedColour::eMedAlphaDarkGreen = 0x007F007F, PredefinedColour::eHighAlphaDarkGreen = 0x007F00BF, PredefinedColour::eOpaqueDarkGreen = 0x007F00FF,
PredefinedColour::eTransparentGreen = 0x00FF0000, PredefinedColour::eLowAlphaGreen = 0x00FF0040, PredefinedColour::eMedAlphaGreen = 0x00FF007F, PredefinedColour::eHighAlphaGreen = 0x00FF00BF,
PredefinedColour::eOpaqueGreen = 0x00FF00FF, PredefinedColour::eTransparentDarkRed = 0x7F000000, PredefinedColour::eLowAlphaDarkRed = 0x7F000040, PredefinedColour::eMedAlphaDarkRed = 0x7F00007F,
PredefinedColour::eHighAlphaDarkRed = 0x7F0000BF, PredefinedColour::eOpaqueDarkRed = 0x7F0000FF, PredefinedColour::eTransparentRed = 0xFF000000, PredefinedColour::eLowAlphaRed = 0xFF000040,
PredefinedColour::eMedAlphaRed = 0xFF00007F, PredefinedColour::eHighAlphaRed = 0xFF0000BF, PredefinedColour::eOpaqueRed = 0xFF0000FF, PredefinedColour::eTransparentLightBlue = 0x7F7FFF00,
PredefinedColour::eLowAlphaLightBlue = 0x7F7FFF40, PredefinedColour::eMedAlphaLightBlue = 0x7F7FFF7F, PredefinedColour::eHighAlphaLightBlue = 0x7F7FFFBF, PredefinedColour::eOpaqueLightBlue = 0x7F7FFFFF,
PredefinedColour::eTransparentLightGreen = 0x7FFF7F00, PredefinedColour::eLowAlphaLightGreen = 0x7FFF7F40, PredefinedColour::eMedAlphaLightGreen = 0x7FFF7F7F, PredefinedColour::eHighAlphaLightGreen = 0x7FFF7FBF,
PredefinedColour::eOpaqueLightGreen = 0x7FFF7FFF, PredefinedColour::eTransparentLightRed = 0xFF7F7F00, PredefinedColour::eLowAlphaLightRed = 0xFF7F7F40, PredefinedColour::eMedAlphaLightRed = 0xFF7F7F7F,
PredefinedColour::eHighAlphaLightRed = 0xFF7F7FBF, PredefinedColour::eOpaqueLightRed = 0xFF7F7FFF, PredefinedColour::eTransparentWhite = 0xFFFFFF00, PredefinedColour::eLowAlphaWhite = 0xFFFFFF40,
PredefinedColour::eMedAlphaWhite = 0xFFFFFF7F, PredefinedColour::eHighAlphaWhite = 0xFFFFFFBF, PredefinedColour::eOpaqueWhite = 0xFFFFFFFF
}
Predefined colours enumeration.
enum Component : uint8_t { Component::eRed, Component::eGreen, Component::eBlue, Component::eAlpha }
ColourT components enumeration.
enum PixelComponent : uint8_t {
PixelComponent::eRed, PixelComponent::eGreen, PixelComponent::eBlue, PixelComponent::eAlpha,
PixelComponent::eLuminance, PixelComponent::eDepth, PixelComponent::eStencil
}
Pixel PixelComponents enumeration.
enum LogType : uint8_t {
LogType::eTrace, LogType::eDebug, LogType::eInfo, LogType::eWarning,
LogType::eError, LogType::eCount
}
Defines the various log types.
enum PoolErrorType {
PoolErrorType::eCommonOutOfMemory, PoolErrorType::eCommonPoolIsFull, PoolErrorType::eCommonMemoryLeaksDetected, PoolErrorType::eCommonNotFromRange,
PoolErrorType::eMarkedLeakAddress, PoolErrorType::eMarkedDoubleDelete, PoolErrorType::eMarkedNotFromPool, PoolErrorType::eGrowingNotFromRanges,
PoolErrorType::eSTLAllocatorUnique
}
Pool errors enumeration.
Functions
CU_API void * alignedAlloc (size_t p_alignment, size_t p_size)
Allocates aligned memory.
CU_API void alignedFree (void *p_memory)
Deallocates aligned memory.
template<int A>
class CASTOR_ALIGNED_DECL (A) Aligned
Templated class that provide alignment support.
template<typename T >
class CASTOR_ALIGNED_DECL (alignof(T)) AlignedFrom
Templated class that provide alignment support.
CU_API Point3r operator* (Matrix4x4r const &p_mtx, Point3r const &p_pt)
CU_API Point3r operator* (Point3r const &p_pt, Matrix4x4r const &p_mtx)
CU_API Point4r operator* (Matrix4x4r const &p_mtx, Point4r const &p_pt)
CU_API Point4r operator* (Point4r const &p_pt, Matrix4x4r const &p_mtx)
CU_API uint32_t getNext2Pow (uint32_t p_uiDim)
DECLARE_POINT (bool, 4, b)
DECLARE_POINT (bool, 3, b)
DECLARE_POINT (bool, 2, b)
DECLARE_POINT (int8_t, 4, c)
DECLARE_POINT (int8_t, 3, c)
DECLARE_POINT (int8_t, 2, c)
DECLARE_POINT (uint8_t, 4, ub)
DECLARE_POINT (uint8_t, 3, ub)
DECLARE_POINT (uint8_t, 2, ub)
DECLARE_POINT (int16_t, 4, s)
DECLARE_POINT (int16_t, 3, s)
DECLARE_POINT (int16_t, 2, s)
DECLARE_POINT (uint16_t, 4, us)
DECLARE_POINT (uint16_t, 3, us)
DECLARE_POINT (uint16_t, 2, us)
DECLARE_POINT (int32_t, 4, i)
DECLARE_POINT (int32_t, 3, i)
DECLARE_POINT (int32_t, 2, i)
DECLARE_POINT (uint32_t, 4, ui)
DECLARE_POINT (uint32_t, 3, ui)
DECLARE_POINT (uint32_t, 2, ui)
DECLARE_POINT (real, 4, r)
DECLARE_POINT (real, 3, r)
DECLARE_POINT (real, 2, r)
DECLARE_POINT (float, 4, f)
DECLARE_POINT (float, 3, f)
DECLARE_POINT (float, 2, f)
DECLARE_POINT (double, 4, d)
DECLARE_POINT (double, 3, d)
DECLARE_POINT (double, 2, d)
DECLARE_COORD (bool, 4, b)
DECLARE_COORD (bool, 3, b)
DECLARE_COORD (bool, 2, b)
DECLARE_COORD (int8_t, 4, c)
DECLARE_COORD (int8_t, 3, c)
DECLARE_COORD (int8_t, 2, c)
DECLARE_COORD (uint8_t, 4, ub)
DECLARE_COORD (uint8_t, 3, ub)
DECLARE_COORD (uint8_t, 2, ub)
DECLARE_COORD (int16_t, 4, s)
DECLARE_COORD (int16_t, 3, s)
DECLARE_COORD (int16_t, 2, s)
DECLARE_COORD (uint16_t, 4, us)
DECLARE_COORD (uint16_t, 3, us)
DECLARE_COORD (uint16_t, 2, us)
DECLARE_COORD (int32_t, 4, i)
DECLARE_COORD (int32_t, 3, i)
DECLARE_COORD (int32_t, 2, i)
DECLARE_COORD (uint32_t, 4, ui)
DECLARE_COORD (uint32_t, 3, ui)
DECLARE_COORD (uint32_t, 2, ui)
DECLARE_COORD (int, 4, i)
DECLARE_COORD (int, 3, i)
DECLARE_COORD (int, 2, i)
DECLARE_COORD (real, 4, r)
DECLARE_COORD (real, 3, r)
DECLARE_COORD (real, 2, r)
DECLARE_COORD (float, 4, f)
DECLARE_COORD (float, 3, f)
DECLARE_COORD (float, 2, f)
DECLARE_COORD (double, 4, d)
DECLARE_COORD (double, 3, d)
DECLARE_COORD (double, 2, d)
DECLARE_CONST_COORD (bool, 4, b)
DECLARE_CONST_COORD (bool, 3, b)
DECLARE_CONST_COORD (bool, 2, b)
DECLARE_CONST_COORD (int8_t, 4, c)
DECLARE_CONST_COORD (int8_t, 3, c)
DECLARE_CONST_COORD (int8_t, 2, c)
DECLARE_CONST_COORD (uint8_t, 4, ub)
DECLARE_CONST_COORD (uint8_t, 3, ub)
DECLARE_CONST_COORD (uint8_t, 2, ub)
DECLARE_CONST_COORD (int16_t, 4, s)
DECLARE_CONST_COORD (int16_t, 3, s)
DECLARE_CONST_COORD (int16_t, 2, s)
DECLARE_CONST_COORD (uint16_t, 4, us)
DECLARE_CONST_COORD (uint16_t, 3, us)
DECLARE_CONST_COORD (uint16_t, 2, us)
DECLARE_CONST_COORD (int32_t, 4, i)
DECLARE_CONST_COORD (int32_t, 3, i)
DECLARE_CONST_COORD (int32_t, 2, i)
DECLARE_CONST_COORD (uint32_t, 4, ui)
DECLARE_CONST_COORD (uint32_t, 3, ui)
DECLARE_CONST_COORD (uint32_t, 2, ui)
DECLARE_CONST_COORD (int, 4, i)
DECLARE_CONST_COORD (int, 3, i)
DECLARE_CONST_COORD (int, 2, i)
DECLARE_CONST_COORD (real, 4, r)
DECLARE_CONST_COORD (real, 3, r)
DECLARE_CONST_COORD (real, 2, r)
DECLARE_CONST_COORD (float, 4, f)
DECLARE_CONST_COORD (float, 3, f)
DECLARE_CONST_COORD (float, 2, f)
DECLARE_CONST_COORD (double, 4, d)
DECLARE_CONST_COORD (double, 3, d)
DECLARE_CONST_COORD (double, 2, d)
DECLARE_SQMTX (bool, 4, b)
DECLARE_SQMTX (bool, 3, b)
DECLARE_SQMTX (bool, 2, b)
DECLARE_SQMTX (int, 4, i)
DECLARE_SQMTX (int, 3, i)
DECLARE_SQMTX (int, 2, i)
DECLARE_SQMTX (uint32_t, 4, ui)
DECLARE_SQMTX (uint32_t, 3, ui)
DECLARE_SQMTX (uint32_t, 2, ui)
DECLARE_SQMTX (real, 4, r)
DECLARE_SQMTX (real, 3, r)
DECLARE_SQMTX (real, 2, r)
DECLARE_SQMTX (float, 4, f)
DECLARE_SQMTX (float, 3, f)
DECLARE_SQMTX (float, 2, f)
DECLARE_SQMTX (double, 4, d)
DECLARE_SQMTX (double, 3, d)
DECLARE_SQMTX (double, 2, d)
DECLARE_MTX (bool, 2, 3, b)
DECLARE_MTX (bool, 2, 4, b)
DECLARE_MTX (bool, 3, 2, b)
DECLARE_MTX (bool, 3, 4, b)
DECLARE_MTX (bool, 4, 2, b)
DECLARE_MTX (bool, 4, 3, b)
DECLARE_MTX (int, 2, 3, i)
DECLARE_MTX (int, 2, 4, i)
DECLARE_MTX (int, 3, 2, i)
DECLARE_MTX (int, 3, 4, i)
DECLARE_MTX (int, 4, 2, i)
DECLARE_MTX (int, 4, 3, i)
DECLARE_MTX (uint32_t, 2, 3, ui)
DECLARE_MTX (uint32_t, 2, 4, ui)
DECLARE_MTX (uint32_t, 3, 2, ui)
DECLARE_MTX (uint32_t, 3, 4, ui)
DECLARE_MTX (uint32_t, 4, 2, ui)
DECLARE_MTX (uint32_t, 4, 3, ui)
DECLARE_MTX (real, 2, 3, r)
DECLARE_MTX (real, 2, 4, r)
DECLARE_MTX (real, 3, 2, r)
DECLARE_MTX (real, 3, 4, r)
DECLARE_MTX (real, 4, 2, r)
DECLARE_MTX (real, 4, 3, r)
DECLARE_MTX (float, 2, 3, f)
DECLARE_MTX (float, 2, 4, f)
DECLARE_MTX (float, 3, 2, f)
DECLARE_MTX (float, 3, 4, f)
DECLARE_MTX (float, 4, 2, f)
DECLARE_MTX (float, 4, 3, f)
DECLARE_MTX (double, 2, 3, d)
DECLARE_MTX (double, 2, 4, d)
DECLARE_MTX (double, 3, 2, d)
DECLARE_MTX (double, 3, 4, d)
DECLARE_MTX (double, 4, 2, d)
DECLARE_MTX (double, 4, 3, d)
DECLARE_SMART_PTR (Quaternion)
DECLARE_SMART_PTR (SphericalVertex)
DECLARE_SMART_PTR (CubeBox)
DECLARE_SMART_PTR (SphereBox)
DECLARE_SMART_PTR (Image)
DECLARE_SMART_PTR (Font)
DECLARE_SMART_PTR (PxBufferBase)
DECLARE_SMART_PTR (FileParserContext)
DECLARE_SMART_PTR (ParserParameterBase)
DECLARE_SMART_PTR (DynamicLibrary)
Typedef on a pointer to a DynamicLibrary.
DECLARE_VECTOR (uint8_t, Byte)
DECLARE_VECTOR (SphericalVertexSPtr, SphericalVertexPtr)
DECLARE_VECTOR (int, Int)
DECLARE_VECTOR (String, String)
DECLARE_VECTOR (Path, Path)
DECLARE_VECTOR (ParserParameterBaseSPtr, ParserParameter)
DECLARE_MAP (String, uint32_t, UIntStr)
DECLARE_MAP (String, uint64_t, UInt64Str)
DECLARE_MAP (String, bool, BoolStr)
DECLARE_MAP (String, String, StrStr)
DECLARE_SET (String, Str)
DECLARE_MAP (uint32_t, String, StrUInt)
template<typename Lockable >
std::unique_lock< Lockable > makeUniqueLock (Lockable &p_lockable)
template<typename T >
BinaryFile & operator<< (BinaryFile &p_file, T const &p_toWrite)
open mode dependant write function
template<typename T >
BinaryFile & operator>> (BinaryFile &p_file, T &p_toRead)
open mode dependant read function
bool isBigEndian () noexcept
Detects if the current system is big endian.
template<typename T >
T & switchEndianness (T &value) noexcept
Convert from little or big endian to the other.
template<typename T >
T switchEndianness (T const &value)
Convert from little or big endian to the other.
template<typename T >
T & systemEndianToBigEndian (T &value) noexcept
Convert the given value to big endian if needed.
template<typename T >
T systemEndianToBigEndian (T const &value)
Convert the given value to big endian if needed.
template<typename T , size_t N>
std::array< T, N > & systemEndianToBigEndian (std::array< T, N > &value) noexcept
Convert the given value to big endian if needed.
template<typename T , size_t N>
std::array< T, N > systemEndianToBigEndian (std::array< T, N > const &value)
Convert the given value to big endian if needed.
template<typename T >
std::vector< T > & systemEndianToBigEndian (std::vector< T > &value) noexcept
Convert the given value to big endian if needed.
template<typename T >
std::vector< T > systemEndianToBigEndian (std::vector< T > const &value)
Convert the given value to big endian if needed.
template<typename T >
T & bigEndianToSystemEndian (T &value) noexcept
Convert the given big endian value to system endian if needed.
template<typename T >
T bigEndianToSystemEndian (T const &value)
Convert the given big endian value to system endian if needed.
template<typename T , size_t N>
std::array< T, N > & bigEndianToSystemEndian (std::array< T, N > &value) noexcept
Convert the given value to big endian if needed.
template<typename T , size_t N>
std::array< T, N > bigEndianToSystemEndian (std::array< T, N > const &value)
Convert the given value to big endian if needed.
template<typename T >
std::vector< T > & bigEndianToSystemEndian (std::vector< T > &value) noexcept
Convert the given value to big endian if needed.
template<typename T >
std::vector< T > bigEndianToSystemEndian (std::vector< T > const &value)
Convert the given value to big endian if needed.
CU_API bool fileOpen (FILE *&p_pFile, char const *p_pszPath, char const *p_pszMode)
Opens a file.
CU_API bool fileOpen64 (FILE *&p_pFile, char const *p_pszPath, char const *p_pszMode)
Opens a file.
CU_API bool fileSeek (FILE *p_pFile, int64_t p_offset, int p_iOrigin)
Seeks into a file.
CU_API int64_t fileTell (FILE *p_pFile)
Retrieves the file cursor position.
CU_API Path operator/ (Path const &p_lhs, Path const &p_rhs)
Appends 2 paths. adds the separator if needed.
CU_API Path operator/ (Path const &p_lhs, String const &p_rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (Path const &p_lhs, char const *p_rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (Path const &p_lhs, wchar_t const *p_rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (String const &p_lhs, Path const &p_rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (char const *p_lhs, Path const &p_rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (wchar_t const *p_lhs, Path const &p_rhs)
adds a string to a path. Adds the separator if needed
template<typename T >
TextFile & operator<< (TextFile &p_file, T const &p_toWrite)
open mode dependant write function
template<typename T >
TextFile & operator>> (TextFile &p_file, T &p_toRead)
open mode dependant read function
template<typename T >
ArrayView< T > makeArrayView (T *p_begin, size_t p_size)
template<typename T >
ArrayView< T > makeArrayView (T *p_begin, T *p_end)
template<typename T , size_t N>
ArrayView< T > makeArrayView (T(&p_buffer)[N])
template<typename InitFunc , typename CleanFunc >
BlockGuard< CleanFunc > makeBlockGuard (InitFunc p_init, CleanFunc p_clean)
Helper function to declare a BlockGuard.
template<typename T >
bool operator== (ChangeTracked< T > const &lhs, T const &rhs)
template<typename T >
bool operator== (T const &lhs, ChangeTracked< T > const &rhs)
template<typename T >
bool operator== (ChangeTracked< T > const &lhs, ChangeTracked< T > const &rhs)
template<typename T >
bool operator!= (ChangeTracked< T > const &lhs, T const &rhs)
template<typename T >
bool operator!= (T const &lhs, ChangeTracked< T > const &rhs)
template<typename T >
bool operator!= (ChangeTracked< T > const &lhs, ChangeTracked< T > const &rhs)
template<typename T >
ChangeTracked< T > makeChangeTracked (T const &value)
template<typename FlagType , typename Type >
bool operator== (FlagCombination< FlagType, Type > const &p_lhs, FlagCombination< FlagType, Type > const &p_rhs) noexcept
Equality operator.
template<typename FlagType , typename Type >
bool operator== (FlagCombination< FlagType, Type > const &p_lhs, FlagType const &p_rhs) noexcept
Equality operator.
template<typename FlagType , typename Type >
bool operator!= (FlagCombination< FlagType, Type > const &p_lhs, FlagCombination< FlagType, Type > const &p_rhs) noexcept
Difference operator.
template<typename FlagType , typename Type >
bool operator!= (FlagCombination< FlagType, Type > const &p_lhs, FlagType const &p_rhs) noexcept
Difference operator.
template<typename FlagType , typename Type >
FlagCombination< FlagType, Type > operator & (FlagCombination< FlagType, Type > const &p_lhs, FlagType const &p_rhs) noexcept
Binary AND operator.
template<typename FlagType , typename Type >
FlagCombination< FlagType, Type > operator| (FlagCombination< FlagType, Type > const &p_lhs, FlagType const &p_rhs) noexcept
Binary OR operator.
template<typename T , typename U >
bool checkFlag (T const &p_value, U const &p_flag) noexcept
template<typename FlagType , typename Type >
bool checkFlag (FlagCombination< FlagType, Type > const &p_value, FlagType const &p_flag) noexcept
template<typename FlagType , typename Type >
bool checkFlag (FlagCombination< FlagType, Type > const &p_value, Type const &p_flag) noexcept
template<typename FlagType , typename Type >
FlagCombination< FlagType, Type > & addFlag (FlagCombination< FlagType, Type > &p_value, FlagType const &p_flag) noexcept
adds a flag to the given value.
template<typename FlagType , typename Type >
FlagCombination< FlagType, Type > & addFlags (FlagCombination< FlagType, Type > &p_value, FlagCombination< FlagType, Type > const &p_flags) noexcept
adds a flag combination to the given value.
template<typename FlagType , typename Type >
FlagCombination< FlagType, Type > & remFlag (FlagCombination< FlagType, Type > &p_value, FlagType const &p_flag) noexcept
Removes a flag from the given value.
template<typename FlagType , typename Type >
FlagCombination< FlagType, Type > addFlag (FlagCombination< FlagType, Type > const &p_value, FlagType const &p_flag) noexcept
adds a flag to the given value.
template<typename FlagType , typename Type >
FlagCombination< FlagType, Type > remFlag (FlagCombination< FlagType, Type > const &p_value, FlagType const &p_flag) noexcept
Removes a flag from the given value.
template<typename T >
bool operator== (GroupChangeTracked< T > const &lhs, T const &rhs)
template<typename T >
bool operator== (T const &lhs, GroupChangeTracked< T > const &rhs)
template<typename T >
bool operator== (GroupChangeTracked< T > const &lhs, GroupChangeTracked< T > const &rhs)
template<typename T >
bool operator!= (GroupChangeTracked< T > const &lhs, T const &rhs)
template<typename T >
bool operator!= (T const &lhs, GroupChangeTracked< T > const &rhs)
template<typename T >
bool operator!= (GroupChangeTracked< T > const &lhs, GroupChangeTracked< T > const &rhs)
template<typename ScopeExitFuncType >
ScopeGuard< ScopeExitFuncType > makeScopeGuard (ScopeExitFuncType const &p_function)
Helper function to create a ScopeGuard.
template<typename Expr >
void cuAssert (Expr const &p_expr, char const *const p_description)
Checks an assertion.
template<ParameterType Type>
ParserParameterBaseSPtr makeParameter ()
Creates a parameter of given type.
template<ParameterType Type, typename T >
ParserParameterBaseSPtr makeParameter (Range< T > const &range)
Creates a parameter of given type.
template<ParameterType Type>
ParserParameterBaseSPtr makeParameter (UIntStrMap const &p_values)
Creates a parameter of given type.
template<ParameterType Type>
ParserParameterBaseSPtr makeParameter (UInt64StrMap const &p_values)
Creates a parameter of given type.
CU_API String const & getTypeName (ParameterType p_type)
Retrieves the given parameter type's name.
static String getPredefinedName (PredefinedColour p_predefined)
Retrieves predefined colour name.
static PredefinedColour getPredefined (String const &p_name)
Retrieves predefined colour from a name.
template<typename ComponentType >
bool operator== (ColourT< ComponentType > const &p_lhs, ColourT< ComponentType > const &p_rhs)
Equality operator.
template<typename ComponentType >
bool operator!= (ColourT< ComponentType > const &p_lhs, ColourT< ComponentType > const &p_rhs)
Inequality operator.
template<typename ComponentType >
ColourT< ComponentType > operator+ (ColourT< ComponentType > const &p_lhs, ColourT< ComponentType > const &p_rhs)
addition operator
template<typename ComponentType >
ColourT< ComponentType > operator- (ColourT< ComponentType > const &p_lhs, ColourT< ComponentType > const &p_rhs)
Substraction operator.
template<typename ComponentType , typename T >
ColourT< ComponentType > operator+ (ColourT< ComponentType > const &p_lhs, T p_rhs)
addition operator
template<typename ComponentType , typename T >
ColourT< ComponentType > operator- (ColourT< ComponentType > const &p_lhs, T p_rhs)
Subtraction operator.
template<typename ComponentType , typename T >
ColourT< ComponentType > operator* (ColourT< ComponentType > const &p_lhs, T p_rhs)
Multiplication operator.
template<typename ComponentType , typename T >
ColourT< ComponentType > operator/ (ColourT< ComponentType > const &p_lhs, T p_rhs)
Division operator.
Point3ub toRGBByte (ColourT< ColourComponent > const &p_colour)
Stores a colour's components into a point in RGB format.
Point3ub toBGRByte (ColourT< ColourComponent > const &p_colour)
Stores a colour's components into a point in BGR format.
Point4ub toRGBAByte (ColourT< ColourComponent > const &p_colour)
Stores a colour's components into a point in RGBA format.
Point4ub toBGRAByte (ColourT< ColourComponent > const &p_colour)
Stores a colour's components into a point in BGRA format.
Point4ub toARGBByte (ColourT< ColourComponent > const &p_colour)
Stores a colour's components into a point in ARGB format.
Point4ub toABGRByte (ColourT< ColourComponent > const &p_colour)
Stores a colour's components into a point in ABGR format.
template<typename ComponentType >
Point3f toRGBFloat (ColourT< ComponentType > const &p_colour)
Stores a colour's components into a point in RGB format.
template<typename ComponentType >
Point3f toBGRFloat (ColourT< ComponentType > const &p_colour)
Stores a colour's components into a point in BGR format.
template<typename ComponentType >
Point4f toRGBAFloat (ColourT< ComponentType > const &p_colour)
Stores a colour's components into a point in RGBA format.
template<typename ComponentType >
Point4f toARGBFloat (ColourT< ComponentType > const &p_colour)
Stores a colour's components into a point in ARGB format.
template<typename ComponentType >
Point4f toABGRFloat (ColourT< ComponentType > const &p_colour)
Stores a colour's components into a point in ABGR format.
template<typename ComponentType >
Point4f toBGRAFloat (ColourT< ComponentType > const &p_colour)
Stores a colour's components into a point in BGRA format.
uint32_t toRGBPacked (ColourT< ColourComponent > const &p_colour)
Packs a colour's components into an uint32_t in the RGB format (0x00RRGGBB).
uint32_t toBGRPacked (ColourT< ColourComponent > const &p_colour)
Packs a colour's components into an uint32_t in the BGR format (0x00BBGGRR).
uint32_t toARGBPacked (ColourT< ColourComponent > const &p_colour)
Packs a colour's components into an uint32_t in the ARGB format (0xAARRGGBB).
uint32_t toRGBAPacked (ColourT< ColourComponent > const &p_colour)
Packs a colour's components into an uint32_t in the RGBA format (0xRRGGBBAA).
uint32_t toABGRPacked (ColourT< ColourComponent > const &p_colour)
Packs a colour's components into an uint32_t in the ABGR format (0xAABBGGRR).
uint32_t toBGRAPacked (ColourT< ColourComponent > const &p_colour)
Packs a colour's components into an uint32_t in the BGRA format (0xBBGGRRAA).
CU_API bool operator== (ColourComponent const &p_lhs, ColourComponent const &p_rhs)
Equality operator.
CU_API bool operator!= (ColourComponent const &p_lhs, ColourComponent const &p_rhs)
Inequality operator.
template<typename T >
float operator+ (ColourComponent const &p_lhs, T &&p_rhs)
addition assignment operator
template<typename T >
float operator- (ColourComponent const &p_lhs, T &&p_rhs)
Substraction assignment operator.
template<typename T >
float operator/ (ColourComponent const &p_lhs, T &&p_rhs)
Division assignment operator.
template<typename T >
float operator* (ColourComponent const &p_lhs, T &&p_rhs)
Multiplication assignment operator.
CU_API float operator+ (ColourComponent const &p_lhs, ColourComponent const &p_rhs)
addition operator
CU_API float operator- (ColourComponent const &p_lhs, ColourComponent const &p_rhs)
Subtraction operator.
CU_API float operator* (ColourComponent const &p_lhs, ColourComponent const &p_rhs)
Multiplication operator.
CU_API float operator/ (ColourComponent const &p_lhs, ColourComponent const &p_rhs)
Division operator.
bool operator== (Glyph const &p_lhs, Glyph const &p_rhs)
Equality comparison operator.
bool operator!= (Glyph const &p_lhs, Glyph const &p_rhs)
Difference comparison operator.
bool operator< (Glyph const &p_lhs, Glyph const &p_rhs)
Less than comparison operator.
bool operator> (Glyph const &p_lhs, Glyph const &p_rhs)
Greater than comparison operator.
bool operator<= (Glyph const &p_lhs, Glyph const &p_rhs)
Less than or equal to comparison operator.
bool operator>= (Glyph const &p_lhs, Glyph const &p_rhs)
Greater than or equal to comparison operator.
CU_API bool operator== (HdrColourComponent const &p_lhs, HdrColourComponent const &p_rhs)
Equality operator.
CU_API bool operator!= (HdrColourComponent const &p_lhs, HdrColourComponent const &p_rhs)
Inequality operator.
template<typename T >
float operator+ (HdrColourComponent const &p_lhs, T const &p_rhs)
addition assignment operator
template<typename T >
float operator- (HdrColourComponent const &p_lhs, T const &p_rhs)
Substraction assignment operator.
template<typename T >
float operator/ (HdrColourComponent const &p_lhs, T const &p_rhs)
Division assignment operator.
template<typename T >
float operator* (HdrColourComponent const &p_lhs, T const &p_rhs)
Multiplication assignment operator.
CU_API float operator+ (HdrColourComponent const &p_lhs, HdrColourComponent const &p_rhs)
addition operator
CU_API float operator- (HdrColourComponent const &p_lhs, HdrColourComponent const &p_rhs)
Subtraction operator.
CU_API float operator* (HdrColourComponent const &p_lhs, HdrColourComponent const &p_rhs)
Multiplication operator.
CU_API float operator/ (HdrColourComponent const &p_lhs, HdrColourComponent const &p_rhs)
Division operator.
template<PixelFormat FT, PixelFormat FU>
bool operator== (Pixel< FT > const &p_lhs, Pixel< FU > const &p_rhs)
Equality operator.
template<PixelFormat PF>
PixelIterator< PF > operator+ (PixelIterator< PF > p_it, size_t p_offset)
template<PixelFormat PF>
PixelIterator< PF > operator- (PixelIterator< PF > p_it, size_t p_offset)
template<PixelFormat PF>
ConstPixelIterator< PF > operator+ (ConstPixelIterator< PF > p_it, size_t p_offset)
template<PixelFormat PF>
ConstPixelIterator< PF > operator- (ConstPixelIterator< PF > p_it, size_t p_offset)
CU_API bool operator== (Position const &p_a, Position const &p_b)
Equality operator.
CU_API bool operator!= (Position const &p_a, Position const &p_b)
Difference operator.
CU_API bool operator== (Size const &p_a, Size const &p_b)
Equality operator.
CU_API bool operator!= (Size const &p_a, Size const &p_b)
Difference operator.
template<typename Type >
bool operator== (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
Equality operator.
template<typename Type >
bool operator!= (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
Difference operator.
template<typename Type >
bool operator< (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
"Less than" operator
template<typename Type >
bool operator>= (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
"Greater than or equal to" operator
template<typename Type >
bool operator> (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
"Greater than" operator
template<typename Type >
bool operator<= (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
"Less than or equal to" operator
template<typename Type >
AngleT< Type > operator+ (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
addition operator
template<typename Type >
AngleT< Type > operator- (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
Substraction operator.
template<typename Type >
AngleT< Type > operator* (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
Multiplication operator.
template<typename Type >
AngleT< Type > operator/ (AngleT< Type > const &p_lhs, AngleT< Type > const &p_rhs) noexcept
Division operator.
template<typename Type >
AngleT< Type > operator* (AngleT< Type > const &p_lhs, double p_rhs) noexcept
Multiplication operator.
template<typename Type >
AngleT< Type > operator/ (AngleT< Type > const &p_lhs, double p_rhs) noexcept
Division operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
bool operator== (Coords< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Equality operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
bool operator!= (Coords< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Difference operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator+ (Coords< T, Count > const &lhs, Coords< U, _Count > const &rhs)
addition operator
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator- (Coords< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Substraction operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator* (Coords< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Multiplication operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator/ (Coords< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Division operator.
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator+ (Coords< T, Count > const &p_pt, U const *p_coords)
addition operator
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator- (Coords< T, Count > const &p_pt, U const *p_coords)
Substraction operator.
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator* (Coords< T, Count > const &p_pt, U const *p_coords)
Multiplication operator.
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator/ (Coords< T, Count > const &p_pt, U const *p_coords)
Division operator.
template<typename T , uint32_t Count>
Point< T, Count > operator* (Coords< T, Count > const &p_pt, T const &p_coord)
Multiplication operator.
template<typename T , uint32_t Count>
Point< T, Count > operator/ (Coords< T, Count > const &p_pt, T const &p_coord)
Division operator.
bool isNan (double x)
Tests if a double is a number.
int isInf (double x)
Tests if a double is infinite.
template<typename T , uint32_t Columns, uint32_t Rows>
bool operator== (Matrix< T, Columns, Rows > const &p_mtxA, Matrix< T, Columns, Rows > const &p_mtxB)
Equality operator.
template<typename T , uint32_t Columns, uint32_t Rows>
bool operator!= (Matrix< T, Columns, Rows > const &p_mtxA, Matrix< T, Columns, Rows > const &p_mtxB)
Difference operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator+ (Matrix< T, Columns, Rows > const &p_mtxA, Matrix< U, Columns, Rows > const &p_mtxB)
addition operator
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator- (Matrix< T, Columns, Rows > const &p_mtxA, Matrix< U, Columns, Rows > const &p_mtxB)
Substraction operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U , uint32_t _Columns>
Matrix< T, _Columns, Rows > operator* (Matrix< T, Columns, Rows > const &p_mtxA, Matrix< U, _Columns, Columns > const &p_mtxB)
Multiplication operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Point< T, Rows > operator* (Matrix< T, Columns, Rows > const &p_mtxA, Point< U, Columns > const &p_vector)
Multiplication operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Point< T, Columns > operator* (Point< T, Rows > const &p_vector, Matrix< U, Columns, Rows > const &p_mtxA)
Multiplication operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator+ (Matrix< T, Columns, Rows > const &p_mtxA, U const *p_mtxB)
addition operator
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator- (Matrix< T, Columns, Rows > const &p_mtxA, U const *p_mtxB)
Substraction operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator+ (Matrix< T, Columns, Rows > const &p_mtxA, T const &p_value)
addition operator
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator- (Matrix< T, Columns, Rows > const &p_mtxA, T const &p_value)
Substraction operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator* (Matrix< T, Columns, Rows > const &p_mtxA, T const &p_value)
Multiplication operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator/ (Matrix< T, Columns, Rows > const &p_mtxA, T const &p_value)
Division operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator+ (T const &p_value, Matrix< U, Columns, Rows > const &p_matrix)
addition operator
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator- (T const &p_value, Matrix< U, Columns, Rows > const &p_matrix)
Substraction operator.
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator* (T const &p_value, Matrix< U, Columns, Rows > const &p_matrix)
Multiplication operator.
template<typename T , uint32_t Columns, uint32_t Rows>
Matrix< T, Columns, Rows > operator- (Matrix< T, Columns, Rows > const &p_matrix)
template<typename T , uint32_t Columns, uint32_t Rows>
castor::String & operator<< (castor::String &p_streamOut, castor::Matrix< T, Columns, Rows > const &p_matrix)
Stream operator.
template<typename T , uint32_t Columns, uint32_t Rows>
castor::String & operator>> (castor::String &p_streamIn, castor::Matrix< T, Columns, Rows > &p_matrix)
Stream operator.
template<typename CharT , typename T , uint32_t Columns, uint32_t Rows>
std::basic_ostream< CharT > & operator<< (std::basic_ostream< CharT > &p_streamOut, castor::Matrix< T, Columns, Rows > const &p_matrix)
Stream operator.
template<typename CharT , typename T , uint32_t Columns, uint32_t Rows>
std::basic_istream< CharT > & operator>> (std::basic_istream< CharT > &p_streamIn, castor::Matrix< T, Columns, Rows > &p_matrix)
Stream operator.
CU_API bool operator== (PlaneEquation const &lhs, PlaneEquation const &rhs)
Checks if this plane is equal to another one.
CU_API bool operator!= (PlaneEquation const &lhs, PlaneEquation const &rhs)
Checks if this plane is different from another one.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
bool operator== (Point< T, Count > const &lhs, Point< U, _Count > const &rhs)
Equality operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
bool operator!= (Point< T, Count > const &lhs, Point< U, _Count > const &rhs)
Difference operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator+ (Point< T, Count > const &lhs, Point< U, _Count > const &rhs)
addition operator
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator- (Point< T, Count > const &lhs, Point< U, _Count > const &rhs)
Substraction operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator* (Point< T, Count > const &lhs, Point< U, _Count > const &rhs)
Multiplication operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator/ (Point< T, Count > const &lhs, Point< U, _Count > const &rhs)
Division operator.
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator+ (Point< T, Count > const &p_pt, U const *p_coords)
addition operator
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator- (Point< T, Count > const &p_pt, U const *p_coords)
Substraction operator.
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator* (Point< T, Count > const &p_pt, U const *p_coords)
Multiplication operator.
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator/ (Point< T, Count > const &p_pt, U const *p_coords)
Division operator.
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator* (Point< T, Count > const &p_pt, U const &p_coord)
Multiplication operator.
template<typename T , uint32_t Count, typename U >
Point< T, Count > operator/ (Point< T, Count > const &p_pt, U const &p_coord)
Division operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
bool operator== (Point< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Equality operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
bool operator!= (Point< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Difference operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator+ (Point< T, Count > const &lhs, Coords< U, _Count > const &rhs)
addition operator
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator- (Point< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Substraction operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator* (Point< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Multiplication operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator/ (Point< T, Count > const &lhs, Coords< U, _Count > const &rhs)
Division operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
bool operator== (Coords< T, Count > const &lhs, Point< U, _Count > const &rhs)
Equality operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
bool operator!= (Coords< T, Count > const &lhs, Point< U, _Count > const &rhs)
Difference operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator+ (Coords< T, Count > const &lhs, Point< U, _Count > const &rhs)
addition operator
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator- (Coords< T, Count > const &lhs, Point< U, _Count > const &rhs)
Substraction operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator* (Coords< T, Count > const &lhs, Point< U, _Count > const &rhs)
Multiplication operator.
template<typename T , uint32_t Count, typename U , uint32_t _Count>
Point< T, Count > operator/ (Coords< T, Count > const &lhs, Point< U, _Count > const &rhs)
Division operator.
template<typename T , uint32_t Count>
Point< T, Count > operator- (Point< T, Count > const &p_pt)
Negation operator.
template<typename T >
QuaternionT< T > operator+ (QuaternionT< T > const &p_lhs, QuaternionT< T > const &p_rhs)
addition operator
template<typename T >
QuaternionT< T > operator- (QuaternionT< T > const &p_lhs, QuaternionT< T > const &p_rhs)
Substraction operator.
template<typename T >
QuaternionT< T > operator* (QuaternionT< T > const &p_lhs, QuaternionT< T > const &p_rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator* (QuaternionT< T > const &p_lhs, double p_rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator* (QuaternionT< T > const &p_lhs, float p_rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator* (double p_lhs, QuaternionT< T > const &p_rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator* (float p_lhs, QuaternionT< T > const &p_rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator- (QuaternionT< T > const &p_quat)
Negation operator.
template<typename CharT , typename T >
std::basic_ostream< CharT > & operator<< (std::basic_ostream< CharT > &p_stream, QuaternionT< T > const &p_quat)
Stream operator.
template<typename T >
Range< T > makeRange (T const &p_min, T const &p_max) noexcept
Helper function to create a range.
template<typename T >
RangedValue< T > makeRangedValue (T const &p_value, T const &p_min, T const &p_max) noexcept
Helper function to create a ranged value.
template<typename T , uint32_t Count>
bool operator== (SquareMatrix< T, Count > const &p_mtxA, SquareMatrix< T, Count > const &p_mtxB)
Equality operator.
template<typename T , uint32_t Count>
bool operator!= (SquareMatrix< T, Count > const &p_mtxA, SquareMatrix< T, Count > const &p_mtxB)
Difference operator.
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator+ (SquareMatrix< T, Count > const &p_mtxA, SquareMatrix< U, Count > const &p_mtxB)
addition operator
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator- (SquareMatrix< T, Count > const &p_mtxA, SquareMatrix< U, Count > const &p_mtxB)
Substraction operator.
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator* (SquareMatrix< T, Count > const &p_mtxA, SquareMatrix< U, Count > const &p_mtxB)
Multiplication operator.
template<typename T , uint32_t Count, typename U , size_t Columns>
SquareMatrix< T, Count > operator* (SquareMatrix< T, Count > const &p_mtxA, Matrix< U, Columns, Count > const &p_mtxB)
Multiplication operator.
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator+ (SquareMatrix< T, Count > const &p_mtxA, U const *p_mtxB)
addition operator
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator- (SquareMatrix< T, Count > const &p_mtxA, U const *p_mtxB)
Substraction operator.
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator* (SquareMatrix< T, Count > const &p_mtxA, U const *p_mtxB)
Multiplication operator.
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator+ (SquareMatrix< T, Count > const &p_mtxA, T const &p_value)
addition operator
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator- (SquareMatrix< T, Count > const &p_mtxA, T const &p_value)
Substraction operator.
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator* (SquareMatrix< T, Count > const &p_mtxA, T const &p_value)
Multiplication operator.
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator/ (SquareMatrix< T, Count > const &p_mtxA, T const &p_value)
Division operator.
template<typename T , uint32_t Count, typename U , size_t Rows>
Matrix< T, Count, Rows > operator* (Matrix< U, Count, Rows > const &p_mtxA, SquareMatrix< T, Count > const &p_mtxB)
Multiplication operator.
template<typename T , uint32_t Count>
SquareMatrix< T, Count > operator+ (T const &p_value, SquareMatrix< T, Count > const &p_matrix)
addition operator
template<typename T , uint32_t Count>
SquareMatrix< T, Count > operator- (T const &p_value, SquareMatrix< T, Count > const &p_matrix)
Substraction operator.
template<typename T , uint32_t Count>
SquareMatrix< T, Count > operator* (T const &p_value, SquareMatrix< T, Count > const &p_matrix)
Multiplication operator.
template<typename T , uint32_t Count>
SquareMatrix< T, Count > operator- (SquareMatrix< T, Count > const &p_matrix)
Negation operator.
template<typename CharT , typename T , uint32_t Count>
std::basic_ostream< CharT > & operator<< (std::basic_ostream< CharT > &p_streamOut, castor::SquareMatrix< T, Count > const &p_matrix)
Stream operator.
template<typename CharT , typename T , uint32_t Count>
std::basic_istream< CharT > & operator>> (std::basic_istream< CharT > &p_streamIn, castor::SquareMatrix< T, Count > &p_matrix)
Stream operator.
CU_API std::ostream & operator<< (std::ostream &p_stream, CpuInformations const &p_object)
Output stream operator.
void getLocaltime (std::tm *p_tm, time_t const *p_pTime)
template<PoolErrorType ErrorType, typename ... Params>
static void reportError (char const *const p_name, Params ... p_params)
Reports a pool error.
template<typename CharType >
std::basic_ostream< CharType > & operator<< (std::basic_ostream< CharType > &stream, format::Indent const &ind)
Stream operator.
template<typename CharType , typename PrefixType >
std::basic_ostream< CharType > & operator<< (std::basic_ostream< CharType > &stream, format::BasePrefixer< CharType, PrefixType > const &Prefix)
Stream operator.
Arithmetic operators.
template<PixelFormat FT, PixelFormat FU>
Pixel< FT > operator+ (Pixel< FT > const &p_lhs, Pixel< FU > const &p_rhs)
template<PixelFormat FT, PixelFormat FU>
Pixel< FT > operator- (Pixel< FT > const &p_lhs, Pixel< FU > const &p_rhs)
template<PixelFormat FT, PixelFormat FU>
Pixel< FT > operator/ (Pixel< FT > const &p_lhs, Pixel< FU > const &p_rhs)
template<PixelFormat FT, PixelFormat FU>
Pixel< FT > operator* (Pixel< FT > const &p_lhs, Pixel< FU > const &p_rhs)
template<PixelFormat FT, typename U >
Pixel< FT > operator+ (Pixel< FT > const &p_lhs, U const &p_rhs)
template<PixelFormat FT, typename U >
Pixel< FT > operator- (Pixel< FT > const &p_lhs, U const &p_rhs)
template<PixelFormat FT, typename U >
Pixel< FT > operator/ (Pixel< FT > const &p_lhs, U const &p_rhs)
template<PixelFormat FT, typename U >
Pixel< FT > operator* (Pixel< FT > const &p_lhs, U const &p_rhs)
template<typename T >
T operator+ (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
T operator- (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
T operator* (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
T operator/ (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
T operator+ (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
T operator- (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
T operator* (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
T operator/ (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
T operator+ (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
T operator- (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
T operator* (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
T operator/ (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
Logic operators.
template<typename T >
bool operator== (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
bool operator!= (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
bool operator> (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
bool operator< (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
bool operator>= (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
bool operator<= (RangedValue< T > const &p_lhs, T const &p_rhs) noexcept
template<typename T >
bool operator== (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator!= (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator> (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator< (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator>= (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator<= (T const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator== (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator!= (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator> (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator< (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator>= (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
template<typename T >
bool operator<= (RangedValue< T > const &p_lhs, RangedValue< T > const &p_rhs) noexcept
Variables
CU_API DummyDtor g_dummyDtor
static const std::string ERROR_UNKNOWN_OBJECT = "Unknown object type"
static char const *const STR_UNICITY_ERROR []
Unicity error texts.
static const String cuEmptyString
An empty String.
Typedef Documentation
Angle
typedef AngleT< float > castor::Angle
BuddyAllocator
using castor::BuddyAllocator = typedef BuddyAllocatorT< BuddyAllocatorTraits >
Colour
using castor::Colour = typedef ColourT< ColourComponent >
ContainerBox2D
using castor::ContainerBox2D = typedef ContainerBox< 2 >
Typedef on a 2 dimensions ContainerBox.
Author
Sylvain DOREMUS
Date
14/02/2010
ContainerBox3D
using castor::ContainerBox3D = typedef ContainerBox< 3 >
Typedef on a 3 dimensions ContainerBox.
Author
Sylvain DOREMUS
Date
14/02/2010
Coords2
template<typename T > using castor::Coords2 = typedef Coords< T, 2 >
Coords3
template<typename T > using castor::Coords3 = typedef Coords< T, 3 >
Coords4
template<typename T > using castor::Coords4 = typedef Coords< T, 4 >
HdrColour
using castor::HdrColour = typedef ColourT< HdrColourComponent >
InputStream
using castor::InputStream = typedef std::basic_istream< xchar >
InputStringStream
using castor::InputStringStream = typedef std::basic_istringstream< xchar >
LogCallback
using castor::LogCallback = typedef std::function< void (String const & text, LogType type, bool newLine) >
Logging callback function.
Parameters
[in] text The logged text.
[in] type The log type.
[in] newLine Tells if we add the end line character.
MatchResults
using castor::MatchResults = typedef std::match_results< String::const_iterator >
MessageQueue
using castor::MessageQueue = typedef std::deque< Message >
The message queue.
Microseconds
using castor::Microseconds = typedef std::chrono::microseconds
Milliseconds
using castor::Milliseconds = typedef std::chrono::milliseconds
Named
typedef NamedBase< String > castor::Named
A typedef for NamedBase with String as a name
Nanoseconds
using castor::Nanoseconds = typedef std::chrono::nanoseconds
OutputStream
using castor::OutputStream = typedef std::basic_ostream< xchar >
OutputStringStream
using castor::OutputStringStream = typedef std::basic_ostringstream< xchar >
ParserFunction
typedef std::function< bool(castor::FileParser * p_parser, ParserParameterArray const & p_params) > castor::ParserFunction
Parser function definition.
Parameters
[in] p_parser The file parser.
[in] p_params The params contained in the line.
Returns
true if a brace is to be opened on next line.
PixelBuffer
using castor::PixelBuffer = typedef PxBuffer< PixelFormat::eA8R8G8B8 >
Typedef over a buffer of pixels in format A8R8G8B8.
Author
Sylvain DOREMUS
Point2
template<typename T > using castor::Point2 = typedef Point< T, 2 >
Point3
template<typename T > using castor::Point3 = typedef Point< T, 3 >
Point4
template<typename T > using castor::Point4 = typedef Point< T, 4 >
Quaternion
using castor::Quaternion = typedef QuaternionT< real >
real
using castor::real = typedef float
Regex
using castor::Regex = typedef std::basic_regex< xchar >
RegexIterator
using castor::RegexIterator = typedef std::regex_iterator< String::const_iterator >
Seconds
using castor::Seconds = typedef std::chrono::seconds
String
using castor::String = typedef std::basic_string< xchar >
StringStream
using castor::StringStream = typedef std::basic_stringstream< xchar >
UbPixel
typedef Pixel< PixelFormat::eA8R8G8B8 > castor::UbPixel
Typedef over a pixel in A8R8G8B8 format.
Author
Sylvain DOREMUS
Enumeration Type Documentation
Component
enum castor::Component : uint8_t strong
ColourT components enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Enumerator
eRed
Red PixelComponents.
eGreen
Green PixelComponents.
eBlue
Blue PixelComponents.
eAlpha
Alpha PixelComponents.
FileType
enum castor::FileType : uint8_t strong
castor::Loader supported file types enumeration
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Enumerator
eBinary
Binary file.
eText
Text file.
Intersection
enum castor::Intersection : uint8_t strong
Intersection types.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Remarks
Enumerates the different intersection types.
Enumerator
eIn
Completely inside.
eOut
Completely outside.
eIntersect
Intersection.
LogType
enum castor::LogType : uint8_t strong
Defines the various log types.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Enumerator
eTrace
Trace type log.
eDebug
Debug type log.
eInfo
Information type log.
eWarning
Warning type log.
eError
Error type log.
eCount
Log types count.
MemoryDataType
enum castor::MemoryDataType strong
Supported MemoryData types.
Enumerator
eFixed
eMarked
eFixedGrowing
eFixedGrowingMarked
ParameterType
enum castor::ParameterType : uint8_t strong
Parser function parameter types enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
04/02/2013
Enumerator
eText
eName
ePath
eCheckedText
eBitwiseOred32BitsCheckedText
eBitwiseOred64BitsCheckedText
eBool
eInt8
eInt16
eInt32
eInt64
eUInt8
eUInt16
eUInt32
eUInt64
eFloat
eDouble
eLongDouble
ePixelFormat
ePoint2I
ePoint3I
ePoint4I
ePoint2F
ePoint3F
ePoint4F
ePoint2D
ePoint3D
ePoint4D
eSize
ePosition
eRectangle
eColour
eHdrColour
PixelComponent
enum castor::PixelComponent : uint8_t strong
Pixel PixelComponents enumeration.
Enumerator
eRed
Red.
eGreen
Green.
eBlue
Blue.
eAlpha
Alpha.
eLuminance
Luminance.
eDepth
Depth.
eStencil
Stencil.
PixelFormat
enum castor::PixelFormat : uint8_t strong
Pixel format enumeration.
Enumerator
eL8
8 bits luminosity.
eL16F32F
Half floats luminosity on VRAM, floats luminosity on RAM.
eL32F
32 bits loats luminosity.
eA8L8
16 bits alpha and luminosity.
eAL16F32F
Half floats alpha and luminosity on VRAM, floats alpha and luminosity on RAM.
eAL32F
32 bits floats alpha and luminosity.
eA1R5G5B5
16 bits 5551 ARGB.
eA4R4G4B4
16 bits 4444 ARGB.
eR5G6B5
16 bits 565 RGB.
eR8G8B8
24 bits 888 RGB.
eB8G8R8
24 bits 888 BGR.
eR8G8B8_SRGB
24 bits 888 RGB in sRGB colour space.
eB8G8R8_SRGB
24 bits 888 BGR in sRGB colour space.
eA8R8G8B8
32 bits 8888 ARGB.
eA8B8G8R8
32 bits 8888 ABGR.
eA8R8G8B8_SRGB
32 bits 8888 ARGB in sRGB colour space.
eA8B8G8R8_SRGB
32 bits 8888 ABGR in sRGB colour space.
eRGB16F
Half float RGB.
eRGBA16F
Half float ARGB.
eRGB16F32F
Half float RGB on VRAM, Float RGB on RAM.
eRGBA16F32F
Half float ARGB on VRAM, Float ARGB on RAM.
eRGB32F
32 bits float RGB.
eRGBA32F
32 bits float ARGB.
eDXTC1
DXT1 8 bits compressed format.
eDXTC3
DXT3 16 bits compressed format.
eDXTC5
DXT5 16 bits compressed format.
eYUY2
YUY2 16 bits compressed format.
eD16
Depth 16 bits.
eD24
Depth 24 bits.
eD24S8
Depth 24 bits, Stencil 8 bits.
eD32
Depth 32 bits.
eD32F
Depth 32 bits floating point.
eD32FS8
Depth 32 bits floating point, Stencil 8 bits.
eS1
Stencil 1 bit.
eS8
Stencil 8 bits.
PoolErrorType
enum castor::PoolErrorType strong
Pool errors enumeration.
Enumerator
eCommonOutOfMemory
eCommonPoolIsFull
eCommonMemoryLeaksDetected
eCommonNotFromRange
eMarkedLeakAddress
eMarkedDoubleDelete
eMarkedNotFromPool
eGrowingNotFromRanges
eSTLAllocatorUnique
PredefinedColour
enum castor::PredefinedColour : uint32_t strong
Predefined colours enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Enumerator
eTransparentBlack
eLowAlphaBlack
eMedAlphaBlack
eHighAlphaBlack
eOpaqueBlack
eTransparentDarkBlue
eLowAlphaDarkBlue
eMedAlphaDarkBlue
eHighAlphaDarkBlue
eOpaqueDarkBlue
eTransparentBlue
eLowAlphaBlue
eMedAlphaBlue
eHighAlphaBlue
eOpaqueBlue
eTransparentDarkGreen
eLowAlphaDarkGreen
eMedAlphaDarkGreen
eHighAlphaDarkGreen
eOpaqueDarkGreen
eTransparentGreen
eLowAlphaGreen
eMedAlphaGreen
eHighAlphaGreen
eOpaqueGreen
eTransparentDarkRed
eLowAlphaDarkRed
eMedAlphaDarkRed
eHighAlphaDarkRed
eOpaqueDarkRed
eTransparentRed
eLowAlphaRed
eMedAlphaRed
eHighAlphaRed
eOpaqueRed
eTransparentLightBlue
eLowAlphaLightBlue
eMedAlphaLightBlue
eHighAlphaLightBlue
eOpaqueLightBlue
eTransparentLightGreen
eLowAlphaLightGreen
eMedAlphaLightGreen
eHighAlphaLightGreen
eOpaqueLightGreen
eTransparentLightRed
eLowAlphaLightRed
eMedAlphaLightRed
eHighAlphaLightRed
eOpaqueLightRed
eTransparentWhite
eLowAlphaWhite
eMedAlphaWhite
eHighAlphaWhite
eOpaqueWhite
UnicityError
enum castor::UnicityError strong
Unicity errors enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
12/01/2016
Enumerator
eNoInstance
eAnInstance
Function Documentation
addFlag() [1/2]
template<typename FlagType , typename Type > FlagCombination< FlagType, Type >& castor::addFlag (FlagCombination< FlagType, Type > & p_value, FlagType const & p_flag) inline noexcept
adds a flag to the given value.
Parameters
[in,out] p_value The value.
[in] p_flag The flag to add.
Returns
The value.
addFlag() [2/2]
template<typename FlagType , typename Type > FlagCombination< FlagType, Type > castor::addFlag (FlagCombination< FlagType, Type > const & p_value, FlagType const & p_flag) inline noexcept
adds a flag to the given value.
Parameters
[in] p_value The value.
[in] p_flag The flag to add.
Returns
The new value.
addFlags()
template<typename FlagType , typename Type > FlagCombination< FlagType, Type >& castor::addFlags (FlagCombination< FlagType, Type > & p_value, FlagCombination< FlagType, Type > const & p_flags) inline noexcept
adds a flag combination to the given value.
Parameters
[in,out] p_value The value.
[in] p_flags The flag combination to add.
Returns
The value.
alignedAlloc()
T * castor::alignedAlloc (size_t p_alignment, size_t p_size)
Allocates aligned memory.
Parameters
[in] p_alignment The alignment value, must be a power of two.
[in] p_size The wanted size.
Returns
The allocated memory, nullptr on error.
Referenced by castor::AlignedMemoryAllocator< Align >::allocate(), and CASTOR_ALIGNED_DECL().
alignedFree()
CU_API void castor::alignedFree (void * p_memory)
Deallocates aligned memory.
Parameters
[in] p_memory The memory.
Referenced by CASTOR_ALIGNED_DECL(), castor::MatrixDataAllocator< T, Columns, Rows >::deallocate(), and castor::AlignedMemoryAllocator< Align >::deallocate().
bigEndianToSystemEndian() [1/6]
template<typename T > T& castor::bigEndianToSystemEndian (T & value) inline noexcept
Convert the given big endian value to system endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [2/6]
template<typename T > T castor::bigEndianToSystemEndian (T const & value) inline
Convert the given big endian value to system endian if needed.
Parameters
[in,out] value Value to be converted.
References switchEndianness().
bigEndianToSystemEndian() [3/6]
template<typename T , size_t N> std::array< T, N >& castor::bigEndianToSystemEndian (std::array< T, N > & value) inline noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [4/6]
template<typename T , size_t N> std::array< T, N > castor::bigEndianToSystemEndian (std::array< T, N > const & value) inline
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [5/6]
template<typename T > std::vector< T >& castor::bigEndianToSystemEndian (std::vector< T > & value) inline noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [6/6]
template<typename T > std::vector< T > castor::bigEndianToSystemEndian (std::vector< T > const & value) inline
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
CASTOR_ALIGNED_DECL() [1/2]
template<typename T > class castor::CASTOR_ALIGNED_DECL (alignof(T))
Templated class that provide alignment support.
Author
Sylvain DOREMUS
Version
0.8.0
Date
03/10/2015
References alignedAlloc(), and alignedFree().
CASTOR_ALIGNED_DECL() [2/2]
template<int A> class castor::CASTOR_ALIGNED_DECL (A)
Templated class that provide alignment support.
Author
Sylvain DOREMUS
Version
0.8.0
Date
03/10/2015
References alignedAlloc(), and alignedFree().
checkFlag() [1/3]
template<typename T , typename U > bool castor::checkFlag (T const & p_value, U const & p_flag) inline noexcept
Parameters
[in] p_value The value.
[in] p_flag The flag looked for.
Returns
true if p_flags contain p_flag.
checkFlag() [2/3]
template<typename FlagType , typename Type > bool castor::checkFlag (FlagCombination< FlagType, Type > const & p_value, FlagType const & p_flag) inline noexcept
Parameters
[in] p_value The value.
[in] p_flag The flag looked for.
Returns
true if p_flags contain p_flag.
checkFlag() [3/3]
template<typename FlagType , typename Type > bool castor::checkFlag (FlagCombination< FlagType, Type > const & p_value, Type const & p_flag) inline noexcept
Parameters
[in] p_value The value.
[in] p_flag The flag looked for.
Returns
true if p_flags contain p_flag.
cuAssert()
template<typename Expr > void castor::cuAssert (Expr const & p_expr, char const *const p_description) inline
Checks an assertion.
Parameters
[in] p_expr The expression to test.
[in] p_description The assertion description.
References castor::Logger::logError().
DECLARE_CONST_COORD() [1/33]
castor::DECLARE_CONST_COORD (bool , 4 , b)
DECLARE_CONST_COORD() [2/33]
castor::DECLARE_CONST_COORD (bool , 3 , b)
DECLARE_CONST_COORD() [3/33]
castor::DECLARE_CONST_COORD (bool , 2 , b)
DECLARE_CONST_COORD() [4/33]
castor::DECLARE_CONST_COORD (int8_t , 4 , c)
DECLARE_CONST_COORD() [5/33]
castor::DECLARE_CONST_COORD (int8_t , 3 , c)
DECLARE_CONST_COORD() [6/33]
castor::DECLARE_CONST_COORD (int8_t , 2 , c)
DECLARE_CONST_COORD() [7/33]
castor::DECLARE_CONST_COORD (uint8_t , 4 , ub)
DECLARE_CONST_COORD() [8/33]
castor::DECLARE_CONST_COORD (uint8_t , 3 , ub)
DECLARE_CONST_COORD() [9/33]
castor::DECLARE_CONST_COORD (uint8_t , 2 , ub)
DECLARE_CONST_COORD() [10/33]
castor::DECLARE_CONST_COORD (int16_t , 4 , s)
DECLARE_CONST_COORD() [11/33]
castor::DECLARE_CONST_COORD (int16_t , 3 , s)
DECLARE_CONST_COORD() [12/33]
castor::DECLARE_CONST_COORD (int16_t , 2 , s)
DECLARE_CONST_COORD() [13/33]
castor::DECLARE_CONST_COORD (uint16_t , 4 , us)
DECLARE_CONST_COORD() [14/33]
castor::DECLARE_CONST_COORD (uint16_t , 3 , us)
DECLARE_CONST_COORD() [15/33]
castor::DECLARE_CONST_COORD (uint16_t , 2 , us)
DECLARE_CONST_COORD() [16/33]
castor::DECLARE_CONST_COORD (int32_t , 4 , i)
DECLARE_CONST_COORD() [17/33]
castor::DECLARE_CONST_COORD (int32_t , 3 , i)
DECLARE_CONST_COORD() [18/33]
castor::DECLARE_CONST_COORD (int32_t , 2 , i)
DECLARE_CONST_COORD() [19/33]
castor::DECLARE_CONST_COORD (uint32_t , 4 , ui)
DECLARE_CONST_COORD() [20/33]
castor::DECLARE_CONST_COORD (uint32_t , 3 , ui)
DECLARE_CONST_COORD() [21/33]
castor::DECLARE_CONST_COORD (uint32_t , 2 , ui)
DECLARE_CONST_COORD() [22/33]
castor::DECLARE_CONST_COORD (int , 4 , i)
DECLARE_CONST_COORD() [23/33]
castor::DECLARE_CONST_COORD (int , 3 , i)
DECLARE_CONST_COORD() [24/33]
castor::DECLARE_CONST_COORD (int , 2 , i)
DECLARE_CONST_COORD() [25/33]
castor::DECLARE_CONST_COORD (real , 4 , r)
DECLARE_CONST_COORD() [26/33]
castor::DECLARE_CONST_COORD (real , 3 , r)
DECLARE_CONST_COORD() [27/33]
castor::DECLARE_CONST_COORD (real , 2 , r)
DECLARE_CONST_COORD() [28/33]
castor::DECLARE_CONST_COORD (float , 4 , f)
DECLARE_CONST_COORD() [29/33]
castor::DECLARE_CONST_COORD (float , 3 , f)
DECLARE_CONST_COORD() [30/33]
castor::DECLARE_CONST_COORD (float , 2 , f)
DECLARE_CONST_COORD() [31/33]
castor::DECLARE_CONST_COORD (double , 4 , d)
DECLARE_CONST_COORD() [32/33]
castor::DECLARE_CONST_COORD (double , 3 , d)
DECLARE_CONST_COORD() [33/33]
castor::DECLARE_CONST_COORD (double , 2 , d)
DECLARE_COORD() [1/33]
castor::DECLARE_COORD (bool , 4 , b)
DECLARE_COORD() [2/33]
castor::DECLARE_COORD (bool , 3 , b)
DECLARE_COORD() [3/33]
castor::DECLARE_COORD (bool , 2 , b)
DECLARE_COORD() [4/33]
castor::DECLARE_COORD (int8_t , 4 , c)
DECLARE_COORD() [5/33]
castor::DECLARE_COORD (int8_t , 3 , c)
DECLARE_COORD() [6/33]
castor::DECLARE_COORD (int8_t , 2 , c)
DECLARE_COORD() [7/33]
castor::DECLARE_COORD (uint8_t , 4 , ub)
DECLARE_COORD() [8/33]
castor::DECLARE_COORD (uint8_t , 3 , ub)
DECLARE_COORD() [9/33]
castor::DECLARE_COORD (uint8_t , 2 , ub)
DECLARE_COORD() [10/33]
castor::DECLARE_COORD (int16_t , 4 , s)
DECLARE_COORD() [11/33]
castor::DECLARE_COORD (int16_t , 3 , s)
DECLARE_COORD() [12/33]
castor::DECLARE_COORD (int16_t , 2 , s)
DECLARE_COORD() [13/33]
castor::DECLARE_COORD (uint16_t , 4 , us)
DECLARE_COORD() [14/33]
castor::DECLARE_COORD (uint16_t , 3 , us)
DECLARE_COORD() [15/33]
castor::DECLARE_COORD (uint16_t , 2 , us)
DECLARE_COORD() [16/33]
castor::DECLARE_COORD (int32_t , 4 , i)
DECLARE_COORD() [17/33]
castor::DECLARE_COORD (int32_t , 3 , i)
DECLARE_COORD() [18/33]
castor::DECLARE_COORD (int32_t , 2 , i)
DECLARE_COORD() [19/33]
castor::DECLARE_COORD (uint32_t , 4 , ui)
DECLARE_COORD() [20/33]
castor::DECLARE_COORD (uint32_t , 3 , ui)
DECLARE_COORD() [21/33]
castor::DECLARE_COORD (uint32_t , 2 , ui)
DECLARE_COORD() [22/33]
castor::DECLARE_COORD (int , 4 , i)
DECLARE_COORD() [23/33]
castor::DECLARE_COORD (int , 3 , i)
DECLARE_COORD() [24/33]
castor::DECLARE_COORD (int , 2 , i)
DECLARE_COORD() [25/33]
castor::DECLARE_COORD (real , 4 , r)
DECLARE_COORD() [26/33]
castor::DECLARE_COORD (real , 3 , r)
DECLARE_COORD() [27/33]
castor::DECLARE_COORD (real , 2 , r)
DECLARE_COORD() [28/33]
castor::DECLARE_COORD (float , 4 , f)
DECLARE_COORD() [29/33]
castor::DECLARE_COORD (float , 3 , f)
DECLARE_COORD() [30/33]
castor::DECLARE_COORD (float , 2 , f)
DECLARE_COORD() [31/33]
castor::DECLARE_COORD (double , 4 , d)
DECLARE_COORD() [32/33]
castor::DECLARE_COORD (double , 3 , d)
DECLARE_COORD() [33/33]
castor::DECLARE_COORD (double , 2 , d)
DECLARE_MAP() [1/5]
castor::DECLARE_MAP (String , uint32_t , UIntStr)
DECLARE_MAP() [2/5]
castor::DECLARE_MAP (String , uint64_t , UInt64Str)
DECLARE_MAP() [3/5]
castor::DECLARE_MAP (String , bool , BoolStr)
DECLARE_MAP() [4/5]
castor::DECLARE_MAP (String , String , StrStr)
DECLARE_MAP() [5/5]
castor::DECLARE_MAP (uint32_t , String , StrUInt)
DECLARE_MTX() [1/36]
castor::DECLARE_MTX (bool , 2 , 3 , b)
DECLARE_MTX() [2/36]
castor::DECLARE_MTX (bool , 2 , 4 , b)
DECLARE_MTX() [3/36]
castor::DECLARE_MTX (bool , 3 , 2 , b)
DECLARE_MTX() [4/36]
castor::DECLARE_MTX (bool , 3 , 4 , b)
DECLARE_MTX() [5/36]
castor::DECLARE_MTX (bool , 4 , 2 , b)
DECLARE_MTX() [6/36]
castor::DECLARE_MTX (bool , 4 , 3 , b)
DECLARE_MTX() [7/36]
castor::DECLARE_MTX (int , 2 , 3 , i)
DECLARE_MTX() [8/36]
castor::DECLARE_MTX (int , 2 , 4 , i)
DECLARE_MTX() [9/36]
castor::DECLARE_MTX (int , 3 , 2 , i)
DECLARE_MTX() [10/36]
castor::DECLARE_MTX (int , 3 , 4 , i)
DECLARE_MTX() [11/36]
castor::DECLARE_MTX (int , 4 , 2 , i)
DECLARE_MTX() [12/36]
castor::DECLARE_MTX (int , 4 , 3 , i)
DECLARE_MTX() [13/36]
castor::DECLARE_MTX (uint32_t , 2 , 3 , ui)
DECLARE_MTX() [14/36]
castor::DECLARE_MTX (uint32_t , 2 , 4 , ui)
DECLARE_MTX() [15/36]
castor::DECLARE_MTX (uint32_t , 3 , 2 , ui)
DECLARE_MTX() [16/36]
castor::DECLARE_MTX (uint32_t , 3 , 4 , ui)
DECLARE_MTX() [17/36]
castor::DECLARE_MTX (uint32_t , 4 , 2 , ui)
DECLARE_MTX() [18/36]
castor::DECLARE_MTX (uint32_t , 4 , 3 , ui)
DECLARE_MTX() [19/36]
castor::DECLARE_MTX (real , 2 , 3 , r)
DECLARE_MTX() [20/36]
castor::DECLARE_MTX (real , 2 , 4 , r)
DECLARE_MTX() [21/36]
castor::DECLARE_MTX (real , 3 , 2 , r)
DECLARE_MTX() [22/36]
castor::DECLARE_MTX (real , 3 , 4 , r)
DECLARE_MTX() [23/36]
castor::DECLARE_MTX (real , 4 , 2 , r)
DECLARE_MTX() [24/36]
castor::DECLARE_MTX (real , 4 , 3 , r)
DECLARE_MTX() [25/36]
castor::DECLARE_MTX (float , 2 , 3 , f)
DECLARE_MTX() [26/36]
castor::DECLARE_MTX (float , 2 , 4 , f)
DECLARE_MTX() [27/36]
castor::DECLARE_MTX (float , 3 , 2 , f)
DECLARE_MTX() [28/36]
castor::DECLARE_MTX (float , 3 , 4 , f)
DECLARE_MTX() [29/36]
castor::DECLARE_MTX (float , 4 , 2 , f)
DECLARE_MTX() [30/36]
castor::DECLARE_MTX (float , 4 , 3 , f)
DECLARE_MTX() [31/36]
castor::DECLARE_MTX (double , 2 , 3 , d)
DECLARE_MTX() [32/36]
castor::DECLARE_MTX (double , 2 , 4 , d)
DECLARE_MTX() [33/36]
castor::DECLARE_MTX (double , 3 , 2 , d)
DECLARE_MTX() [34/36]
castor::DECLARE_MTX (double , 3 , 4 , d)
DECLARE_MTX() [35/36]
castor::DECLARE_MTX (double , 4 , 2 , d)
DECLARE_MTX() [36/36]
castor::DECLARE_MTX (double , 4 , 3 , d)
DECLARE_POINT() [1/30]
castor::DECLARE_POINT (bool , 4 , b)
DECLARE_POINT() [2/30]
castor::DECLARE_POINT (bool , 3 , b)
DECLARE_POINT() [3/30]
castor::DECLARE_POINT (bool , 2 , b)
DECLARE_POINT() [4/30]
castor::DECLARE_POINT (int8_t , 4 , c)
DECLARE_POINT() [5/30]
castor::DECLARE_POINT (int8_t , 3 , c)
DECLARE_POINT() [6/30]
castor::DECLARE_POINT (int8_t , 2 , c)
DECLARE_POINT() [7/30]
castor::DECLARE_POINT (uint8_t , 4 , ub)
DECLARE_POINT() [8/30]
castor::DECLARE_POINT (uint8_t , 3 , ub)
DECLARE_POINT() [9/30]
castor::DECLARE_POINT (uint8_t , 2 , ub)
DECLARE_POINT() [10/30]
castor::DECLARE_POINT (int16_t , 4 , s)
DECLARE_POINT() [11/30]
castor::DECLARE_POINT (int16_t , 3 , s)
DECLARE_POINT() [12/30]
castor::DECLARE_POINT (int16_t , 2 , s)
DECLARE_POINT() [13/30]
castor::DECLARE_POINT (uint16_t , 4 , us)
DECLARE_POINT() [14/30]
castor::DECLARE_POINT (uint16_t , 3 , us)
DECLARE_POINT() [15/30]
castor::DECLARE_POINT (uint16_t , 2 , us)
DECLARE_POINT() [16/30]
castor::DECLARE_POINT (int32_t , 4 , i)
DECLARE_POINT() [17/30]
castor::DECLARE_POINT (int32_t , 3 , i)
DECLARE_POINT() [18/30]
castor::DECLARE_POINT (int32_t , 2 , i)
DECLARE_POINT() [19/30]
castor::DECLARE_POINT (uint32_t , 4 , ui)
DECLARE_POINT() [20/30]
castor::DECLARE_POINT (uint32_t , 3 , ui)
DECLARE_POINT() [21/30]
castor::DECLARE_POINT (uint32_t , 2 , ui)
DECLARE_POINT() [22/30]
castor::DECLARE_POINT (real , 4 , r)
DECLARE_POINT() [23/30]
castor::DECLARE_POINT (real , 3 , r)
DECLARE_POINT() [24/30]
castor::DECLARE_POINT (real , 2 , r)
DECLARE_POINT() [25/30]
castor::DECLARE_POINT (float , 4 , f)
DECLARE_POINT() [26/30]
castor::DECLARE_POINT (float , 3 , f)
DECLARE_POINT() [27/30]
castor::DECLARE_POINT (float , 2 , f)
DECLARE_POINT() [28/30]
castor::DECLARE_POINT (double , 4 , d)
DECLARE_POINT() [29/30]
castor::DECLARE_POINT (double , 3 , d)
DECLARE_POINT() [30/30]
castor::DECLARE_POINT (double , 2 , d)
DECLARE_SET()
castor::DECLARE_SET (String , Str)
DECLARE_SMART_PTR() [1/10]
castor::DECLARE_SMART_PTR (Quaternion)
Referenced by castor::DynamicLibrary::getPath().
DECLARE_SMART_PTR() [2/10]
castor::DECLARE_SMART_PTR (SphericalVertex)
DECLARE_SMART_PTR() [3/10]
castor::DECLARE_SMART_PTR (CubeBox)
DECLARE_SMART_PTR() [4/10]
castor::DECLARE_SMART_PTR (SphereBox)
DECLARE_SMART_PTR() [5/10]
castor::DECLARE_SMART_PTR (Image)
DECLARE_SMART_PTR() [6/10]
castor::DECLARE_SMART_PTR (Font)
DECLARE_SMART_PTR() [7/10]
castor::DECLARE_SMART_PTR (PxBufferBase)
DECLARE_SMART_PTR() [8/10]
castor::DECLARE_SMART_PTR (FileParserContext)
DECLARE_SMART_PTR() [9/10]
castor::DECLARE_SMART_PTR (ParserParameterBase)
DECLARE_SMART_PTR() [10/10]
castor::DECLARE_SMART_PTR (DynamicLibrary)
Typedef on a pointer to a DynamicLibrary.
Author
Sylvain DOREMUS
Date
03/01/2011
DECLARE_SQMTX() [1/18]
castor::DECLARE_SQMTX (bool , 4 , b)
DECLARE_SQMTX() [2/18]
castor::DECLARE_SQMTX (bool , 3 , b)
DECLARE_SQMTX() [3/18]
castor::DECLARE_SQMTX (bool , 2 , b)
DECLARE_SQMTX() [4/18]
castor::DECLARE_SQMTX (int , 4 , i)
DECLARE_SQMTX() [5/18]
castor::DECLARE_SQMTX (int , 3 , i)
DECLARE_SQMTX() [6/18]
castor::DECLARE_SQMTX (int , 2 , i)
DECLARE_SQMTX() [7/18]
castor::DECLARE_SQMTX (uint32_t , 4 , ui)
DECLARE_SQMTX() [8/18]
castor::DECLARE_SQMTX (uint32_t , 3 , ui)
DECLARE_SQMTX() [9/18]
castor::DECLARE_SQMTX (uint32_t , 2 , ui)
DECLARE_SQMTX() [10/18]
castor::DECLARE_SQMTX (real , 4 , r)
DECLARE_SQMTX() [11/18]
castor::DECLARE_SQMTX (real , 3 , r)
DECLARE_SQMTX() [12/18]
castor::DECLARE_SQMTX (real , 2 , r)
DECLARE_SQMTX() [13/18]
castor::DECLARE_SQMTX (float , 4 , f)
DECLARE_SQMTX() [14/18]
castor::DECLARE_SQMTX (float , 3 , f)
DECLARE_SQMTX() [15/18]
castor::DECLARE_SQMTX (float , 2 , f)
DECLARE_SQMTX() [16/18]
castor::DECLARE_SQMTX (double , 4 , d)
DECLARE_SQMTX() [17/18]
castor::DECLARE_SQMTX (double , 3 , d)
DECLARE_SQMTX() [18/18]
castor::DECLARE_SQMTX (double , 2 , d)
DECLARE_VECTOR() [1/6]
castor::DECLARE_VECTOR (uint8_t , Byte)
DECLARE_VECTOR() [2/6]
castor::DECLARE_VECTOR (SphericalVertexSPtr , SphericalVertexPtr)
DECLARE_VECTOR() [3/6]
castor::DECLARE_VECTOR (int , Int)
DECLARE_VECTOR() [4/6]
castor::DECLARE_VECTOR (String , String)
DECLARE_VECTOR() [5/6]
castor::DECLARE_VECTOR (Path , Path)
DECLARE_VECTOR() [6/6]
castor::DECLARE_VECTOR (ParserParameterBaseSPtr , ParserParameter)
fileOpen()
CU_API bool castor::fileOpen (FILE *& p_pFile, char const * p_pszPath, char const * p_pszMode)
Opens a file.
Parameters
[out] p_pFile Receives the file descriptor
[in] p_pszPath The file path
[in] p_pszMode The opening mode
Returns
true on success
fileOpen64()
CU_API bool castor::fileOpen64 (FILE *& p_pFile, char const * p_pszPath, char const * p_pszMode)
Opens a file.
Parameters
[out] p_pFile Receives the file descriptor
[in] p_pszPath The file path
[in] p_pszMode The opening mode
Returns
true on success
fileSeek()
CU_API bool castor::fileSeek (FILE * p_pFile, int64_t p_offset, int p_iOrigin)
Seeks into a file.
Parameters
[in] p_pFile The file descriptor
[in] p_offset The seek offset
[in] p_iOrigin The seek origin
Returns
true on success
fileTell()
CU_API int64_t castor::fileTell (FILE * p_pFile)
Retrieves the file cursor position.
Parameters
[out] p_pFile The file descriptor
Returns
The position
getLocaltime()
void castor::getLocaltime (std::tm * p_tm, time_t const * p_pTime)
See also
localtime
getNext2Pow()
CU_API uint32_t castor::getNext2Pow (uint32_t p_uiDim)
getPredefined()
static PredefinedColour castor::getPredefined (String const & p_name) inline static
Retrieves predefined colour from a name.
Parameters
[in] p_name The predefined colour name
Returns
The predefined colour
getPredefinedName()
static String castor::getPredefinedName (PredefinedColour p_predefined) inline static
Retrieves predefined colour name.
Parameters
[in] p_predefined The predefined colour
Returns
The colour name
getTypeName()
CU_API String const& castor::getTypeName (ParameterType p_type)
Retrieves the given parameter type's name.
Parameters
[in] p_type The parameter type.
Referenced by castor::ParserParameterTypeException< GivenType >::ParserParameterTypeException().
isBigEndian()
bool castor::isBigEndian () inline noexcept
Detects if the current system is big endian.
References castor::details::BigInt.
Referenced by bigEndianToSystemEndian(), and systemEndianToBigEndian().
isInf()
int castor::isInf (double x) inline
Tests if a double is infinite.
Remarks
It is infinite if x==x and x-x!=0
Parameters
[in] x Number to test
Returns
-1 if negative infinite, 1 if positive infinite, 0 if not infinite
isNan()
bool castor::isNan (double x) inline
Tests if a double is a number.
Remarks
It is a number as long as x==x
Parameters
[in] x Number to test
Returns
The result
makeArrayView() [1/3]
template<typename T > ArrayView< T > castor::makeArrayView (T * p_begin, size_t p_size)
makeArrayView() [2/3]
template<typename T > ArrayView< T > castor::makeArrayView (T * p_begin, T * p_end)
makeArrayView() [3/3]
template<typename T , size_t N> ArrayView< T > castor::makeArrayView (T(&) p_buffer[N])
makeBlockGuard()
template<typename InitFunc , typename CleanFunc > BlockGuard< CleanFunc > castor::makeBlockGuard (InitFunc p_init, CleanFunc p_clean)
Helper function to declare a BlockGuard.
Parameters
[in] p_init The action executed on construction.
[in] p_clean The action executed on destruction.
Returns
The block guard.
makeChangeTracked()
template<typename T > ChangeTracked< T > castor::makeChangeTracked (T const & value)
makeParameter() [1/4]
template<ParameterType Type> ParserParameterBaseSPtr castor::makeParameter ()
Creates a parameter of given type.
Returns
The created parameter.
makeParameter() [2/4]
template<ParameterType Type, typename T > ParserParameterBaseSPtr castor::makeParameter (Range< T > const & range)
Creates a parameter of given type.
Returns
The created parameter.
References eDouble, eFloat, eInt16, eInt32, eInt64, eInt8, eLongDouble, eUInt16, eUInt32, eUInt64, and eUInt8.
makeParameter() [3/4]
template<ParameterType Type> ParserParameterBaseSPtr castor::makeParameter (UIntStrMap const & p_values)
Creates a parameter of given type.
Parameters
[in] p_values The values used to validate the parsed value.
Returns
The created parameter.
References eBitwiseOred32BitsCheckedText, and eCheckedText.
makeParameter() [4/4]
template<ParameterType Type> ParserParameterBaseSPtr castor::makeParameter (UInt64StrMap const & p_values)
Creates a parameter of given type.
Parameters
[in] p_values The values used to validate the parsed value.
Returns
The created parameter.
References eBitwiseOred64BitsCheckedText.
makeRange()
template<typename T > Range< T > castor::makeRange (T const & p_min, T const & p_max) inline noexcept
Helper function to create a range.
Parameters
[in] p_min,p_max The range.
Returns
The created range.
Referenced by makeRangedValue(), and castor::ParserParameter< Type, typename std::enable_if< IsArithmeticType< Type >::value >::type >::ParserParameter().
makeRangedValue()
template<typename T > RangedValue< T > castor::makeRangedValue (T const & p_value, T const & p_min, T const & p_max) inline noexcept
Helper function to create a ranged value.
Parameters
[in] p_value The value.
[in] p_min,p_max The range.
Returns
The created ranged value.
References makeRange().
makeScopeGuard()
template<typename ScopeExitFuncType > ScopeGuard< ScopeExitFuncType > castor::makeScopeGuard (ScopeExitFuncType const & p_function)
Helper function to create a ScopeGuard.
Parameters
[in] p_function The function.
Returns
The ScopeGuard.
makeUniqueLock()
template<typename Lockable > std::unique_lock< Lockable > castor::makeUniqueLock (Lockable & p_lockable)
operator &()
template<typename FlagType , typename Type > FlagCombination< FlagType, Type > castor::operator& (FlagCombination< FlagType, Type > const & p_lhs, FlagType const & p_rhs) inline noexcept
Binary AND operator.
Parameters
[in] p_lhs,p_rhs The operands.
Returns
The resulting flags combination.
operator!=() [1/25]
template<typename T > bool castor::operator!= (GroupChangeTracked< T > const & lhs, T const & rhs)
References operator==().
operator!=() [2/25]
template<typename T > bool castor::operator!= (T const & lhs, GroupChangeTracked< T > const & rhs)
References operator==().
operator!=() [3/25]
template<typename T > bool castor::operator!= (ChangeTracked< T > const & lhs, T const & rhs)
References operator==().
Referenced by castor::Coords< uint32_t, 2 >::end(), castor::Point< real, Dimension >::end(), castor::AngleT< Type >::fromGrads(), castor::ColourT< ComponentType >::operator/=(), castor::HdrColourComponent::value(), and castor::ColourComponent::value().
operator!=() [4/25]
template<typename T > bool castor::operator!= (GroupChangeTracked< T > const & lhs, GroupChangeTracked< T > const & rhs)
References operator==().
operator!=() [5/25]
template<typename T > bool castor::operator!= (T const & lhs, ChangeTracked< T > const & rhs)
References operator==().
operator!=() [6/25]
template<typename T > bool castor::operator!= (ChangeTracked< T > const & lhs, ChangeTracked< T > const & rhs)
References operator==().
operator!=() [7/25]
bool castor::operator!= (Glyph const & p_lhs, Glyph const & p_rhs) inline
Difference comparison operator.
Parameters
[in] p_lhs,p_rhs The values to compare.
References castor::Glyph::getCharacter().
operator!=() [8/25]
CU_API bool castor::operator!= (Position const & p_a, Position const & p_b)
Difference operator.
Parameters
[in] p_a,p_b The positions to compare
Returns
false if positions have same coordinates
operator!=() [9/25]
CU_API bool castor::operator!= (Size const & p_a, Size const & p_b)
Difference operator.
Parameters
[in] p_a,p_b The sizes to compare
Returns
false if sizes have same dimensions
operator!=() [10/25]
template<typename T > bool castor::operator!= (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator!=() [11/25]
CU_API bool castor::operator!= (PlaneEquation const & lhs, PlaneEquation const & rhs)
Checks if this plane is different from another one.
operator!=() [12/25]
template<typename T > bool castor::operator!= (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator!=() [13/25]
template<typename FlagType , typename Type > bool castor::operator!= (FlagCombination< FlagType, Type > const & p_lhs, FlagCombination< FlagType, Type > const & p_rhs) inline noexcept
Difference operator.
Parameters
[in] p_lhs,p_rhs The operands.
operator!=() [14/25]
template<typename FlagType , typename Type > bool castor::operator!= (FlagCombination< FlagType, Type > const & p_lhs, FlagType const & p_rhs) inline noexcept
Difference operator.
Parameters
[in] p_lhs,p_rhs The operands.
operator!=() [15/25]
template<typename T > bool castor::operator!= (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator!=() [16/25]
template<typename Type > bool castor::operator!= (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
Difference operator.
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
true if p_lhs is different from p_rhs
operator!=() [17/25]
template<typename T , uint32_t Count> bool castor::operator!= (SquareMatrix< T, Count > const & p_mtxA, SquareMatrix< T, Count > const & p_mtxB)
Difference operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to compare
Returns
true if matrices have different dimensions or at least one different value
operator!=() [18/25]
CU_API bool castor::operator!= (HdrColourComponent const & p_lhs, HdrColourComponent const & p_rhs)
Inequality operator.
Parameters
[in] p_lhs,p_rhs The components to compare
operator!=() [19/25]
template<typename T , uint32_t Count, typename U , uint32_t _Count> bool castor::operator!= (Coords< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Difference operator.
Parameters
[in] lhs,rhs The points to compare
Returns
true if points have different dimensions or at least one different value
operator!=() [20/25]
template<typename T , uint32_t Columns, uint32_t Rows> bool castor::operator!= (Matrix< T, Columns, Rows > const & p_mtxA, Matrix< T, Columns, Rows > const & p_mtxB)
Difference operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to compare
Returns
true if matrices have different dimensions or at least one different value
operator!=() [21/25]
CU_API bool castor::operator!= (ColourComponent const & p_lhs, ColourComponent const & p_rhs)
Inequality operator.
Parameters
[in] p_lhs,p_rhs The components to compare
operator!=() [22/25]
template<typename T , uint32_t Count, typename U , uint32_t _Count> bool castor::operator!= (Point< T, Count > const & lhs, Point< U, _Count > const & rhs)
Difference operator.
Parameters
[in] lhs,rhs The points to compare
Returns
true if points have different dimensions or at least one different value
operator!=() [23/25]
template<typename T , uint32_t Count, typename U , uint32_t _Count> bool castor::operator!= (Point< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Difference operator.
Parameters
[in] lhs,rhs The points to compare
Returns
true if points have different dimensions or at least one different value
operator!=() [24/25]
template<typename T , uint32_t Count, typename U , uint32_t _Count> bool castor::operator!= (Coords< T, Count > const & lhs, Point< U, _Count > const & rhs)
Difference operator.
Parameters
[in] lhs,rhs The points to compare
Returns
true if points have different dimensions or at least one different value
operator!=() [25/25]
template<typename ComponentType > bool castor::operator!= (ColourT< ComponentType > const & p_lhs, ColourT< ComponentType > const & p_rhs) inline
Inequality operator.
Parameters
[in] p_lhs,p_rhs The colours to compare
operator*() [1/40]
CU_API Point3r castor::operator* (Matrix4x4r const & p_mtx, Point3r const & p_pt)
Referenced by castor::Coords< uint32_t, 2 >::end(), castor::Point< real, Dimension >::end(), castor::AngleT< Type >::fromGrads(), castor::Pixel< PF >::getSize(), and operator*().
operator*() [2/40]
CU_API Point3r castor::operator* (Point3r const & p_pt, Matrix4x4r const & p_mtx)
operator*() [3/40]
CU_API Point4r castor::operator* (Matrix4x4r const & p_mtx, Point4r const & p_pt)
operator*() [4/40]
CU_API Point4r castor::operator* (Point4r const & p_pt, Matrix4x4r const & p_mtx)
operator*() [5/40]
template<typename T > T castor::operator* (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator*() [6/40]
template<typename T > T castor::operator* (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator*() [7/40]
template<typename T > T castor::operator* (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator*() [8/40]
template<PixelFormat FT, PixelFormat FU> Pixel< FT > castor::operator* (Pixel< FT > const & p_lhs, Pixel< FU > const & p_rhs)
operator*() [9/40]
template<PixelFormat FT, typename U > Pixel< FT > castor::operator* (Pixel< FT > const & p_lhs, U const & p_rhs)
operator*() [10/40]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator* (SquareMatrix< T, Count > const & p_mtxA, SquareMatrix< U, Count > const & p_mtxB)
Multiplication operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to multiply
Returns
The multiplication result
operator*() [11/40]
template<typename T , uint32_t Count, typename U , size_t Columns> SquareMatrix< T, Count > castor::operator* (SquareMatrix< T, Count > const & p_mtxA, Matrix< U, Columns, Count > const & p_mtxB)
Multiplication operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to multiply
Returns
The multiplication result
operator*() [12/40]
template<typename Type > AngleT< Type > castor::operator* (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
Multiplication operator.
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
Result of multiplication
operator*() [13/40]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator* (SquareMatrix< T, Count > const & p_mtxA, U const * p_mtxB)
Multiplication operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to multiply
Returns
The multiplication result
operator*() [14/40]
template<typename Type > AngleT< Type > castor::operator* (AngleT< Type > const & p_lhs, double p_rhs) inline noexcept
Multiplication operator.
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
Result of multiplication
operator*() [15/40]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator* (SquareMatrix< T, Count > const & p_mtxA, T const & p_value)
Multiplication operator.
Parameters
[in] p_mtxA The matrix to multiply
[in] p_value The value
Returns
The multiplication result
operator*() [16/40]
template<typename T , uint32_t Count, typename U , size_t Rows> Matrix< T, Count, Rows > castor::operator* (Matrix< U, Count, Rows > const & p_mtxA, SquareMatrix< T, Count > const & p_mtxB)
Multiplication operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to multiply
Returns
The multiplication result
operator*() [17/40]
template<typename T , uint32_t Count> SquareMatrix< T, Count > castor::operator* (T const & p_value, SquareMatrix< T, Count > const & p_matrix)
Multiplication operator.
Parameters
[in] p_matrix The matrix to multiply
[in] p_value The value
Returns
The multiplication result
operator*() [18/40]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator* (Coords< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Multiplication operator.
Parameters
[in] lhs,rhs The points to multiply
Returns
The multiplication result
operator*() [19/40]
template<typename T > QuaternionT< T > castor::operator* (QuaternionT< T > const & p_lhs, QuaternionT< T > const & p_rhs) inline
Multiplication operator.
Parameters
[in] p_lhs The first Quaternion object to multiply
[in] p_rhs The second Quaternion object to multiply
Returns
The multiplication result
operator*() [20/40]
template<typename T > float castor::operator* (HdrColourComponent const & p_lhs, T const & p_rhs)
Multiplication assignment operator.
Parameters
[in] p_lhs,p_rhs The components to multiply
Returns
Result of p_lhs * p_rhs
References castor::HdrColourComponent::convertTo(), CU_API, operator*(), operator+(), operator-(), and operator/().
operator*() [21/40]
template<typename T , uint32_t Columns, uint32_t Rows, typename U , uint32_t _Columns> Matrix< T, _Columns, Rows > castor::operator* (Matrix< T, Columns, Rows > const & p_mtxA, Matrix< U, _Columns, Columns > const & p_mtxB)
Multiplication operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to multiply
Returns
The multiplication result
operator*() [22/40]
template<typename T > QuaternionT< T > castor::operator* (QuaternionT< T > const & p_lhs, double p_rhs) inline
Multiplication operator.
Parameters
[in] p_lhs The Quaternion object to multiply
[in] p_rhs The scalar to multiply
Returns
The multiplication result
operator*() [23/40]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Point< T, Rows > castor::operator* (Matrix< T, Columns, Rows > const & p_mtxA, Point< U, Columns > const & p_vector)
Multiplication operator.
Parameters
[in] p_mtxA The matrix to multiply
[in] p_vector The vector
Returns
The multiplication result
operator*() [24/40]
template<typename T > QuaternionT< T > castor::operator* (QuaternionT< T > const & p_lhs, float p_rhs) inline
Multiplication operator.
Parameters
[in] p_lhs The Quaternion object to multiply
[in] p_rhs The scalar to multiply
Returns
The multiplication result
operator*() [25/40]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Point< T, Columns > castor::operator* (Point< T, Rows > const & p_vector, Matrix< U, Columns, Rows > const & p_mtxA)
Multiplication operator.
Parameters
[in] p_vector The vector
[in] p_mtxA The matrix to multiply
Returns
The multiplication result
operator*() [26/40]
template<typename T > QuaternionT< T > castor::operator* (double p_lhs, QuaternionT< T > const & p_rhs) inline
Multiplication operator.
Parameters
[in] p_lhs The scalar to multiply
[in] p_rhs The Quaternion object to multiply
Returns
The multiplication result
operator*() [27/40]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator* (Coords< T, Count > const & p_pt, U const * p_coords)
Multiplication operator.
Parameters
[in] p_pt The point
[in] p_coords The values to multiply
Returns
The multiplication result
operator*() [28/40]
CU_API float castor::operator* (HdrColourComponent const & p_lhs, HdrColourComponent const & p_rhs)
Multiplication operator.
Parameters
[in] p_lhs,p_rhs The components to multiply
Returns
Result of p_lhs * p_rhs
operator*() [29/40]
template<typename T > float castor::operator* (ColourComponent const & p_lhs, T && p_rhs)
Multiplication assignment operator.
Parameters
[in] p_lhs,p_rhs The components to multiply
Returns
Result of p_lhs * p_rhs
References castor::ColourComponent::convertTo(), CU_API, operator*(), operator+(), operator-(), and operator/().
operator*() [30/40]
template<typename T > QuaternionT< T > castor::operator* (float p_lhs, QuaternionT< T > const & p_rhs) inline
Multiplication operator.
Parameters
[in] p_lhs The scalar to multiply
[in] p_rhs The Quaternion object to multiply
Returns
The multiplication result
operator*() [31/40]
template<typename T , uint32_t Count> Point< T, Count > castor::operator* (Coords< T, Count > const & p_pt, T const & p_coord)
Multiplication operator.
Parameters
[in] p_pt The point to multiply
[in] p_coord The value
Returns
The multiplication result
operator*() [32/40]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator* (Point< T, Count > const & lhs, Point< U, _Count > const & rhs)
Multiplication operator.
Parameters
[in] lhs,rhs The points to multiply
Returns
The multiplication result
operator*() [33/40]
CU_API float castor::operator* (ColourComponent const & p_lhs, ColourComponent const & p_rhs)
Multiplication operator.
Parameters
[in] p_lhs,p_rhs The components to multiply
Returns
Result of p_lhs * p_rhs
operator*() [34/40]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator* (Matrix< T, Columns, Rows > const & p_mtxA, T const & p_value)
Multiplication operator.
Parameters
[in] p_mtxA The matrix to multiply
[in] p_value The value
Returns
The multiplication result
operator*() [35/40]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator* (Point< T, Count > const & p_pt, U const * p_coords)
Multiplication operator.
Parameters
[in] p_pt The point
[in] p_coords The values to multiply
Returns
The multiplication result
operator*() [36/40]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator* (T const & p_value, Matrix< U, Columns, Rows > const & p_matrix)
Multiplication operator.
Parameters
[in] p_matrix The matrix to multiply
[in] p_value The value
Returns
The multiplication result
operator*() [37/40]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator* (Point< T, Count > const & p_pt, U const & p_coord)
Multiplication operator.
Parameters
[in] p_pt The point to multiply
[in] p_coord The value
Returns
The multiplication result
operator*() [38/40]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator* (Point< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Multiplication operator.
Parameters
[in] lhs,rhs The points to multiply
Returns
The multiplication result
operator*() [39/40]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator* (Coords< T, Count > const & lhs, Point< U, _Count > const & rhs)
Multiplication operator.
Parameters
[in] lhs,rhs The points to multiply
Returns
The multiplication result
operator*() [40/40]
template<typename ComponentType , typename T > ColourT< ComponentType > castor::operator* (ColourT< ComponentType > const & p_lhs, T p_rhs)
Multiplication operator.
Parameters
[in] p_lhs,p_rhs The values to multiply
Returns
Result of p_lhs * p_rhs
operator+() [1/29]
template<PixelFormat PF> PixelIterator< PF > castor::operator+ (PixelIterator< PF > p_it, size_t p_offset) inline
operator+() [2/29]
template<PixelFormat PF> ConstPixelIterator< PF > castor::operator+ (ConstPixelIterator< PF > p_it, size_t p_offset) inline
operator+() [3/29]
template<typename T > T castor::operator+ (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator+() [4/29]
template<typename T > T castor::operator+ (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator+() [5/29]
template<typename T > T castor::operator+ (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator+() [6/29]
template<PixelFormat FT, PixelFormat FU> Pixel< FT > castor::operator+ (Pixel< FT > const & p_lhs, Pixel< FU > const & p_rhs)
operator+() [7/29]
template<PixelFormat FT, typename U > Pixel< FT > castor::operator+ (Pixel< FT > const & p_lhs, U const & p_rhs)
operator+() [8/29]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator+ (SquareMatrix< T, Count > const & p_mtxA, SquareMatrix< U, Count > const & p_mtxB)
addition operator
Parameters
[in] p_mtxA,p_mtxB The matrices to add
Returns
The addition result
operator+() [9/29]
template<typename Type > AngleT< Type > castor::operator+ (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
addition operator
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
Result of addition
operator+() [10/29]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator+ (SquareMatrix< T, Count > const & p_mtxA, U const * p_mtxB)
addition operator
Parameters
[in] p_mtxA,p_mtxB The matrices to add
Returns
The addition result
operator+() [11/29]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator+ (SquareMatrix< T, Count > const & p_mtxA, T const & p_value)
addition operator
Parameters
[in] p_mtxA The matrix
[in] p_value The value to add
Returns
The addition result
operator+() [12/29]
template<typename T > float castor::operator+ (HdrColourComponent const & p_lhs, T const & p_rhs)
addition assignment operator
Parameters
[in] p_lhs,p_rhs The components to add
Returns
Result of p_lhs + p_rhs
References castor::HdrColourComponent::convertTo().
operator+() [13/29]
template<typename T , uint32_t Count> SquareMatrix< T, Count > castor::operator+ (T const & p_value, SquareMatrix< T, Count > const & p_matrix)
addition operator
Parameters
[in] p_matrix The matrix
[in] p_value The value to add
Returns
The addition result
operator+() [14/29]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator+ (Coords< T, Count > const & lhs, Coords< U, _Count > const & rhs)
addition operator
Parameters
[in] lhs,rhs The points to add
Returns
The addition result
operator+() [15/29]
template<typename T > QuaternionT< T > castor::operator+ (QuaternionT< T > const & p_lhs, QuaternionT< T > const & p_rhs) inline
addition operator
Parameters
[in] p_lhs The first Quaternion object to add
[in] p_rhs The second Quaternion object to add
Returns
The addition result
operator+() [16/29]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator+ (Matrix< T, Columns, Rows > const & p_mtxA, Matrix< U, Columns, Rows > const & p_mtxB)
addition operator
Parameters
[in] p_mtxA,p_mtxB The matrices to add
Returns
The addition result
operator+() [17/29]
template<typename T > float castor::operator+ (ColourComponent const & p_lhs, T && p_rhs)
addition assignment operator
Parameters
[in] p_lhs,p_rhs The components to add
Returns
Result of p_lhs + p_rhs
References castor::ColourComponent::convertTo().
operator+() [18/29]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator+ (Coords< T, Count > const & p_pt, U const * p_coords)
addition operator
Parameters
[in] p_pt The point
[in] p_coords The values to add
Returns
The addition result
operator+() [19/29]
CU_API float castor::operator+ (HdrColourComponent const & p_lhs, HdrColourComponent const & p_rhs)
addition operator
Parameters
[in] p_lhs,p_rhs The components to add
Returns
Result of p_lhs + p_rhs
operator+() [20/29]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator+ (Matrix< T, Columns, Rows > const & p_mtxA, U const * p_mtxB)
addition operator
Parameters
[in] p_mtxA,p_mtxB The matrices to add
Returns
The addition result
operator+() [21/29]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator+ (Point< T, Count > const & lhs, Point< U, _Count > const & rhs)
addition operator
Parameters
[in] lhs,rhs The points to add
Returns
The addition result
operator+() [22/29]
CU_API float castor::operator+ (ColourComponent const & p_lhs, ColourComponent const & p_rhs)
addition operator
Parameters
[in] p_lhs,p_rhs The components to add
Returns
Result of p_lhs + p_rhs
operator+() [23/29]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator+ (Matrix< T, Columns, Rows > const & p_mtxA, T const & p_value)
addition operator
Parameters
[in] p_mtxA The matrix
[in] p_value The value to add
Returns
The addition result
operator+() [24/29]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator+ (Point< T, Count > const & p_pt, U const * p_coords)
addition operator
Parameters
[in] p_pt The point
[in] p_coords The values to add
Returns
The addition result
operator+() [25/29]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator+ (T const & p_value, Matrix< U, Columns, Rows > const & p_matrix)
addition operator
Parameters
[in] p_matrix The matrix
[in] p_value The value to add
Returns
The addition result
operator+() [26/29]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator+ (Point< T, Count > const & lhs, Coords< U, _Count > const & rhs)
addition operator
Parameters
[in] lhs,rhs The points to add
Returns
The addition result
operator+() [27/29]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator+ (Coords< T, Count > const & lhs, Point< U, _Count > const & rhs)
addition operator
Parameters
[in] lhs,rhs The points to add
Returns
The addition result
operator+() [28/29]
template<typename ComponentType > ColourT< ComponentType > castor::operator+ (ColourT< ComponentType > const & p_lhs, ColourT< ComponentType > const & p_rhs) inline
addition operator
Parameters
[in] p_lhs,p_rhs The colours to add
Returns
Result of p_lhs + p_rhs
Referenced by castor::Coords< uint32_t, 2 >::end(), castor::Point< real, Dimension >::end(), castor::AngleT< Type >::fromGrads(), castor::Pixel< PF >::getSize(), operator*(), and castor::ColourT< ComponentType >::operator/=().
operator+() [29/29]
template<typename ComponentType , typename T > ColourT< ComponentType > castor::operator+ (ColourT< ComponentType > const & p_lhs, T p_rhs)
addition operator
Parameters
[in] p_lhs,p_rhs The values to add
Returns
Result of p_lhs + p_rhs
operator-() [1/33]
template<PixelFormat PF> PixelIterator< PF > castor::operator- (PixelIterator< PF > p_it, size_t p_offset) inline
operator-() [2/33]
template<PixelFormat PF> ConstPixelIterator< PF > castor::operator- (ConstPixelIterator< PF > p_it, size_t p_offset) inline
operator-() [3/33]
template<typename T > T castor::operator- (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator-() [4/33]
template<typename T > T castor::operator- (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator-() [5/33]
template<typename T > T castor::operator- (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator-() [6/33]
template<PixelFormat FT, PixelFormat FU> Pixel< FT > castor::operator- (Pixel< FT > const & p_lhs, Pixel< FU > const & p_rhs)
operator-() [7/33]
template<PixelFormat FT, typename U > Pixel< FT > castor::operator- (Pixel< FT > const & p_lhs, U const & p_rhs)
operator-() [8/33]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator- (SquareMatrix< T, Count > const & p_mtxA, SquareMatrix< U, Count > const & p_mtxB)
Substraction operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to subtract
Returns
The substraction result
operator-() [9/33]
template<typename Type > AngleT< Type > castor::operator- (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
Substraction operator.
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
Result of substraction
operator-() [10/33]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator- (SquareMatrix< T, Count > const & p_mtxA, U const * p_mtxB)
Substraction operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to subtract
Returns
The substraction result
operator-() [11/33]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator- (SquareMatrix< T, Count > const & p_mtxA, T const & p_value)
Substraction operator.
Parameters
[in] p_mtxA The matrix
[in] p_value The value to subtract
Returns
The substraction result
operator-() [12/33]
template<typename T > float castor::operator- (HdrColourComponent const & p_lhs, T const & p_rhs)
Substraction assignment operator.
Parameters
[in] p_lhs,p_rhs The components to subtract
Returns
Result of p_lhs - p_rhs
References castor::HdrColourComponent::convertTo().
operator-() [13/33]
template<typename T , uint32_t Count> SquareMatrix< T, Count > castor::operator- (T const & p_value, SquareMatrix< T, Count > const & p_matrix)
Substraction operator.
Parameters
[in] p_matrix The matrix
[in] p_value The value to subtract
Returns
The substraction result
operator-() [14/33]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator- (Coords< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Substraction operator.
Parameters
[in] lhs,rhs The points to subtract
Returns
The substraction result
operator-() [15/33]
template<typename T > QuaternionT< T > castor::operator- (QuaternionT< T > const & p_lhs, QuaternionT< T > const & p_rhs) inline
Substraction operator.
Parameters
[in] p_lhs The first Quaternion object to subtract
[in] p_rhs The second Quaternion object to subtract
Returns
The substraction result
operator-() [16/33]
template<typename T , uint32_t Count> SquareMatrix< T, Count > castor::operator- (SquareMatrix< T, Count > const & p_matrix)
Negation operator.
Parameters
[in] p_matrix The matrix
Returns
The negation result
operator-() [17/33]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator- (Matrix< T, Columns, Rows > const & p_mtxA, Matrix< U, Columns, Rows > const & p_mtxB)
Substraction operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to subtract
Returns
The substraction result
operator-() [18/33]
template<typename T > float castor::operator- (ColourComponent const & p_lhs, T && p_rhs)
Substraction assignment operator.
Parameters
[in] p_lhs,p_rhs The components to subtract
Returns
Result of p_lhs - p_rhs
References castor::ColourComponent::convertTo().
operator-() [19/33]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator- (Coords< T, Count > const & p_pt, U const * p_coords)
Substraction operator.
Parameters
[in] p_pt The point
[in] p_coords The values to subtract
Returns
The substraction result
operator-() [20/33]
CU_API float castor::operator- (HdrColourComponent const & p_lhs, HdrColourComponent const & p_rhs)
Subtraction operator.
Parameters
[in] p_lhs,p_rhs The components to subtract
Returns
Result of p_lhs - p_rhs
operator-() [21/33]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator- (Matrix< T, Columns, Rows > const & p_mtxA, U const * p_mtxB)
Substraction operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to subtract
Returns
The substraction result
operator-() [22/33]
template<typename T > QuaternionT< T > castor::operator- (QuaternionT< T > const & p_quat) inline
Negation operator.
Parameters
[in] p_quat The Quaternion object to negate
Returns
The negation result
operator-() [23/33]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator- (Point< T, Count > const & lhs, Point< U, _Count > const & rhs)
Substraction operator.
Parameters
[in] lhs,rhs The points to subtract
Returns
The substraction result
operator-() [24/33]
CU_API float castor::operator- (ColourComponent const & p_lhs, ColourComponent const & p_rhs)
Subtraction operator.
Parameters
[in] p_lhs,p_rhs The components to subtract
Returns
Result of p_lhs - p_rhs
operator-() [25/33]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator- (Matrix< T, Columns, Rows > const & p_mtxA, T const & p_value)
Substraction operator.
Parameters
[in] p_mtxA The matrix
[in] p_value The value to subtract
Returns
The substraction result
operator-() [26/33]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator- (Point< T, Count > const & p_pt, U const * p_coords)
Substraction operator.
Parameters
[in] p_pt The point
[in] p_coords The values to subtract
Returns
The substraction result
operator-() [27/33]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator- (T const & p_value, Matrix< U, Columns, Rows > const & p_matrix)
Substraction operator.
Parameters
[in] p_matrix The matrix
[in] p_value The value to subtract
Returns
The substraction result
operator-() [28/33]
template<typename T , uint32_t Columns, uint32_t Rows> Matrix< T, Columns, Rows > castor::operator- (Matrix< T, Columns, Rows > const & p_matrix)
operator-() [29/33]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator- (Point< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Substraction operator.
Parameters
[in] lhs,rhs The points to subtract
Returns
The substraction result
operator-() [30/33]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator- (Coords< T, Count > const & lhs, Point< U, _Count > const & rhs)
Substraction operator.
Parameters
[in] lhs,rhs The points to subtract
Returns
The substraction result
operator-() [31/33]
template<typename T , uint32_t Count> Point< T, Count > castor::operator- (Point< T, Count > const & p_pt)
Negation operator.
Parameters
[in] p_pt The point to negate
operator-() [32/33]
template<typename ComponentType > ColourT< ComponentType > castor::operator- (ColourT< ComponentType > const & p_lhs, ColourT< ComponentType > const & p_rhs) inline
Substraction operator.
Parameters
[in] p_lhs,p_rhs The colours to subtract
Returns
Result of p_lhs - p_rhs
Referenced by castor::Coords< uint32_t, 2 >::end(), castor::Point< real, Dimension >::end(), castor::Pixel< PF >::getSize(), operator*(), and castor::ColourT< ComponentType >::operator/=().
operator-() [33/33]
template<typename ComponentType , typename T > ColourT< ComponentType > castor::operator- (ColourT< ComponentType > const & p_lhs, T p_rhs)
Subtraction operator.
Parameters
[in] p_lhs,p_rhs The values to subtract
Returns
Result of p_lhs - p_rhs
operator/() [1/29]
CU_API Path castor::operator/ (Path const & p_lhs, Path const & p_rhs)
Appends 2 paths. adds the separator if needed.
Parameters
[in] p_lhs The first path to add
[in] p_rhs The second path to add
Referenced by castor::Coords< uint32_t, 2 >::end(), castor::Point< real, Dimension >::end(), castor::AngleT< Type >::fromGrads(), castor::Pixel< PF >::getSize(), and operator*().
operator/() [2/29]
CU_API Path castor::operator/ (Path const & p_lhs, String const & p_rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] p_lhs The first path to add
[in] p_rhs The path to add
operator/() [3/29]
CU_API Path castor::operator/ (Path const & p_lhs, char const * p_rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] p_lhs The first path to add
[in] p_rhs The path to add
operator/() [4/29]
CU_API Path castor::operator/ (Path const & p_lhs, wchar_t const * p_rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] p_lhs The first path to add
[in] p_rhs The path to add
operator/() [5/29]
CU_API Path castor::operator/ (String const & p_lhs, Path const & p_rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] p_lhs The path to add
[in] p_rhs The first path to add
operator/() [6/29]
CU_API Path castor::operator/ (char const * p_lhs, Path const & p_rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] p_lhs The path to add
[in] p_rhs The first path to add
operator/() [7/29]
CU_API Path castor::operator/ (wchar_t const * p_lhs, Path const & p_rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] p_lhs The path to add
[in] p_rhs The first path to add
operator/() [8/29]
template<typename T > T castor::operator/ (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator/() [9/29]
template<typename T > T castor::operator/ (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator/() [10/29]
template<typename T > T castor::operator/ (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator/() [11/29]
template<PixelFormat FT, PixelFormat FU> Pixel< FT > castor::operator/ (Pixel< FT > const & p_lhs, Pixel< FU > const & p_rhs)
operator/() [12/29]
template<PixelFormat FT, typename U > Pixel< FT > castor::operator/ (Pixel< FT > const & p_lhs, U const & p_rhs)
operator/() [13/29]
template<typename Type > AngleT< Type > castor::operator/ (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
Division operator.
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
Result of division
operator/() [14/29]
template<typename Type > AngleT< Type > castor::operator/ (AngleT< Type > const & p_lhs, double p_rhs) inline noexcept
Division operator.
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
Result of division
operator/() [15/29]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator/ (SquareMatrix< T, Count > const & p_mtxA, T const & p_value)
Division operator.
Parameters
[in] p_mtxA The matrix to divide
[in] p_value The value
Returns
The division result
operator/() [16/29]
template<typename T > float castor::operator/ (HdrColourComponent const & p_lhs, T const & p_rhs)
Division assignment operator.
Parameters
[in] p_lhs,p_rhs The components to divide
Returns
Result of p_lhs / p_rhs
References castor::HdrColourComponent::convertTo().
operator/() [17/29]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator/ (Coords< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Division operator.
Parameters
[in] lhs,rhs The points to divide
Returns
The division result
operator/() [18/29]
template<typename T > float castor::operator/ (ColourComponent const & p_lhs, T && p_rhs)
Division assignment operator.
Parameters
[in] p_lhs,p_rhs The components to divide
Returns
Result of p_lhs / p_rhs
References castor::ColourComponent::convertTo().
operator/() [19/29]
CU_API float castor::operator/ (HdrColourComponent const & p_lhs, HdrColourComponent const & p_rhs)
Division operator.
Parameters
[in] p_lhs,p_rhs The components to divide
Returns
Result of p_lhs / p_rhs
operator/() [20/29]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator/ (Coords< T, Count > const & p_pt, U const * p_coords)
Division operator.
Parameters
[in] p_pt The point to divide
[in] p_coords The values
Returns
The division result
operator/() [21/29]
template<typename T , uint32_t Count> Point< T, Count > castor::operator/ (Coords< T, Count > const & p_pt, T const & p_coord)
Division operator.
Parameters
[in] p_pt The point to divide
[in] p_coord The value
Returns
The division result
operator/() [22/29]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator/ (Point< T, Count > const & lhs, Point< U, _Count > const & rhs)
Division operator.
Parameters
[in] lhs,rhs The points to divide
Returns
The division result
operator/() [23/29]
CU_API float castor::operator/ (ColourComponent const & p_lhs, ColourComponent const & p_rhs)
Division operator.
Parameters
[in] p_lhs,p_rhs The components to divide
Returns
Result of p_lhs / p_rhs
operator/() [24/29]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator/ (Matrix< T, Columns, Rows > const & p_mtxA, T const & p_value)
Division operator.
Parameters
[in] p_mtxA The matrix to divide
[in] p_value The value
Returns
The division result
operator/() [25/29]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator/ (Point< T, Count > const & p_pt, U const * p_coords)
Division operator.
Parameters
[in] p_pt The point to divide
[in] p_coords The values
Returns
The division result
operator/() [26/29]
template<typename T , uint32_t Count, typename U > Point< T, Count > castor::operator/ (Point< T, Count > const & p_pt, U const & p_coord)
Division operator.
Parameters
[in] p_pt The point to divide
[in] p_coord The value
Returns
The division result
operator/() [27/29]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator/ (Point< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Division operator.
Parameters
[in] lhs,rhs The points to divide
Returns
The division result
operator/() [28/29]
template<typename T , uint32_t Count, typename U , uint32_t _Count> Point< T, Count > castor::operator/ (Coords< T, Count > const & lhs, Point< U, _Count > const & rhs)
Division operator.
Parameters
[in] lhs,rhs The points to divide
Returns
The division result
operator/() [29/29]
template<typename ComponentType , typename T > ColourT< ComponentType > castor::operator/ (ColourT< ComponentType > const & p_lhs, T p_rhs)
Division operator.
Parameters
[in] p_lhs,p_rhs The values to divide
Returns
Result of p_lhs / p_rhs
References toABGRByte(), toABGRFloat(), toABGRPacked(), toARGBByte(), toARGBFloat(), toARGBPacked(), toBGRAByte(), toBGRAFloat(), toBGRAPacked(), toBGRByte(), toBGRFloat(), toBGRPacked(), toRGBAByte(), toRGBAFloat(), toRGBAPacked(), toRGBByte(), toRGBFloat(), and toRGBPacked().
operator<() [1/5]
bool castor::operator< (Glyph const & p_lhs, Glyph const & p_rhs) inline
Less than comparison operator.
Parameters
[in] p_lhs,p_rhs The values to compare.
References castor::Glyph::getCharacter().
operator<() [2/5]
template<typename T > bool castor::operator< (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator<() [3/5]
template<typename T > bool castor::operator< (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator<() [4/5]
template<typename T > bool castor::operator< (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
References castor::RangedValue< T >::value().
operator<() [5/5]
template<typename Type > bool castor::operator< (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
"Less than" operator
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
true if p_lhs is less than p_rhs.
operator<<() [1/9]
template<typename T > TextFile& castor::operator<< (TextFile & p_file, T const & p_toWrite)
open mode dependant write function
Parameters
[in] p_file The file
[in] p_toWrite The data to write in the file
Returns
A reference to this file
operator<<() [2/9]
template<typename CharType , typename PrefixType > std::basic_ostream< CharType >& castor::operator<< (std::basic_ostream< CharType > & stream, format::BasePrefixer< CharType, PrefixType > const & Prefix) inline
Stream operator.
Remarks
Initializes the stream in order to Prefix it.
Parameters
[in] stream The stream.
[in] Prefix The Prefix.
operator<<() [3/9]
template<typename CharType > std::basic_ostream< CharType >& castor::operator<< (std::basic_ostream< CharType > & stream, format::Indent const & ind) inline
Stream operator.
Remarks
Initializes the stream in order to indent it
Parameters
[in] stream The stream
[in] ind The indent
References castor::format::BasicIndentBuffer< char_type, fill_char, traits >::indent(), castor::format::installIndentBuffer(), and castor::format::setIndent().
operator<<() [4/9]
template<typename T > BinaryFile& castor::operator<< (BinaryFile & p_file, T const & p_toWrite)
open mode dependant write function
Parameters
[in] p_file The file
[in] p_toWrite The data to write in the file
Returns
A reference to this file
Referenced by castor::CpuInformations::PREFETCHWT1().
operator<<() [5/9]
CU_API std::ostream& castor::operator<< (std::ostream & p_stream, CpuInformations const & p_object)
Output stream operator.
Parameters
[in,out] p_stream The stream.
[in] p_object The object to put in the stream.
Returns
The stream.
operator<<() [6/9]
template<typename CharT , typename T , uint32_t Count> std::basic_ostream< CharT >& castor::operator<< (std::basic_ostream< CharT > & p_streamOut, castor::SquareMatrix< T, Count > const & p_matrix)
Stream operator.
Parameters
[in,out] p_streamOut The stream receiving matrix's data
[in] p_matrix The input matrix
Returns
A reference to the stream
operator<<() [7/9]
template<typename CharT , typename T > std::basic_ostream< CharT >& castor::operator<< (std::basic_ostream< CharT > & p_stream, QuaternionT< T > const & p_quat) inline
Stream operator.
Parameters
[in,out] p_stream The stream.
[in] p_quat The Quaternion object to put in stream.
Returns
The stream.
operator<<() [8/9]
template<typename T , uint32_t Columns, uint32_t Rows> castor::String& castor::operator<< (castor::String & p_streamOut, castor::Matrix< T, Columns, Rows > const & p_matrix)
Stream operator.
Parameters
[in,out] p_streamOut The stream receiving matrix's data
[in] p_matrix The input matrix
Returns
A reference to the stream
operator<<() [9/9]
template<typename CharT , typename T , uint32_t Columns, uint32_t Rows> std::basic_ostream< CharT >& castor::operator<< (std::basic_ostream< CharT > & p_streamOut, castor::Matrix< T, Columns, Rows > const & p_matrix)
Stream operator.
Parameters
[in,out] p_streamOut The stream receiving matrix's data
[in] p_matrix The input matrix
Returns
A reference to the stream
operator<=() [1/5]
bool castor::operator<= (Glyph const & p_lhs, Glyph const & p_rhs) inline
Less than or equal to comparison operator.
Parameters
[in] p_lhs,p_rhs The values to compare.
References castor::Glyph::getCharacter().
operator<=() [2/5]
template<typename T > bool castor::operator<= (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator<=() [3/5]
template<typename T > bool castor::operator<= (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator<=() [4/5]
template<typename T > bool castor::operator<= (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator<=() [5/5]
template<typename Type > bool castor::operator<= (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
"Less than or equal to" operator
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
true if p_lhs is less than or equal to p_rhs.
operator==() [1/26]
template<typename T > bool castor::operator== (GroupChangeTracked< T > const & lhs, T const & rhs)
References castor::GroupChangeTracked< T >::value().
operator==() [2/26]
template<typename T > bool castor::operator== (T const & lhs, GroupChangeTracked< T > const & rhs)
References castor::GroupChangeTracked< T >::value().
operator==() [3/26]
template<typename T > bool castor::operator== (ChangeTracked< T > const & lhs, T const & rhs)
References castor::ChangeTracked< T >::value().
Referenced by castor::Coords< uint32_t, 2 >::end(), castor::Point< real, Dimension >::end(), castor::Pixel< PF >::getSize(), operator!=(), castor::ColourT< ComponentType >::operator/=(), castor::HdrColourComponent::value(), and castor::ColourComponent::value().
operator==() [4/26]
template<typename T > bool castor::operator== (GroupChangeTracked< T > const & lhs, GroupChangeTracked< T > const & rhs)
References castor::GroupChangeTracked< T >::value().
operator==() [5/26]
template<typename T > bool castor::operator== (T const & lhs, ChangeTracked< T > const & rhs)
References castor::ChangeTracked< T >::value().
operator==() [6/26]
template<typename T > bool castor::operator== (ChangeTracked< T > const & lhs, ChangeTracked< T > const & rhs)
References castor::ChangeTracked< T >::value().
operator==() [7/26]
bool castor::operator== (Glyph const & p_lhs, Glyph const & p_rhs) inline
Equality comparison operator.
Parameters
[in] p_lhs,p_rhs The values to compare.
References castor::Glyph::getCharacter().
operator==() [8/26]
CU_API bool castor::operator== (Position const & p_a, Position const & p_b)
Equality operator.
Parameters
[in] p_a,p_b The positions to compare
Returns
true if positions have same coordinates
operator==() [9/26]
CU_API bool castor::operator== (Size const & p_a, Size const & p_b)
Equality operator.
Parameters
[in] p_a,p_b The sizes to compare
Returns
true if sizes have same dimensions
operator==() [10/26]
template<typename T > bool castor::operator== (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator==() [11/26]
CU_API bool castor::operator== (PlaneEquation const & lhs, PlaneEquation const & rhs)
Checks if this plane is equal to another one.
Remarks
A plane is equal to another one if it is parallel to it and if normals and d coeff are equal
operator==() [12/26]
template<typename FlagType , typename Type > bool castor::operator== (FlagCombination< FlagType, Type > const & p_lhs, FlagCombination< FlagType, Type > const & p_rhs) inline noexcept
Equality operator.
Parameters
[in] p_lhs,p_rhs The operands.
operator==() [13/26]
template<typename T > bool castor::operator== (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator==() [14/26]
template<typename FlagType , typename Type > bool castor::operator== (FlagCombination< FlagType, Type > const & p_lhs, FlagType const & p_rhs) inline noexcept
Equality operator.
Parameters
[in] p_lhs,p_rhs The operands.
operator==() [15/26]
template<typename T > bool castor::operator== (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator==() [16/26]
template<typename Type > bool castor::operator== (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
Equality operator.
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
true if p_lhs is equal to p_rhs
operator==() [17/26]
template<PixelFormat FT, PixelFormat FU> bool castor::operator== (Pixel< FT > const & p_lhs, Pixel< FU > const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The pixels to compare
Returns
true if points have same dimensions and same values
operator==() [18/26]
template<typename T , uint32_t Count> bool castor::operator== (SquareMatrix< T, Count > const & p_mtxA, SquareMatrix< T, Count > const & p_mtxB)
Equality operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to compare
Returns
true if matrices have same dimensions and same values
operator==() [19/26]
CU_API bool castor::operator== (HdrColourComponent const & p_lhs, HdrColourComponent const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The components to compare
operator==() [20/26]
template<typename T , uint32_t Count, typename U , uint32_t _Count> bool castor::operator== (Coords< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The points to compare
Returns
true if points have same dimensions and same values
operator==() [21/26]
template<typename T , uint32_t Columns, uint32_t Rows> bool castor::operator== (Matrix< T, Columns, Rows > const & p_mtxA, Matrix< T, Columns, Rows > const & p_mtxB)
Equality operator.
Parameters
[in] p_mtxA,p_mtxB The matrices to compare
Returns
true if matrices have same dimensions and same values
operator==() [22/26]
CU_API bool castor::operator== (ColourComponent const & p_lhs, ColourComponent const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The components to compare
operator==() [23/26]
template<typename T , uint32_t Count, typename U , uint32_t _Count> bool castor::operator== (Point< T, Count > const & lhs, Point< U, _Count > const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The points to compare
Returns
true if points have same dimensions and same values
operator==() [24/26]
template<typename T , uint32_t Count, typename U , uint32_t _Count> bool castor::operator== (Point< T, Count > const & lhs, Coords< U, _Count > const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The points to compare
Returns
true if points have same dimensions and same values
operator==() [25/26]
template<typename T , uint32_t Count, typename U , uint32_t _Count> bool castor::operator== (Coords< T, Count > const & lhs, Point< U, _Count > const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The points to compare
Returns
true if points have same dimensions and same values
operator==() [26/26]
template<typename ComponentType > bool castor::operator== (ColourT< ComponentType > const & p_lhs, ColourT< ComponentType > const & p_rhs) inline
Equality operator.
Parameters
[in] p_lhs,p_rhs The colours to compare
operator>() [1/5]
bool castor::operator> (Glyph const & p_lhs, Glyph const & p_rhs) inline
Greater than comparison operator.
Parameters
[in] p_lhs,p_rhs The values to compare.
References castor::Glyph::getCharacter().
operator>() [2/5]
template<typename T > bool castor::operator> (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator>() [3/5]
template<typename T > bool castor::operator> (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator>() [4/5]
template<typename T > bool castor::operator> (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator>() [5/5]
template<typename Type > bool castor::operator> (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
"Greater than" operator
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
true if p_lhs is greater than p_rhs.
operator>=() [1/5]
bool castor::operator>= (Glyph const & p_lhs, Glyph const & p_rhs) inline
Greater than or equal to comparison operator.
Parameters
[in] p_lhs,p_rhs The values to compare.
References castor::Glyph::getCharacter().
Referenced by castor::AngleT< Type >::fromGrads().
operator>=() [2/5]
template<typename T > bool castor::operator>= (RangedValue< T > const & p_lhs, T const & p_rhs) inline noexcept
operator>=() [3/5]
template<typename T > bool castor::operator>= (T const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator>=() [4/5]
template<typename T > bool castor::operator>= (RangedValue< T > const & p_lhs, RangedValue< T > const & p_rhs) inline noexcept
operator>=() [5/5]
template<typename Type > bool castor::operator>= (AngleT< Type > const & p_lhs, AngleT< Type > const & p_rhs) inline noexcept
"Greater than or equal to" operator
Parameters
[in] p_lhs First operand
[in] p_rhs Second operand
Returns
true if p_lhs is greater than or equal to p_rhs.
operator>>() [1/5]
template<typename T > TextFile& castor::operator>> (TextFile & p_file, T & p_toRead)
open mode dependant read function
Parameters
[in] p_file The file
[out] p_toRead The data to read from the file
Returns
A reference to this file
operator>>() [2/5]
template<typename T > BinaryFile& castor::operator>> (BinaryFile & p_file, T & p_toRead)
open mode dependant read function
Parameters
[in] p_file The file
[out] p_toRead The data to read from the file
Returns
A reference to this file
Referenced by castor::Point< real, Dimension >::end().
operator>>() [3/5]
template<typename CharT , typename T , uint32_t Count> std::basic_istream< CharT >& castor::operator>> (std::basic_istream< CharT > & p_streamIn, castor::SquareMatrix< T, Count > & p_matrix)
Stream operator.
Parameters
[in,out] p_streamIn The stream holding matrix's data
[in,out] p_matrix The output matrix
Returns
A reference to the stream
operator>>() [4/5]
template<typename T , uint32_t Columns, uint32_t Rows> castor::String& castor::operator>> (castor::String & p_streamIn, castor::Matrix< T, Columns, Rows > & p_matrix)
Stream operator.
Parameters
[in,out] p_streamIn The stream holding matrix's data
[in,out] p_matrix The output matrix
Returns
A reference to the stream
operator>>() [5/5]
template<typename CharT , typename T , uint32_t Columns, uint32_t Rows> std::basic_istream< CharT >& castor::operator>> (std::basic_istream< CharT > & p_streamIn, castor::Matrix< T, Columns, Rows > & p_matrix)
Stream operator.
Parameters
[in,out] p_streamIn The stream holding matrix's data
[in,out] p_matrix The output matrix
Returns
A reference to the stream
operator|()
template<typename FlagType , typename Type > FlagCombination< FlagType, Type > castor::operator| (FlagCombination< FlagType, Type > const & p_lhs, FlagType const & p_rhs) inline noexcept
Binary OR operator.
Parameters
[in] p_lhs,p_rhs The operands.
Returns
The resulting flags combination.
remFlag() [1/2]
template<typename FlagType , typename Type > FlagCombination< FlagType, Type >& castor::remFlag (FlagCombination< FlagType, Type > & p_value, FlagType const & p_flag) inline noexcept
Removes a flag from the given value.
Parameters
[in,out] p_value The value.
[in] p_flag The flag to remove.
Returns
The value.
remFlag() [2/2]
template<typename FlagType , typename Type > FlagCombination< FlagType, Type > castor::remFlag (FlagCombination< FlagType, Type > const & p_value, FlagType const & p_flag) inline noexcept
Removes a flag from the given value.
Parameters
[in] p_value The value.
[in] p_flag The flag to remove.
Returns
The new value.
reportError()
template<PoolErrorType ErrorType, typename ... Params> static void castor::reportError (char const *const p_name, Params ... p_params) inline static
Reports a pool error.
Parameters
[in] p_name The error text.
[in] p_params The error parameters.
switchEndianness() [1/2]
template<typename T > T& castor::switchEndianness (T & value) inline noexcept
Convert from little or big endian to the other.
Parameters
[in,out] value Value to be converted.
Referenced by bigEndianToSystemEndian(), switchEndianness(), and systemEndianToBigEndian().
switchEndianness() [2/2]
template<typename T > T castor::switchEndianness (T const & value) inline
Convert from little or big endian to the other.
Parameters
[in,out] value Value to be converted.
References switchEndianness().
systemEndianToBigEndian() [1/6]
template<typename T > T& castor::systemEndianToBigEndian (T & value) inline noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [2/6]
template<typename T > T castor::systemEndianToBigEndian (T const & value) inline
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References switchEndianness().
systemEndianToBigEndian() [3/6]
template<typename T , size_t N> std::array< T, N >& castor::systemEndianToBigEndian (std::array< T, N > & value) inline noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [4/6]
template<typename T , size_t N> std::array< T, N > castor::systemEndianToBigEndian (std::array< T, N > const & value) inline
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [5/6]
template<typename T > std::vector< T >& castor::systemEndianToBigEndian (std::vector< T > & value) inline noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [6/6]
template<typename T > std::vector< T > castor::systemEndianToBigEndian (std::vector< T > const & value) inline
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
toABGRByte()
Point4ub castor::toABGRByte (ColourT< ColourComponent > const & p_colour) inline
Stores a colour's components into a point in ABGR format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toABGRFloat()
template<typename ComponentType > Point4f castor::toABGRFloat (ColourT< ComponentType > const & p_colour) inline
Stores a colour's components into a point in ABGR format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toABGRPacked()
uint32_t castor::toABGRPacked (ColourT< ColourComponent > const & p_colour) inline
Packs a colour's components into an uint32_t in the ABGR format (0xAABBGGRR).
Parameters
[in] p_colour The colour.
Returns
The packed colour.
Referenced by operator/().
toARGBByte()
Point4ub castor::toARGBByte (ColourT< ColourComponent > const & p_colour) inline
Stores a colour's components into a point in ARGB format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toARGBFloat()
template<typename ComponentType > Point4f castor::toARGBFloat (ColourT< ComponentType > const & p_colour) inline
Stores a colour's components into a point in ARGB format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toARGBPacked()
uint32_t castor::toARGBPacked (ColourT< ColourComponent > const & p_colour) inline
Packs a colour's components into an uint32_t in the ARGB format (0xAARRGGBB).
Parameters
[in] p_colour The colour.
Returns
The packed colour.
Referenced by operator/().
toBGRAByte()
Point4ub castor::toBGRAByte (ColourT< ColourComponent > const & p_colour) inline
Stores a colour's components into a point in BGRA format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toBGRAFloat()
template<typename ComponentType > Point4f castor::toBGRAFloat (ColourT< ComponentType > const & p_colour) inline
Stores a colour's components into a point in BGRA format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toBGRAPacked()
uint32_t castor::toBGRAPacked (ColourT< ColourComponent > const & p_colour) inline
Packs a colour's components into an uint32_t in the BGRA format (0xBBGGRRAA).
Parameters
[in] p_colour The colour.
Returns
The packed colour.
Referenced by operator/().
toBGRByte()
Point3ub castor::toBGRByte (ColourT< ColourComponent > const & p_colour) inline
Stores a colour's components into a point in BGR format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toBGRFloat()
template<typename ComponentType > Point3f castor::toBGRFloat (ColourT< ComponentType > const & p_colour) inline
Stores a colour's components into a point in BGR format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toBGRPacked()
uint32_t castor::toBGRPacked (ColourT< ColourComponent > const & p_colour) inline
Packs a colour's components into an uint32_t in the BGR format (0x00BBGGRR).
Parameters
[in] p_colour The colour.
Returns
The packed colour.
Referenced by operator/().
toRGBAByte()
Point4ub castor::toRGBAByte (ColourT< ColourComponent > const & p_colour) inline
Stores a colour's components into a point in RGBA format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toRGBAFloat()
template<typename ComponentType > Point4f castor::toRGBAFloat (ColourT< ComponentType > const & p_colour) inline
Stores a colour's components into a point in RGBA format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toRGBAPacked()
uint32_t castor::toRGBAPacked (ColourT< ColourComponent > const & p_colour) inline
Packs a colour's components into an uint32_t in the RGBA format (0xRRGGBBAA).
Parameters
[in] p_colour The colour.
Returns
The packed colour.
Referenced by operator/().
toRGBByte()
Point3ub castor::toRGBByte (ColourT< ColourComponent > const & p_colour) inline
Stores a colour's components into a point in RGB format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toRGBFloat()
template<typename ComponentType > Point3f castor::toRGBFloat (ColourT< ComponentType > const & p_colour) inline
Stores a colour's components into a point in RGB format.
Parameters
[in] p_colour The colour.
Returns
The colour's components.
Referenced by operator/().
toRGBPacked()
uint32_t castor::toRGBPacked (ColourT< ColourComponent > const & p_colour) inline
Packs a colour's components into an uint32_t in the RGB format (0x00RRGGBB).
Parameters
[in] p_colour The colour.
Returns
The packed colour.
Referenced by operator/().
Variable Documentation
cuEmptyString
const String castor::cuEmptyString static
An empty String.
Author
Sylvain DOREMUS
Date
19/06/2012
ERROR_UNKNOWN_OBJECT
const std::string castor::ERROR_UNKNOWN_OBJECT = "Unknown object type" static
g_dummyDtor
CU_API DummyDtor castor::g_dummyDtor
Referenced by castor::DummyDtor::operator()().
STR_UNICITY_ERROR
char const* const castor::STR_UNICITY_ERROR[] static
Initial value:
=
    {
        "No instance for Unique class ",
        "Duplicate instance for Unique class ",
    }
Unicity error texts.
Author
Sylvain DOREMUS
Version
0.8.0
Date
12/01/2016