CastorUtils: castor::Glyph Class Reference
castor::Glyph Class Reference
Font character (glyph) representation.
Public Member Functions
Glyph (char32_t p_char, Size const &p_size, Position const &p_bearing, uint32_t p_advance, ByteArray const &p_bitmap)
Constructor.
~Glyph ()
Destructor.
char32_t getCharacter () const
Retrieves the glyph character.
Size const & getSize () const
Retrieves the glyph dimensions.
Position const & getBearing () const
uint32_t getAdvance () const
Retrieves the number of pixels to go before drawing next glyph.
ByteArray const & getBitmap () const
Retrieves the glyph image.
Detailed Description
Font character (glyph) representation.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
18/08/2011
Remarks
Holds position, size and data of a character
Constructor & Destructor Documentation
Glyph()
castor::Glyph::Glyph (char32_t p_char, Size const & p_size, Position const & p_bearing, uint32_t p_advance, ByteArray const & p_bitmap) inline
Constructor.
Parameters
[in] p_char The glyph character
[in] p_size The glyph dimensions
[in] p_bearing The glyph position relative to cursor
[in] p_advance Pixels to advance in order to go next character
[in] p_bitmap The glyph image
~Glyph()
castor::Glyph::~Glyph () inline
Destructor.
Member Function Documentation
getAdvance()
uint32_t castor::Glyph::getAdvance () const inline
Retrieves the number of pixels to go before drawing next glyph.
Returns
The value
getBearing()
Position const& castor::Glyph::getBearing () const inline
Returns
The glyph position relative to cursor.
getBitmap()
ByteArray const& castor::Glyph::getBitmap () const inline
Retrieves the glyph image.
Returns
A constant reference to the image of the glyph
getCharacter()
char32_t castor::Glyph::getCharacter () const inline
Retrieves the glyph character.
Returns
The value
Referenced by castor::operator!=(), castor::operator<(), castor::operator<=(), castor::operator==(), castor::operator>(), and castor::operator>=().
getSize()
Size const& castor::Glyph::getSize () const inline
Retrieves the glyph dimensions.
Returns
The glyph dimensions
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/Glyph.hpp