Castor3D: castor3d::Version Class Reference
castor3d::Version Class Reference
Version management class.
Public Member Functions
C3D_API Version (int p_major=CASTOR_VERSION_MAJOR, int p_minor=CASTOR_VERSION_MINOR, int p_build=CASTOR_VERSION_BUILD)
Constructor.
C3D_API ~Version ()
Destructor.
uint16_t getMajor () const
uint16_t getMinor () const
uint16_t getBuild () const
Detailed Description
Version management class.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
14/01/2011
Remarks
Class used to manage versions and versions dependencies for plug-ins
Constructor & Destructor Documentation
Version()
C3D_API castor3d::Version::Version (int p_major = CASTOR_VERSION_MAJOR, int p_minor = CASTOR_VERSION_MINOR, int p_build = CASTOR_VERSION_BUILD)
Constructor.
Parameters
[in] p_major The major version number.
[in] p_minor The minor version number.
[in] p_build The build version number.
~Version()
C3D_API castor3d::Version::~Version ()
Destructor.
Member Function Documentation
getBuild()
uint16_t castor3d::Version::getBuild () const inline
Returns
The build version number.
References C3D_API, castor3d::operator!=(), castor3d::operator<(), castor3d::operator<<(), castor3d::operator<=(), castor3d::operator==(), castor3d::operator>(), and castor3d::operator>=().
getMajor()
uint16_t castor3d::Version::getMajor () const inline
Returns
The major version number.
getMinor()
uint16_t castor3d::Version::getMinor () const inline
Returns
The major version number.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Miscellaneous/Version.hpp