notifications:
  email:
    on_success: never
    on_failure: never

language: cpp
compiler: g++
os: linux
sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libc6-dev
      - gcc-5-multilib
      - g++-5-multilib
      - cmake
      - libfreeimage-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libglm-dev
      - libassimp-dev

env:
  global:
    - COMPILER=g++-5

before_script:
  - export CXX="g++-5"
  - export CC="gcc-5"

script:
  - mkdir -p build/release
  - cd build/release
  - cmake -DCMAKE_BUILD_TYPE=Release ../../source -DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DCASTOR_BUILDGRP_TEST=ON -DCASTOR_BUILDGRP_INTEROP=OFF -DCASTOR_BUILDGRP_SAMPLE=OFF -DCASTOR_BUILDGRP_DIVIDER=ON -DCASTOR_BUILDGRP_TONEMAPS=ON -DCASTOR_BUILDGRP_GENERIC=ON -DCASTOR_BUILDGRP_IMPORTER=ON -DCASTOR_BUILDGRP_POSTFX=ON -DCASTOR_FORCE_ALL_IMPORTERS=ON
  - make -j2
  - make test

install: true
branches:
  only:
    - master
    - development
    - travis
