language: C++
compiler:
 - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - openrave-release
    packages:
    - cmake
    - libfreeimage-dev
    - libfreetype6-dev
    - libzip-dev
    - zlib1g-dev
    - libgtk2.0-dev
    - libwxgtk3.0-dev
    - libassimp-dev
    - libassimp3
script:
  - mkdir -p build/release
  - cd build/release
  - cmake -DCMAKE_BUILD_TYPE=Release ../../source -DCASTOR_BUILD_BINDING_PYCASTOR3D=OFF -DCASTOR_BUILD_BINDING_COM=OFF -DCASTOR_BUILD_BINDING_PYGUICOMMON=OFF -DCASTOR_BUILD_SAMPLE_GUICOMMON=ON -DCASTOR_BUILD_SAMPLE_CASTOR_VIEWER=ON -DCASTOR_BUILD_SAMPLE_OCEAN_LIGHTING=ON -DCASTOR_BUILD_SAMPLE_CASTOR_SHAPE=ON -DCASTOR_FORCE_ALL_IMPORTERS=ON
  - make -j4
  - make test
install: true
sudo: false