language: C++
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libfreeimage-dev
      - libfreetype6-dev
      - libzip-dev
      - zlib1g-dev
      - libglm-dev
      - g++-4.9
before_script:
  - export CXX="g++-4.9"
  - export CC="gcc-4.9"
script:
  - mkdir -p build/release
  - cd build/release
  - cmake -DCMAKE_BUILD_TYPE=Release ../../source -DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DCASTOR_BUILDGRP_TEST=ON -DCASTOR_BUILDGRP_INTEROP=OFF -DCASTOR_BUILDGRP_SAMPLE=OFF -DCASTOR_BUILDGRP_DIVIDER=ON -DCASTOR_BUILDGRP_GENERIC=ON -DCASTOR_BUILDGRP_IMPORTER=ON -DCASTOR_BUILDGRP_POSTFX=ON -DCASTOR_FORCE_ALL_IMPORTERS=ON
  - make -j2
  - make test
install: true
branches:
  only:
    - master
    - development
sudo: false
