CastorUtils: castor::HdrColourComponent Class Reference
castor::HdrColourComponent Class Reference
Defines a HDR colour PixelComponents (R, G, B or A) to be used in castor::HdrRgbColour or castor::HdrRgbaColour.
Public Member Functions
HdrColourComponent (float *p_value)
Specified constructor.
HdrColourComponent & operator= (HdrColourComponent const &p_rhs)
Copy assignment operator.
HdrColourComponent & operator= (float p_rhs)
Assignment operator from float.
HdrColourComponent & operator= (double p_rhs)
Assignment operator from double.
HdrColourComponent & operator= (long double p_rhs)
Assignment operator from long double.
HdrColourComponent & operator= (int8_t p_rhs)
Assignment operator from int8_t.
HdrColourComponent & operator= (uint8_t p_rhs)
Assignment operator from uint8_t.
HdrColourComponent & operator= (int16_t p_rhs)
Assignment operator from int16_t.
HdrColourComponent & operator= (uint16_t p_rhs)
Assignment operator from uint16_t.
HdrColourComponent & operator= (int32_t p_rhs)
Assignment operator from int32_t.
HdrColourComponent & operator= (uint32_t p_rhs)
Assignment operator from uint32_t.
HdrColourComponent & operator= (int64_t p_rhs)
Assignment operator from int64_t.
HdrColourComponent & operator= (uint64_t p_rhs)
Assignment operator from uint64_t.
int8_t & convertTo (int8_t &p_value) const
int8_t conversion operator
uint8_t & convertTo (uint8_t &p_value) const
uint8_t conversion operator
int16_t & convertTo (int16_t &p_value) const
int16_t conversion operator
uint16_t & convertTo (uint16_t &p_value) const
uint16_t conversion operator
int32_t & convertTo (int32_t &p_value) const
int32_t conversion operator
uint32_t & convertTo (uint32_t &p_value) const
uint32_t conversion operator
int64_t & convertTo (int64_t &p_value) const
int64_t conversion operator
uint64_t & convertTo (uint64_t &p_value) const
uint64_t conversion operator
float & convertTo (float &p_value) const
float conversion operator
double & convertTo (double &p_value) const
float conversion operator
long double & convertTo (long double &p_value) const
float conversion operator
void link (float *p_value)
sets the PixelComponents value
HdrColourComponent & operator+= (HdrColourComponent const &p_rhs)
addition assignment operator
HdrColourComponent & operator-= (HdrColourComponent const &p_rhs)
Substraction assignment operator.
HdrColourComponent & operator*= (HdrColourComponent const &p_rhs)
Multiplication assignment operator.
HdrColourComponent & operator/= (HdrColourComponent const &p_rhs)
Division assignment operator.
template<typename T >
HdrColourComponent & operator+= (T const &p_rhs)
addition assignment operator
template<typename T >
HdrColourComponent & operator-= (T const &p_rhs)
Substraction assignment operator.
template<typename T >
HdrColourComponent & operator*= (T const &p_rhs)
Multiplication assignment operator.
template<typename T >
HdrColourComponent & operator/= (T const &p_rhs)
Division assignment operator.
operator float () const
Implicit cast operator.
float const & value () const
Retrieves the PixelComponents value.
float & value ()
Retrieves the PixelComponents value.
Friends
class std::array< HdrColourComponent, 3u >
class std::array< HdrColourComponent, 4u >
Detailed Description
Defines a HDR colour PixelComponents (R, G, B or A) to be used in castor::HdrRgbColour or castor::HdrRgbaColour.
Author
Sylvain DOREMUS
Version
0.9.0
Date
07/10=1/2016
Remarks
Holds conversion operators to be converted either into float or uint8_t, with corresponding operations
Constructor & Destructor Documentation
HdrColourComponent()
castor::HdrColourComponent::HdrColourComponent (float * p_value) inline explicit
Specified constructor.
Parameters
[in] p_value The PixelComponents value
Member Function Documentation
convertTo() [1/11]
int8_t& castor::HdrColourComponent::convertTo (int8_t & p_value) const inline
int8_t conversion operator
References value().
Referenced by castor::operator*(), castor::operator+(), castor::operator-(), and castor::operator/().
convertTo() [2/11]
uint8_t& castor::HdrColourComponent::convertTo (uint8_t & p_value) const inline
uint8_t conversion operator
References value().
convertTo() [3/11]
int16_t& castor::HdrColourComponent::convertTo (int16_t & p_value) const inline
int16_t conversion operator
References value().
convertTo() [4/11]
uint16_t& castor::HdrColourComponent::convertTo (uint16_t & p_value) const inline
uint16_t conversion operator
References value().
convertTo() [5/11]
int32_t& castor::HdrColourComponent::convertTo (int32_t & p_value) const inline
int32_t conversion operator
References value().
convertTo() [6/11]
uint32_t& castor::HdrColourComponent::convertTo (uint32_t & p_value) const inline
uint32_t conversion operator
References value().
convertTo() [7/11]
int64_t& castor::HdrColourComponent::convertTo (int64_t & p_value) const inline
int64_t conversion operator
References value().
convertTo() [8/11]
uint64_t& castor::HdrColourComponent::convertTo (uint64_t & p_value) const inline
uint64_t conversion operator
References value().
convertTo() [9/11]
float& castor::HdrColourComponent::convertTo (float & p_value) const inline
float conversion operator
References value().
convertTo() [10/11]
double& castor::HdrColourComponent::convertTo (double & p_value) const inline
float conversion operator
References value().
convertTo() [11/11]
long double& castor::HdrColourComponent::convertTo (long double & p_value) const inline
float conversion operator
References value().
link()
void castor::HdrColourComponent::link (float * p_value) inline
sets the PixelComponents value
Remarks
Clamps the result
Parameters
[in] p_value The value
operator float()
castor::HdrColourComponent::operator float () const inline
Implicit cast operator.
Returns
The value
operator*=() [1/2]
HdrColourComponent& castor::HdrColourComponent::operator*= (HdrColourComponent const & p_rhs) inline
Multiplication assignment operator.
Remarks
Clamps the result
Parameters
[in] p_rhs The value to multiply
Returns
Result of this * p_rhs
References value().
operator*=() [2/2]
template<typename T > HdrColourComponent& castor::HdrColourComponent::operator*= (T const & p_rhs) inline
Multiplication assignment operator.
Parameters
[in] p_rhs The value to multiply
Returns
Result of this * p_rhs
operator+=() [1/2]
HdrColourComponent& castor::HdrColourComponent::operator+= (HdrColourComponent const & p_rhs) inline
addition assignment operator
Remarks
Clamps the result
Parameters
[in] p_rhs The value to add
Returns
Result of this + p_rhs
References value().
operator+=() [2/2]
template<typename T > HdrColourComponent& castor::HdrColourComponent::operator+= (T const & p_rhs) inline
addition assignment operator
Parameters
[in] p_rhs The value to add
Returns
Result of this + p_rhs
operator-=() [1/2]
HdrColourComponent& castor::HdrColourComponent::operator-= (HdrColourComponent const & p_rhs) inline
Substraction assignment operator.
Remarks
Clamps the result
Parameters
[in] p_rhs The value to subtract
Returns
Result of this - p_rhs
References value().
operator-=() [2/2]
template<typename T > HdrColourComponent& castor::HdrColourComponent::operator-= (T const & p_rhs) inline
Substraction assignment operator.
Parameters
[in] p_rhs The value to subtract
Returns
Result of this - p_rhs
operator/=() [1/2]
HdrColourComponent& castor::HdrColourComponent::operator/= (HdrColourComponent const & p_rhs) inline
Division assignment operator.
Remarks
Clamps the result
Parameters
[in] p_rhs The value to divide
Returns
Result of this / p_rhs
References value().
operator/=() [2/2]
template<typename T > HdrColourComponent& castor::HdrColourComponent::operator/= (T const & p_rhs) inline
Division assignment operator.
Parameters
[in] p_rhs The value to divide
Returns
Result of this / p_rhs
operator=() [1/12]
HdrColourComponent& castor::HdrColourComponent::operator= (HdrColourComponent const & p_rhs) inline
Copy assignment operator.
Parameters
[in] p_rhs The PixelComponents
Returns
Reference to this object
operator=() [2/12]
HdrColourComponent& castor::HdrColourComponent::operator= (float p_rhs) inline
Assignment operator from float.
Parameters
[in] p_rhs The PixelComponents value, must be between 0.0f and 1.0f
Returns
Reference to this object
operator=() [3/12]
HdrColourComponent& castor::HdrColourComponent::operator= (double p_rhs) inline
Assignment operator from double.
Parameters
[in] p_rhs The PixelComponents value, must be between 0.0 and 1.0
Returns
Reference to this object
operator=() [4/12]
HdrColourComponent& castor::HdrColourComponent::operator= (long double p_rhs) inline
Assignment operator from long double.
Parameters
[in] p_rhs The PixelComponents value, must be between 0.0 and 1.0
Returns
Reference to this object
operator=() [5/12]
HdrColourComponent& castor::HdrColourComponent::operator= (int8_t p_rhs) inline
Assignment operator from int8_t.
Parameters
[in] p_rhs The PixelComponents value
Returns
Reference to this object
operator=() [6/12]
HdrColourComponent& castor::HdrColourComponent::operator= (uint8_t p_rhs) inline
Assignment operator from uint8_t.
Parameters
[in] p_rhs The PixelComponents value
Returns
Reference to this object
operator=() [7/12]
HdrColourComponent& castor::HdrColourComponent::operator= (int16_t p_rhs) inline
Assignment operator from int16_t.
Parameters
[in] p_rhs The PixelComponents value, must be between 0 and 255
Returns
Reference to this object
operator=() [8/12]
HdrColourComponent& castor::HdrColourComponent::operator= (uint16_t p_rhs) inline
Assignment operator from uint16_t.
Parameters
[in] p_rhs The PixelComponents value, must be between 0 and 255
Returns
Reference to this object
operator=() [9/12]
HdrColourComponent& castor::HdrColourComponent::operator= (int32_t p_rhs) inline
Assignment operator from int32_t.
Parameters
[in] p_rhs The PixelComponents value, must be between 0 and 255
Returns
Reference to this object
operator=() [10/12]
HdrColourComponent& castor::HdrColourComponent::operator= (uint32_t p_rhs) inline
Assignment operator from uint32_t.
Parameters
[in] p_rhs The PixelComponents value, must be between 0 and 255
Returns
Reference to this object
operator=() [11/12]
HdrColourComponent& castor::HdrColourComponent::operator= (int64_t p_rhs) inline
Assignment operator from int64_t.
Parameters
[in] p_rhs The PixelComponents value, must be between 0 and 255
Returns
Reference to this object
operator=() [12/12]
HdrColourComponent& castor::HdrColourComponent::operator= (uint64_t p_rhs) inline
Assignment operator from uint64_t.
Parameters
[in] p_rhs The PixelComponents value, must be between 0 and 255
Returns
Reference to this object
value() [1/2]
float const& castor::HdrColourComponent::value () const inline
Retrieves the PixelComponents value.
Returns
The value
Referenced by convertTo(), operator*=(), operator+=(), operator-=(), and operator/=().
value() [2/2]
float& castor::HdrColourComponent::value () inline
Retrieves the PixelComponents value.
Returns
The value
References CU_API, castor::operator!=(), and castor::operator==().
Friends And Related Function Documentation
std::array< HdrColourComponent, 3u >
friend class std::array< HdrColourComponent, 3u > friend
std::array< HdrColourComponent, 4u >
friend class std::array< HdrColourComponent, 4u > friend
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/HdrColourComponent.hpp