CastorUtils: castor::PoolManagedObject< Object, MemDataType > Class Template Reference
castor::PoolManagedObject< Object, MemDataType > Class Template Reference
Pool managed object.
Public Types
using MyUniqueObjectPool = UniqueObjectPool< Object, MemDataType >
Public Member Functions
template<typename ... Params>
PoolManagedObject (Params ... p_params) noexcept
Constructor.
PoolManagedObject (PoolManagedObject const &p_rhs) noexcept
Copy constructor.
PoolManagedObject (Object const &p_rhs) noexcept
Copy constructor.
~PoolManagedObject () noexcept
Destructor.
Static Public Member Functions
static void * operator new (std::size_t p_size)
New operator overload.
static void operator delete (void *p_ptr, std::size_t p_size)
Delete operator overload.
static void operator delete[] (void *p_ptr, std::size_t p_size)
Delete array operator overload.
Detailed Description
template<typename Object, MemoryDataType MemDataType>
class castor::PoolManagedObject< Object, MemDataType >
Pool managed object.
Author
Sylvain DOREMUS
Version
0.8.0
Date
08/01/2016
Remarks
Uses a policy to change behaviour easily.
Parameters
Object The pool objects type.
MemDataType The allocation/deallocation policy type.
Member Typedef Documentation
MyUniqueObjectPool
template<typename Object , MemoryDataType MemDataType> using castor::PoolManagedObject< Object, MemDataType >::MyUniqueObjectPool = UniqueObjectPool< Object, MemDataType >
Constructor & Destructor Documentation
PoolManagedObject() [1/3]
template<typename Object , MemoryDataType MemDataType> template<typename ... Params> castor::PoolManagedObject< Object, MemDataType >::PoolManagedObject (Params ... p_params) inline explicit noexcept
Constructor.
Parameters
[in] p_params The Object constructor parameters.
PoolManagedObject() [2/3]
template<typename Object , MemoryDataType MemDataType> castor::PoolManagedObject< Object, MemDataType >::PoolManagedObject (PoolManagedObject< Object, MemDataType > const & p_rhs) inline noexcept
Copy constructor.
Parameters
[in] p_rhs The other object.
PoolManagedObject() [3/3]
template<typename Object , MemoryDataType MemDataType> castor::PoolManagedObject< Object, MemDataType >::PoolManagedObject (Object const & p_rhs) inline explicit noexcept
Copy constructor.
Parameters
[in] p_rhs The other object.
~PoolManagedObject()
template<typename Object , MemoryDataType MemDataType> castor::PoolManagedObject< Object, MemDataType >::~PoolManagedObject () inline noexcept
Destructor.
Member Function Documentation
operator delete()
template<typename Object , MemoryDataType MemDataType> static void castor::PoolManagedObject< Object, MemDataType >::operator delete (void * p_ptr, std::size_t p_size) inline static
Delete operator overload.
Remarks
Uses the objects pool to deallocate memory.
Parameters
[in] p_ptr The pointer to deallocate.
[in] p_size The deallocation size.
References castor::ObjectPool< Object, MemDataType >::deallocate(), and castor::UniqueObjectPool< Object, MemDataType >::get().
operator delete[]()
template<typename Object , MemoryDataType MemDataType> static void castor::PoolManagedObject< Object, MemDataType >::operator delete[] (void * p_ptr, std::size_t p_size) inline static
Delete array operator overload.
Remarks
Uses the objects pool to deallocate memory.
Parameters
[in] p_ptr The pointer to deallocate.
[in] p_size The deallocation size.
References castor::ObjectPool< Object, MemDataType >::deallocate(), and castor::UniqueObjectPool< Object, MemDataType >::get().
operator new()
template<typename Object , MemoryDataType MemDataType> static void* castor::PoolManagedObject< Object, MemDataType >::operator new (std::size_t p_size) inline static
New operator overload.
Remarks
Uses the objects pool to allocate memory.
Parameters
[in] p_size The allocation size.
References castor::ObjectPool< Object, MemDataType >::allocate(), and castor::UniqueObjectPool< Object, MemDataType >::get().
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/CastorUtilsPrerequisites.hpp
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Pool/PoolManagedObject.hpp