CastorUtils: castor::Size Class Reference
castor::Size Class Reference
Size class.
Public Member Functions
CU_API Size (uint32_t p_width=0, uint32_t p_height=0)
Constructor.
CU_API Size (Size const &p_obj)
Copy Constructor.
CU_API Size (Size &&p_obj)
Move assignment Constructor.
CU_API ~Size ()
Destructor.
CU_API Size & operator= (Size const &p_obj)
Copy assignment operator.
CU_API Size & operator= (Size &&p_obj)
Move assignment operator.
CU_API void set (uint32_t p_width, uint32_t p_height)
sets the size values
uint32_t getWidth () const
Retrieves the width.
uint32_t & getWidth ()
Retrieves the width.
uint32_t getHeight () const
Retrieves the height.
uint32_t & getHeight ()
Retrieves the height.
CU_API void grow (int32_t p_cx, int32_t p_cy)
Modifies the size.
Public Member Functions inherited from castor::Coords< uint32_t, 2 >
Coords ()
Constructor.
Coords (Coords< uint32_t, Count > const &p_point)
Copy Constructor.
Coords (Coords< uint32_t, Count > &&p_point)
Move assignment Constructor.
Coords (uint32_t *p_pValues)
Constructor.
~Coords ()
Destructor.
Coords< uint32_t, Count > & operator= (uint32_t *p_pValues)
Assignment operator.
Coords< uint32_t, Count > & operator= (Coords< uint32_t, Count > const &p_pt)
Copy assignment operator.
Coords< uint32_t, Count > & operator= (Coords< uint32_t, Count > &&p_pt)
Move assignment operator.
Coords< uint32_t, Count > & operator= (Point< uint32_t, Count > const &p_pt)
Copy assignment operator.
Coords< uint32_t, Count > & operator+= (Coords< U, _Count > const &p_pt)
addition assignment operator
Coords< uint32_t, Count > & operator+= (Point< U, _Count > const &p_pt)
addition assignment operator
Coords< uint32_t, Count > & operator+= (U const *p_coords)
addition assignment operator
Coords< uint32_t, Count > & operator-= (Coords< U, _Count > const &p_pt)
Substraction assignment operator.
Coords< uint32_t, Count > & operator-= (Point< U, _Count > const &p_pt)
Substraction assignment operator.
Coords< uint32_t, Count > & operator-= (U const *p_coords)
Substraction assignment operator.
Coords< uint32_t, Count > & operator*= (Coords< U, _Count > const &p_pt)
Multiplication assignment operator.
Coords< uint32_t, Count > & operator*= (Point< U, _Count > const &p_pt)
Multiplication assignment operator.
Coords< uint32_t, Count > & operator*= (U const *p_coords)
Multiplication assignment operator.
Coords< uint32_t, Count > & operator*= (uint32_t const &p_coord)
Multiplication assignment operator.
Coords< uint32_t, Count > & operator/= (Coords< U, _Count > const &p_pt)
Division assignment operator.
Coords< uint32_t, Count > & operator/= (Point< U, _Count > const &p_pt)
Division assignment operator.
Coords< uint32_t, Count > & operator/= (U const *p_coords)
Division assignment operator.
Coords< uint32_t, Count > & operator/= (uint32_t const &p_coord)
Division assignment operator.
void swap (Coords< uint32_t, Count > &p_pt)
Swaps this pont data with the parameter ones.
void flip ()
Inverts data in the point.
uint32_t size () const
Retrieves the total size of the point.
void toValues (uint32_t *p_pResult) const
Retrieves data from the point and put it into an array.
uint32_t count () const
Retrieves the number of coordinates.
std::size_t elemSize () const
Retrieves the coordinate type size.
uint32_t const & operator[] (uint32_t p_pos) const
Retrieves the data at given index.
uint32_t & operator[] (uint32_t p_pos)
Retrieves the data at given index.
uint32_t const & at (uint32_t p_pos) const
Retrieves the data at given index.
uint32_t & at (uint32_t p_pos)
Retrieves the data at given index.
uint32_t * ptr ()
Retrieves a non constant pointer on datas.
uint32_t const * constPtr () const
Retrieves a constant pointer on datas.
iterator begin ()
Retrieves an iterator to the first element.
const_iterator begin () const
Retrieves a constant iterator to the first element.
iterator end ()
Retrieves an iterator to the last element.
const_iterator end () const
Retrieves a constant iterator to the last element.
Additional Inherited Members
Public Types inherited from castor::Coords< uint32_t, 2 >
typedef value_type * iterator
Typedef over a pointer on data.
typedef value_type const * const_iterator
Typedef over a constant pointer on data.
Detailed Description
Size class.
Author
Sylvain DOREMUS
Date
20/02/2013
Version
0.7.0
Remarks
Kind of specialisation of Coords< 2, uint32_t >
Constructor & Destructor Documentation
Size() [1/3]
CU_API castor::Size::Size (uint32_t p_width = 0, uint32_t p_height = 0)
Constructor.
Parameters
[in] p_width,p_height The dimensions
Size() [2/3]
CU_API castor::Size::Size (Size const & p_obj)
Copy Constructor.
Parameters
[in] p_obj The object to copy
Size() [3/3]
CU_API castor::Size::Size (Size && p_obj)
Move assignment Constructor.
Parameters
[in] p_obj The object to move
~Size()
CU_API castor::Size::~Size ()
Destructor.
Member Function Documentation
getHeight() [1/2]
uint32_t castor::Size::getHeight () const inline
Retrieves the height.
Returns
The height
Referenced by castor::PxBufferBase::getHeight().
getHeight() [2/2]
uint32_t& castor::Size::getHeight () inline
Retrieves the height.
Returns
The height
References castor::Coords< uint32_t, 2 >::constPtr(), CU_API, grow(), and castor::Coords< uint32_t, 2 >::ptr().
getWidth() [1/2]
uint32_t castor::Size::getWidth () const inline
Retrieves the width.
Returns
The width
Referenced by castor::PxBufferBase::getWidth().
getWidth() [2/2]
uint32_t& castor::Size::getWidth () inline
Retrieves the width.
Returns
The width
grow()
CU_API void castor::Size::grow (int32_t p_cx, int32_t p_cy)
Modifies the size.
Remarks
If width+cx < 0 (or height+cy < 0) then width=0 (respectively height=0)
Parameters
[in] p_cx,p_cy The size modifications
Referenced by getHeight().
operator=() [1/2]
CU_API Size& castor::Size::operator= (Size const & p_obj)
Copy assignment operator.
Parameters
[in] p_obj The object to copy
Returns
A reference to this object
operator=() [2/2]
CU_API Size& castor::Size::operator= (Size && p_obj)
Move assignment operator.
Parameters
[in] p_obj The object to move
Returns
A reference to this object
set()
CU_API void castor::Size::set (uint32_t p_width, uint32_t p_height)
sets the size values
Parameters
[in] p_width,p_height The dimensions
Member Data Documentation
buffer
uint32_t castor::Size::buffer[2]
cx
uint32_t castor::Size::cx
cy
uint32_t castor::Size::cy
size
struct { ... } castor::Size::size
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/Size.hpp