Castor3D: castor3d::OverlayCategory Class Reference
castor3d::OverlayCategory Class Reference abstract
Holds specific members for an overlay category.
Classes
class TextWriter
OverlayCategory loader.
struct Vertex
Holds specific vertex data for an Overlay.
Public Member Functions
DECLARE_VECTOR (Vertex, Vertex)
C3D_API OverlayCategory (OverlayType p_type)
Constructor.
virtual C3D_API ~OverlayCategory ()
Destructor.
virtual C3D_API std::unique_ptr< TextWriter > createTextWriter (castor::String const &p_tabs)=0
Creates an OverlayCategory specific TextLoader.
C3D_API void update ()
Updates the overlay position, size...
C3D_API void render ()
Draws the overlay.
virtual C3D_API void setMaterial (MaterialSPtr p_material)
sets the material
C3D_API castor::String const & getOverlayName () const
Retrieves the overlay name.
C3D_API castor::Position getAbsolutePosition (castor::Size const &p_size) const
Retrieves the absolute overlay position, in pixels.
C3D_API castor::Size getAbsoluteSize (castor::Size const &p_size) const
Retrieves the absolute overlay size, in pixels.
C3D_API castor::Point2d getAbsolutePosition () const
Retrieves the absolute overlay position.
C3D_API castor::Point2d getAbsoluteSize () const
Retrieves the absolute overlay size.
C3D_API bool isSizeChanged () const
C3D_API bool isPositionChanged () const
virtual C3D_API bool isChanged () const
void setPosition (castor::Point2d const &p_position)
sets the overlay position
void setSize (castor::Point2d const &p_size)
sets the overlay size
castor::Point2d const & getSize () const
Retrieves the overlay size.
castor::Point2d const & getPosition () const
Retrieves the overlay position.
castor::Size const & getPixelSize () const
Retrieves the overlay size.
castor::Position const & getPixelPosition () const
Retrieves the overlay position.
castor::Point2d & getSize ()
Retrieves the overlay size.
castor::Point2d & getPosition ()
Retrieves the overlay position.
castor::Size & getPixelSize ()
Retrieves the overlay size.
castor::Position & getPixelPosition ()
Retrieves the overlay position.
OverlayType getType () const
Retrieves the overlay type.
bool isVisible () const
Retrieves the visibility status.
MaterialSPtr getMaterial () const
Retrieves the material.
int getIndex () const
Retrieves the index.
int getLevel () const
Retrieves the level.
Overlay const & getOverlay () const
Retrieves the overlay.
Overlay & getOverlay ()
Retrieves the overlay.
void setOverlay (Overlay *val)
sets the overlay
void setVisible (bool val)
sets the visibility status
void setPixelPosition (castor::Position const &val)
sets the overlay position
void setPixelSize (castor::Size const &val)
sets the overlay size
void setOrder (int p_index, int p_level)
sets the overlay order
void setUV (castor::Point4d const &val)
sets the overlay UV
castor::Point4d const & getUV () const
Retrieves the overlay UV.
Protected Member Functions
castor::Point2d doGetTotalSize () const
virtual void doUpdatePosition ()
Updates the overlay position, taking care of wanted pixel position.
virtual void doUpdateSize ()
Updates the overlay size, taking care of wanted pixel size.
virtual void doRender (OverlayRendererSPtr p_renderer)=0
Draws the overlay.
virtual void doUpdate ()
Updates the overlay position, size...
virtual void doUpdateBuffer (castor::Size const &p_size)=0
Updates the vertex buffer.
Protected Attributes
Overlay * m_pOverlay { nullptr }
The overlay.
castor::Point2d m_position
The relative position (to parent or screen)
castor::Point2d m_ptSize
The relative size (to parent or screen)
castor::Position m_pxPosition
The relative position (to parent or screen), in pixels.
castor::Size m_size
The absolute size in pixels.
bool m_visible { true }
The visibility.
MaterialWPtr m_pMaterial
The material used by the overlay.
int m_index { 0 }
The overlay index.
int m_level { 0 }
The overlay level.
castor::String m_strMatName
The material name.
OverlayType m_type
The overlay type.
bool m_sizeChanged { true }
Tells if this overlay's size has changed.
bool m_positionChanged { true }
Tells if this overlay's position has changed.
castor::Point4d m_uv { 0.0, 0.0, 1.0, 1.0 }
The UV for the panel.
Detailed Description
Holds specific members for an overlay category.
Author
Sylvain DOREMUS
Date
09/02/2010
Version
0.1
Constructor & Destructor Documentation
OverlayCategory()
C3D_API castor3d::OverlayCategory::OverlayCategory (OverlayType p_type) explicit
Constructor.
Parameters
[in] p_type The overlay type
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
~OverlayCategory()
virtual C3D_API castor3d::OverlayCategory::~OverlayCategory () virtual
Destructor.
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
Member Function Documentation
createTextWriter()
virtual C3D_API std::unique_ptr< TextWriter > castor3d::OverlayCategory::createTextWriter (castor::String const & p_tabs) pure virtual
Creates an OverlayCategory specific TextLoader.
Parameters
[in] p_tabs The current indentation level.
Returns
The TextLoader.
Implemented in castor3d::TextOverlay, castor3d::BorderPanelOverlay, and castor3d::PanelOverlay.
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
DECLARE_VECTOR()
castor3d::OverlayCategory::DECLARE_VECTOR (Vertex , Vertex)
doGetTotalSize()
castor::Point2d castor3d::OverlayCategory::doGetTotalSize () const protected
Returns
The screen or parent's size.
Referenced by getUV().
doRender()
virtual void castor3d::OverlayCategory::doRender (OverlayRendererSPtr p_renderer) protected pure virtual
Draws the overlay.
Parameters
[in] p_renderer The renderer used to draw this overlay
Implemented in castor3d::BorderPanelOverlay, and castor3d::PanelOverlay.
Referenced by getUV().
doUpdate()
virtual void castor3d::OverlayCategory::doUpdate () inline protected virtual
Updates the overlay position, size...
References doUpdateBuffer().
doUpdateBuffer()
virtual void castor3d::OverlayCategory::doUpdateBuffer (castor::Size const & p_size) protected pure virtual
Updates the vertex buffer.
Parameters
[in] p_size The render target size.
Implemented in castor3d::BorderPanelOverlay, and castor3d::PanelOverlay.
Referenced by doUpdate().
doUpdatePosition()
virtual void castor3d::OverlayCategory::doUpdatePosition () protected virtual
Updates the overlay position, taking care of wanted pixel position.
Referenced by getUV().
doUpdateSize()
virtual void castor3d::OverlayCategory::doUpdateSize () protected virtual
Updates the overlay size, taking care of wanted pixel size.
Reimplemented in castor3d::BorderPanelOverlay.
Referenced by getUV().
getAbsolutePosition() [1/2]
C3D_API castor::Position castor3d::OverlayCategory::getAbsolutePosition (castor::Size const & p_size) const
Retrieves the absolute overlay position, in pixels.
Parameters
[in] p_size The screen size
Returns
The position
getAbsolutePosition() [2/2]
C3D_API castor::Point2d castor3d::OverlayCategory::getAbsolutePosition () const
Retrieves the absolute overlay position.
Returns
The position
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
getAbsoluteSize() [1/2]
C3D_API castor::Size castor3d::OverlayCategory::getAbsoluteSize (castor::Size const & p_size) const
Retrieves the absolute overlay size, in pixels.
Parameters
[in] p_size The screen size
Returns
The size
getAbsoluteSize() [2/2]
C3D_API castor::Point2d castor3d::OverlayCategory::getAbsoluteSize () const
Retrieves the absolute overlay size.
Returns
The size
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
getIndex()
int castor3d::OverlayCategory::getIndex () const inline
Retrieves the index.
Returns
The value
References m_index.
getLevel()
int castor3d::OverlayCategory::getLevel () const inline
Retrieves the level.
Returns
The value
References m_level.
getMaterial()
MaterialSPtr castor3d::OverlayCategory::getMaterial () const inline
Retrieves the material.
Returns
The value
References m_pMaterial.
getOverlay() [1/2]
Overlay const& castor3d::OverlayCategory::getOverlay () const inline
Retrieves the overlay.
Returns
The value
References m_pOverlay.
getOverlay() [2/2]
Overlay& castor3d::OverlayCategory::getOverlay () inline
Retrieves the overlay.
Returns
The value
References m_pOverlay.
getOverlayName()
C3D_API castor::String const& castor3d::OverlayCategory::getOverlayName () const
Retrieves the overlay name.
Returns
The value
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
getPixelPosition() [1/2]
castor::Position const& castor3d::OverlayCategory::getPixelPosition () const inline
Retrieves the overlay position.
Returns
The value
References m_pxPosition.
getPixelPosition() [2/2]
castor::Position& castor3d::OverlayCategory::getPixelPosition () inline
Retrieves the overlay position.
Returns
The value
References m_pxPosition.
getPixelSize() [1/2]
castor::Size const& castor3d::OverlayCategory::getPixelSize () const inline
Retrieves the overlay size.
Returns
The value
References m_size.
getPixelSize() [2/2]
castor::Size& castor3d::OverlayCategory::getPixelSize () inline
Retrieves the overlay size.
Returns
The value
References m_size.
getPosition() [1/2]
castor::Point2d const& castor3d::OverlayCategory::getPosition () const inline
Retrieves the overlay position.
Returns
The value
References m_position.
getPosition() [2/2]
castor::Point2d& castor3d::OverlayCategory::getPosition () inline
Retrieves the overlay position.
Returns
The value
References m_position.
getSize() [1/2]
castor::Point2d const& castor3d::OverlayCategory::getSize () const inline
Retrieves the overlay size.
Returns
The value
References m_ptSize.
getSize() [2/2]
castor::Point2d& castor3d::OverlayCategory::getSize () inline
Retrieves the overlay size.
Returns
The value
References m_ptSize.
getType()
OverlayType castor3d::OverlayCategory::getType () const inline
Retrieves the overlay type.
Returns
The value
References m_type.
getUV()
castor::Point4d const& castor3d::OverlayCategory::getUV () const inline
Retrieves the overlay UV.
Returns
The value (left, top, right and bottom)
References doGetTotalSize(), doRender(), doUpdatePosition(), doUpdateSize(), and m_uv.
isChanged()
virtual C3D_API bool castor3d::OverlayCategory::isChanged () const inline virtual
Returns
true if this overlay's has changed.
Reimplemented in castor3d::TextOverlay, and castor3d::BorderPanelOverlay.
isPositionChanged()
C3D_API bool castor3d::OverlayCategory::isPositionChanged () const
Returns
true if this overlay's or one of its parents' position has changed.
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
isSizeChanged()
C3D_API bool castor3d::OverlayCategory::isSizeChanged () const
Returns
true if this overlay's or one of its parents' size has changed.
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
isVisible()
bool castor3d::OverlayCategory::isVisible () const inline
Retrieves the visibility status.
Returns
The value
References m_visible.
render()
C3D_API void castor3d::OverlayCategory::render ()
Draws the overlay.
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
setMaterial()
virtual C3D_API void castor3d::OverlayCategory::setMaterial (MaterialSPtr p_material) virtual
sets the material
Parameters
[in] p_material The new value
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
setOrder()
void castor3d::OverlayCategory::setOrder (int p_index, int p_level) inline
sets the overlay order
Parameters
[in] p_index The new index
[in] p_level The new level
References m_index, and m_level.
setOverlay()
void castor3d::OverlayCategory::setOverlay (Overlay * val) inline
sets the overlay
Parameters
[in] val The new value
References m_pOverlay.
setPixelPosition()
void castor3d::OverlayCategory::setPixelPosition (castor::Position const & val) inline
sets the overlay position
Parameters
[in] val The new value
References m_positionChanged, and m_pxPosition.
setPixelSize()
void castor3d::OverlayCategory::setPixelSize (castor::Size const & val) inline
sets the overlay size
Parameters
[in] val The new value
References m_size, and m_sizeChanged.
setPosition()
void castor3d::OverlayCategory::setPosition (castor::Point2d const & p_position) inline
sets the overlay position
Parameters
[in] p_position The new value
References m_position, and m_positionChanged.
setSize()
void castor3d::OverlayCategory::setSize (castor::Point2d const & p_size) inline
sets the overlay size
Parameters
[in] p_size The new value
References m_ptSize, and m_sizeChanged.
setUV()
void castor3d::OverlayCategory::setUV (castor::Point4d const & val) inline
sets the overlay UV
Parameters
[in] val The new value (left, top, right and bottom)
References m_uv.
setVisible()
void castor3d::OverlayCategory::setVisible (bool val) inline
sets the visibility status
Parameters
[in] val The new value
References m_visible.
update()
C3D_API void castor3d::OverlayCategory::update ()
Updates the overlay position, size...
Referenced by castor3d::OverlayCategory::TextWriter::writeInto().
Member Data Documentation
m_index
int castor3d::OverlayCategory::m_index { 0 } protected
The overlay index.
Referenced by getIndex(), and setOrder().
m_level
int castor3d::OverlayCategory::m_level { 0 } protected
The overlay level.
Referenced by getLevel(), and setOrder().
m_pMaterial
MaterialWPtr castor3d::OverlayCategory::m_pMaterial protected
The material used by the overlay.
Referenced by getMaterial().
m_position
castor::Point2d castor3d::OverlayCategory::m_position protected
The relative position (to parent or screen)
Referenced by getPosition(), castor3d::TextOverlay::setLineSpacingMode(), and setPosition().
m_positionChanged
bool castor3d::OverlayCategory::m_positionChanged { true } protected
Tells if this overlay's position has changed.
Referenced by setPixelPosition(), and setPosition().
m_pOverlay
Overlay* castor3d::OverlayCategory::m_pOverlay { nullptr } protected
The overlay.
Referenced by getOverlay(), and setOverlay().
m_ptSize
castor::Point2d castor3d::OverlayCategory::m_ptSize protected
The relative size (to parent or screen)
Referenced by getSize(), and setSize().
m_pxPosition
castor::Position castor3d::OverlayCategory::m_pxPosition protected
The relative position (to parent or screen), in pixels.
Referenced by getPixelPosition(), and setPixelPosition().
m_size
castor::Size castor3d::OverlayCategory::m_size protected
The absolute size in pixels.
Referenced by getPixelSize(), castor3d::TextOverlay::setLineSpacingMode(), and setPixelSize().
m_sizeChanged
bool castor3d::OverlayCategory::m_sizeChanged { true } protected
Tells if this overlay's size has changed.
Referenced by setPixelSize(), and setSize().
m_strMatName
castor::String castor3d::OverlayCategory::m_strMatName protected
The material name.
m_type
OverlayType castor3d::OverlayCategory::m_type protected
The overlay type.
Referenced by getType().
m_uv
castor::Point4d castor3d::OverlayCategory::m_uv { 0.0, 0.0, 1.0, 1.0 } protected
The UV for the panel.
Referenced by getUV(), and setUV().
m_visible
bool castor3d::OverlayCategory::m_visible { true } protected
The visibility.
Referenced by isVisible(), and setVisible().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Overlay/OverlayCategory.hpp