CastorUtils: castor::point Namespace Reference
castor::point Namespace Reference
Point helper functions.
Functions
template<typename T , uint32_t Count>
static void negate (Coords< T, Count > &p_point)
Negates every value of a point's data.
template<typename T , uint32_t Count>
static void normalise (Coords< T, Count > &p_point)
Normalises the point.
template<typename T , uint32_t Count>
static T dot (Coords< T, Count > const &lhs, Coords< T, Count > const &rhs)
Computes the scalar product of 2 points.
template<typename T , typename U >
static Point< T, 3 > cross (Coords< T, 3 > const &lhs, Coords< U, 3 > const &rhs)
Cross product operator.
template<typename T , uint32_t Count>
static double cosTheta (Coords< T, Count > const &lhs, Coords< T, Count > const &rhs)
Computes the trigonometric cosine of the angle between 2 points.
template<typename T , uint32_t Count>
static double lengthSquared (Coords< T, Count > const &p_point)
Computes the squared Euclidian length of the vector.
template<typename T , uint32_t Count>
static double length (Coords< T, Count > const &p_point)
Computes the Euclidian length of the vector.
template<typename T , uint32_t Count>
static double lengthManhattan (Coords< T, Count > const &p_point)
Computes the Manhattan length of the vector.
template<typename T , uint32_t Count>
static double lengthMinkowski (Coords< T, Count > const &p_point, double p_dOrder)
Computes the Minkowski length of the vector.
template<typename T , uint32_t Count>
static double lengthChebychev (Coords< T, Count > const &p_point)
Computes the Chebychev length of the vector.
template<typename T , uint32_t Count>
static double distanceSquared (Coords< T, Count > const &p_lhs, Coords< T, Count > const &p_rhs)
Computes the squared Euclidian distance between two points.
template<typename T , uint32_t Count>
static double distance (Coords< T, Count > const &p_lhs, Coords< T, Count > const &p_rhs)
Computes the Euclidian distance between two points.
template<typename T , uint32_t Count>
static double distanceManhattan (Coords< T, Count > const &p_lhs, Coords< T, Count > const &p_rhs)
Computes the Manhattan distance between two points.
template<typename T , uint32_t Count>
static double distanceMinkowski (Coords< T, Count > const &p_lhs, Coords< T, Count > const &p_rhs, double p_dOrder)
Computes the Minkowski distance between two points.
template<typename T , uint32_t Count>
static double distanceChebychev (Coords< T, Count > const &p_lhs, Coords< T, Count > const &p_rhs)
Computes the Chebychev distance between two points.
template<typename T , uint32_t Count>
static void negate (Point< T, Count > &point)
Negates every value of a point's data.
template<typename T , uint32_t Count>
static void normalise (Point< T, Count > &point)
Normalises the point.
template<typename T , uint32_t Count>
static Point< T, Count > getNormalised (Point< T, Count > const &point)
Returns the normalised form of a point.
template<typename T , typename U , uint32_t Count>
static T dot (Point< T, Count > const &lhs, Point< T, Count > const &rhs)
Computes the dot product of 2 points.
template<typename T , typename U >
static Point< T, 3 > cross (Point< T, 3 > const &lhs, Point< T, 3 > const &rhs)
Computes the cross product of 2 points.
template<typename T , uint32_t Count>
static double cosTheta (Point< T, Count > const &lhs, Point< T, Count > const &rhs)
Computes the trigonometric cosine of the angle between 2 points.
template<typename T , uint32_t Count>
static double lengthSquared (Point< T, Count > const &point)
Computes the squared Euclidian length of the vector.
template<typename T , uint32_t Count>
static double length (Point< T, Count > const &point)
Computes the Euclidian length of the vector.
template<typename T , uint32_t Count>
static double lengthManhattan (Point< T, Count > const &point)
Computes the Manhattan length of the vector.
template<typename T , uint32_t Count>
static double lengthMinkowski (Point< T, Count > const &point, double p_dOrder)
Computes the Minkowski length of the vector.
template<typename T , uint32_t Count>
static double lengthChebychev (Point< T, Count > const &point)
Computes the Chebychev length of the vector.
template<typename T , uint32_t Count>
static double distanceSquared (Point< T, Count > const &p_lhs, Point< T, Count > const &p_rhs)
Computes the squared Euclidian distance between two points.
template<typename T , uint32_t Count>
static double distance (Point< T, Count > const &p_lhs, Point< T, Count > const &p_rhs)
Computes the Euclidian distance between two points.
template<typename T , uint32_t Count>
static double distanceManhattan (Point< T, Count > const &p_lhs, Point< T, Count > const &p_rhs)
Computes the Manhattan distance between two points.
template<typename T , uint32_t Count>
static double distanceMinkowski (Point< T, Count > const &p_lhs, Point< T, Count > const &p_rhs, double p_dOrder)
Computes the Minkowski distance between two points.
template<typename T , uint32_t Count>
static double distanceChebychev (Point< T, Count > const &p_lhs, Point< T, Count > const &p_rhs)
Computes the Chebychev distance between two points.
template<typename T , typename U , uint32_t Count>
static T dot (Coords< T, Count > const &lhs, Point< T, Count > const &rhs)
Computes the dot product of 2 points.
template<typename T , typename U >
static Point< T, 3 > cross (Coords< T, 3 > const &lhs, Point< T, 3 > const &rhs)
Computes the cross product of 2 points.
template<typename T , uint32_t Count>
static double cosTheta (Coords< T, Count > const &lhs, Point< T, Count > const &rhs)
Computes the trigonometric cosine of the angle between 2 points.
template<typename T , typename U , uint32_t Count>
static T dot (Point< T, Count > const &lhs, Coords< T, Count > const &rhs)
Computes the scalar product of 2 points.
template<typename T , typename U >
static Point< T, 3 > cross (Point< T, 3 > const &lhs, Coords< T, 3 > const &rhs)
Computes the cross product of 2 points.
template<typename T , uint32_t Count>
static double cosTheta (Point< T, Count > const &lhs, Coords< T, Count > const &rhs)
Computes the trigonometric cosine of the angle between 2 points.
template<typename T , typename U , uint32_t Count>
static T dot (Coords< T const, Count > const &lhs, Point< T, Count > const &rhs)
Computes the scalar product of 2 points.
template<typename T , typename U >
static Point< T, 3 > cross (Coords< T const, 3 > const &lhs, Point< T, 3 > const &rhs)
Computes the cross product of 2 points.
template<typename T , uint32_t Count>
static double cosTheta (Coords< T const, Count > const &lhs, Point< T, Count > const &rhs)
Computes the trigonometric cosine of the angle between 2 points.
template<typename T , typename U , uint32_t Count>
static T dot (Point< T, Count > const &lhs, Coords< T const, Count > const &rhs)
Computes the scalar product of 2 points.
template<typename T , typename U >
static Point< T, 3 > cross (Point< T, 3 > const &lhs, Coords< T const, 3 > const &rhs)
Computes the cross product of 2 points.
template<typename T , uint32_t Count>
static double cosTheta (Point< T, Count > const &lhs, Coords< T const, Count > const &rhs)
Computes the trigonometric cosine of the angle between 2 points.
Detailed Description
Point helper functions.
Author
Sylvain DOREMUS
Date
10/07/2012
Version
0.7.0
Function Documentation
cosTheta() [1/6]
template<typename T , uint32_t Count> static double castor::point::cosTheta (Coords< T, Count > const & lhs, Coords< T, Count > const & rhs) static
Computes the trigonometric cosine of the angle between 2 points.
Parameters
[in] lhs,rhs The points
Returns
The cosine
cosTheta() [2/6]
template<typename T , uint32_t Count> static double castor::point::cosTheta (Point< T, Count > const & lhs, Point< T, Count > const & rhs) static
Computes the trigonometric cosine of the angle between 2 points.
Parameters
[in] lhs,rhs The points
Returns
The cosine
cosTheta() [3/6]
template<typename T , uint32_t Count> static double castor::point::cosTheta (Coords< T, Count > const & lhs, Point< T, Count > const & rhs) static
Computes the trigonometric cosine of the angle between 2 points.
Parameters
[in] lhs,rhs The points
Returns
The cosine
cosTheta() [4/6]
template<typename T , uint32_t Count> static double castor::point::cosTheta (Point< T, Count > const & lhs, Coords< T, Count > const & rhs) static
Computes the trigonometric cosine of the angle between 2 points.
Parameters
[in] lhs,rhs The points
Returns
The cosine
cosTheta() [5/6]
template<typename T , uint32_t Count> static double castor::point::cosTheta (Coords< T const, Count > const & lhs, Point< T, Count > const & rhs) static
Computes the trigonometric cosine of the angle between 2 points.
Parameters
[in] lhs,rhs The points
Returns
The cosine
cosTheta() [6/6]
template<typename T , uint32_t Count> static double castor::point::cosTheta (Point< T, Count > const & lhs, Coords< T const, Count > const & rhs) static
Computes the trigonometric cosine of the angle between 2 points.
Parameters
[in] lhs,rhs The points
Returns
The cosine
Referenced by castor::Point< real, Dimension >::end().
cross() [1/6]
template<typename T , typename U > static Point< T, 3 > castor::point::cross (Coords< T, 3 > const & lhs, Coords< U, 3 > const & rhs) static
Cross product operator.
Parameters
[in] lhs,rhs The points to multiply
Returns
The cross product
cross() [2/6]
template<typename T , typename U > static Point< T, 3 > castor::point::cross (Point< T, 3 > const & lhs, Point< T, 3 > const & rhs) static
Computes the cross product of 2 points.
Parameters
[in] lhs,rhs The points.
Returns
The resulting vector.
cross() [3/6]
template<typename T , typename U > static Point< T, 3 > castor::point::cross (Coords< T, 3 > const & lhs, Point< T, 3 > const & rhs) static
Computes the cross product of 2 points.
Parameters
[in] lhs,rhs The points.
Returns
The resulting vector.
cross() [4/6]
template<typename T , typename U > static Point< T, 3 > castor::point::cross (Point< T, 3 > const & lhs, Coords< T, 3 > const & rhs) static
Computes the cross product of 2 points.
Parameters
[in] lhs,rhs The points.
Returns
The resulting vector.
cross() [5/6]
template<typename T , typename U > static Point< T, 3 > castor::point::cross (Coords< T const, 3 > const & lhs, Point< T, 3 > const & rhs) static
Computes the cross product of 2 points.
Parameters
[in] lhs,rhs The points.
Returns
The resulting vector.
cross() [6/6]
template<typename T , typename U > static Point< T, 3 > castor::point::cross (Point< T, 3 > const & lhs, Coords< T const, 3 > const & rhs) static
Computes the cross product of 2 points.
Parameters
[in] lhs,rhs The points.
Returns
The resulting vector.
Referenced by castor::Point< real, Dimension >::end().
distance() [1/2]
template<typename T , uint32_t Count> static double castor::point::distance (Coords< T, Count > const & p_lhs, Coords< T, Count > const & p_rhs) static
Computes the Euclidian distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
Returns
The Euclidian distance.
distance() [2/2]
template<typename T , uint32_t Count> static double castor::point::distance (Point< T, Count > const & p_lhs, Point< T, Count > const & p_rhs) static
Computes the Euclidian distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
Returns
The Euclidian distance.
Referenced by castor::Point< real, Dimension >::end().
distanceChebychev() [1/2]
template<typename T , uint32_t Count> static double castor::point::distanceChebychev (Coords< T, Count > const & p_lhs, Coords< T, Count > const & p_rhs) static
Computes the Chebychev distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
Returns
The Chebychev distance.
distanceChebychev() [2/2]
template<typename T , uint32_t Count> static double castor::point::distanceChebychev (Point< T, Count > const & p_lhs, Point< T, Count > const & p_rhs) static
Computes the Chebychev distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
Returns
The Chebychev distance.
Referenced by castor::Point< real, Dimension >::end().
distanceManhattan() [1/2]
template<typename T , uint32_t Count> static double castor::point::distanceManhattan (Coords< T, Count > const & p_lhs, Coords< T, Count > const & p_rhs) static
Computes the Manhattan distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
Returns
The Manhattan distance.
distanceManhattan() [2/2]
template<typename T , uint32_t Count> static double castor::point::distanceManhattan (Point< T, Count > const & p_lhs, Point< T, Count > const & p_rhs) static
Computes the Manhattan distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
Returns
The Manhattan distance.
Referenced by castor::Point< real, Dimension >::end().
distanceMinkowski() [1/2]
template<typename T , uint32_t Count> static double castor::point::distanceMinkowski (Coords< T, Count > const & p_lhs, Coords< T, Count > const & p_rhs, double p_dOrder) static
Computes the Minkowski distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
[in] p_dOrder The Minkowski order.
Returns
The Minkowski distance.
distanceMinkowski() [2/2]
template<typename T , uint32_t Count> static double castor::point::distanceMinkowski (Point< T, Count > const & p_lhs, Point< T, Count > const & p_rhs, double p_dOrder) static
Computes the Minkowski distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
[in] p_dOrder The Minkowski order.
Returns
The Minkowski distance.
Referenced by castor::Point< real, Dimension >::end().
distanceSquared() [1/2]
template<typename T , uint32_t Count> static double castor::point::distanceSquared (Coords< T, Count > const & p_lhs, Coords< T, Count > const & p_rhs) static
Computes the squared Euclidian distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
Returns
The squared Euclidian distance.
distanceSquared() [2/2]
template<typename T , uint32_t Count> static double castor::point::distanceSquared (Point< T, Count > const & p_lhs, Point< T, Count > const & p_rhs) static
Computes the squared Euclidian distance between two points.
Parameters
[in] p_lhs,p_rhs The points.
Returns
The squared Euclidian distance.
Referenced by castor::Point< real, Dimension >::end().
dot() [1/6]
template<typename T , uint32_t Count> static T castor::point::dot (Coords< T, Count > const & lhs, Coords< T, Count > const & rhs) static
Computes the scalar product of 2 points.
Parameters
[in] lhs,rhs The points
Returns
The scalar product
dot() [2/6]
template<typename T , typename U , uint32_t Count> static T castor::point::dot (Point< T, Count > const & lhs, Point< T, Count > const & rhs) static
Computes the dot product of 2 points.
Parameters
[in] lhs,rhs The points
Returns
The scalar product
dot() [3/6]
template<typename T , typename U , uint32_t Count> static T castor::point::dot (Coords< T, Count > const & lhs, Point< T, Count > const & rhs) static
Computes the dot product of 2 points.
Parameters
[in] lhs,rhs The points
Returns
The scalar product
dot() [4/6]
template<typename T , typename U , uint32_t Count> static T castor::point::dot (Point< T, Count > const & lhs, Coords< T, Count > const & rhs) static
Computes the scalar product of 2 points.
Parameters
[in] lhs,rhs The points
Returns
The scalar product
dot() [5/6]
template<typename T , typename U , uint32_t Count> static T castor::point::dot (Coords< T const, Count > const & lhs, Point< T, Count > const & rhs) static
Computes the scalar product of 2 points.
Parameters
[in] lhs,rhs The points
Returns
The scalar product
dot() [6/6]
template<typename T , typename U , uint32_t Count> static T castor::point::dot (Point< T, Count > const & lhs, Coords< T const, Count > const & rhs) static
Computes the scalar product of 2 points.
Parameters
[in] lhs,rhs The points
Returns
The scalar product
Referenced by castor::Point< real, Dimension >::end().
getNormalised()
template<typename T , uint32_t Count> static Point< T, Count > castor::point::getNormalised (Point< T, Count > const & point) static
Returns the normalised form of a point.
Parameters
[in] point The point
Referenced by castor::Point< real, Dimension >::end().
length() [1/2]
template<typename T , uint32_t Count> static double castor::point::length (Coords< T, Count > const & p_point) static
Computes the Euclidian length of the vector.
Parameters
[in] p_point The point
Returns
The Euclidian distance
length() [2/2]
template<typename T , uint32_t Count> static double castor::point::length (Point< T, Count > const & point) static
Computes the Euclidian length of the vector.
Parameters
[in] point The point
Returns
The Euclidian distance
Referenced by castor::Point< real, Dimension >::end().
lengthChebychev() [1/2]
template<typename T , uint32_t Count> static double castor::point::lengthChebychev (Coords< T, Count > const & p_point) static
Computes the Chebychev length of the vector.
Parameters
[in] p_point The point
Returns
The Chebychev distance
lengthChebychev() [2/2]
template<typename T , uint32_t Count> static double castor::point::lengthChebychev (Point< T, Count > const & point) static
Computes the Chebychev length of the vector.
Parameters
[in] point The point
Returns
The Chebychev distance
Referenced by castor::Point< real, Dimension >::end().
lengthManhattan() [1/2]
template<typename T , uint32_t Count> static double castor::point::lengthManhattan (Coords< T, Count > const & p_point) static
Computes the Manhattan length of the vector.
Parameters
[in] p_point The point
Returns
The Manhattan distance
lengthManhattan() [2/2]
template<typename T , uint32_t Count> static double castor::point::lengthManhattan (Point< T, Count > const & point) static
Computes the Manhattan length of the vector.
Parameters
[in] point The point
Returns
The Manhattan distance
Referenced by castor::Point< real, Dimension >::end().
lengthMinkowski() [1/2]
template<typename T , uint32_t Count> static double castor::point::lengthMinkowski (Coords< T, Count > const & p_point, double p_dOrder) static
Computes the Minkowski length of the vector.
Parameters
[in] p_point The point
[in] p_dOrder The Minkowski order
Returns
The Minkowski distance
lengthMinkowski() [2/2]
template<typename T , uint32_t Count> static double castor::point::lengthMinkowski (Point< T, Count > const & point, double p_dOrder) static
Computes the Minkowski length of the vector.
Parameters
[in] point The point
[in] p_dOrder The Minkowski order
Returns
The Minkowski distance
Referenced by castor::Point< real, Dimension >::end().
lengthSquared() [1/2]
template<typename T , uint32_t Count> static double castor::point::lengthSquared (Coords< T, Count > const & p_point) static
Computes the squared Euclidian length of the vector.
Parameters
[in] p_point The point
Returns
The squared Euclidian distance
lengthSquared() [2/2]
template<typename T , uint32_t Count> static double castor::point::lengthSquared (Point< T, Count > const & point) static
Computes the squared Euclidian length of the vector.
Parameters
[in] point The point
Returns
The squared Euclidian distance
Referenced by castor::Point< real, Dimension >::end().
negate() [1/2]
template<typename T , uint32_t Count> static void castor::point::negate (Coords< T, Count > & p_point) static
Negates every value of a point's data.
Parameters
[in] p_point The point
negate() [2/2]
template<typename T , uint32_t Count> static void castor::point::negate (Point< T, Count > & point) static
Negates every value of a point's data.
Parameters
[in] point The point
Referenced by castor::Point< real, Dimension >::end().
normalise() [1/2]
template<typename T , uint32_t Count> static void castor::point::normalise (Coords< T, Count > & p_point) static
Normalises the point.
Remarks
A point is normalised when it's length equals 1.0
So each data is divided by the point's length
Parameters
[in] p_point The point
normalise() [2/2]
template<typename T , uint32_t Count> static void castor::point::normalise (Point< T, Count > & point) static
Normalises the point.
Remarks
A point is normalised when it's length equals 1.0
So each data is divided by the point's length
Parameters
[in] point The point
Referenced by castor::Point< real, Dimension >::end().