CastorUtils: castor::File Class Reference
castor::File Class Reference
User friendly File class.
Public Types
enum CreateMode : uint32_t {
CreateMode::eUserRead = 0x00000001, CreateMode::eUserWrite = 0x00000002, CreateMode::eUserExec = 0x00000004, CreateMode::eGroupRead = 0x00000010,
CreateMode::eGroupWrite = 0x00000020, CreateMode::eGroupExec = 0x00000040, CreateMode::eOthersRead = 0x00000100, CreateMode::eOthersWrite = 0x00000200,
CreateMode::eOthersExec = 0x00000400, CreateMode::eUserRWX = eUserRead | eUserWrite | eUserExec, CreateMode::eGroupRWX = eGroupRead | eGroupWrite | eGroupExec, CreateMode::eOthersRWX = eOthersRead | eOthersWrite | eOthersExec,
CreateMode::eAllRWX = eUserRWX | eGroupRWX | eOthersRWX
}
open modes enumerator
enum OpenMode : uint32_t {
OpenMode::eDummy = 0x00000000, OpenMode::eRead = 0x00000001, OpenMode::eWrite = 0x00000002, OpenMode::eAppend = 0x00000004,
OpenMode::eBinary = 0x00000008
}
open modes enumerator
enum OffsetMode : uint8_t { OffsetMode::eBeginning, OffsetMode::eCurrent, OffsetMode::eEnd }
Offset modes enumerator.
enum EncodingMode : uint8_t { EncodingMode::eAuto, EncodingMode::eASCII, EncodingMode::eUTF8, EncodingMode::eUTF16 }
Text file encoding mode.
Public Member Functions
virtual CU_API ~File ()
Destructor, closes the file.
CU_API int seek (long long p_offset, OffsetMode p_origin=OffsetMode::eBeginning)
sets the cursor in the file according to the given offset and the given mode
CU_API long long getLength ()
Retrieves the file size.
CU_API bool isOk () const
Tells if the file cursor is OK.
CU_API long long tell ()
Retrieves the file cursor position.
Path const & getFileFullPath () const
Retrieves the full file path, name and extension.
Path getFilePath () const
Retrieves the full file path.
Path getFileName () const
Retrieves the file name and extension.
Static Public Member Functions
static CU_API bool listDirectoryFiles (Path const &p_folderPath, PathArray &p_files, bool p_recursive=false)
List all files in a directory, recursively or not.
static CU_API Path getExecutableDirectory ()
Gives the current directory (id est where the execution is)
static CU_API Path getUserDirectory ()
Gives the user home directory.
static CU_API bool directoryExists (Path const &p_path)
Tests directory existence.
static CU_API bool directoryCreate (Path const &p_path, FlagCombination< CreateMode > const &p_flags=CreateMode::eAllRWX)
Creates a directory.
static CU_API bool directoryDelete (Path const &p_path)
Deletes an empty directory.
static CU_API bool fileExists (Path const &p_pathFile)
Tests file existence.
static CU_API bool deleteFile (Path const &p_file)
Deletes a file.
static CU_API bool copyFile (Path const &p_file, Path const &p_folder)
Copy a file into a folder.
Protected Member Functions
CU_API File (Path const &p_fileName, FlagCombination< OpenMode > const &p_mode, EncodingMode p_encoding=EncodingMode::eASCII)
Opens the file at the given path with the given mode and encoding.
CU_API uint64_t doWrite (uint8_t const *p_buffer, uint64_t p_uiSize)
CU_API uint64_t doRead (uint8_t *p_buffer, uint64_t p_uiSize)
Protected Attributes
FlagCombination< OpenMode > m_mode { 0u }
EncodingMode m_encoding { EncodingMode::eASCII }
Path m_fileFullPath
FILE * m_file { nullptr }
uint64_t m_cursor { 0 }
uint64_t m_length { 0 }
Detailed Description
User friendly File class.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Remarks
adds some static functions to check file/directory validity, file/directory creation...
Member Enumeration Documentation
CreateMode
enum castor::File::CreateMode : uint32_t strong
open modes enumerator
Enumerator
eUserRead
Owner can read.
eUserWrite
Owner can write.
eUserExec
Owner can execute.
eGroupRead
Owner group can read.
eGroupWrite
Owner group can write.
eGroupExec
Owner group can execute.
eOthersRead
Others can read.
eOthersWrite
Others can write.
eOthersExec
Others can execute.
eUserRWX
read, write and execution rights for owner.
eGroupRWX
read, write and execution rights for owner group.
eOthersRWX
read, write and execution rights for others.
eAllRWX
read, write and execution rights for all users.
EncodingMode
enum castor::File::EncodingMode : uint8_t strong
Text file encoding mode.
Enumerator
eAuto
Auto select text encoding.
eASCII
ASCII text encoding.
eUTF8
UTF8 text encoding.
eUTF16
UTF16 text encoding.
OffsetMode
enum castor::File::OffsetMode : uint8_t strong
Offset modes enumerator.
Enumerator
eBeginning
The offset is set from the beginning of the file.
eCurrent
The offset is set from the current position.
eEnd
The offset is set from the end of the file.
OpenMode
enum castor::File::OpenMode : uint32_t strong
open modes enumerator
Enumerator
eDummy
Dummy open mode, not to be used.
eRead
read open mode.
eWrite
write open mode.
eAppend
Append open mode.
eBinary
Binary open mode.
Constructor & Destructor Documentation
File()
CU_API castor::File::File (Path const & p_fileName, FlagCombination< OpenMode > const & p_mode, EncodingMode p_encoding = EncodingMode::eASCII) protected
Opens the file at the given path with the given mode and encoding.
Parameters
[in] p_fileName The file path
[in] p_mode The opening mode, combination of one or more OpenMode
[in] p_encoding The file encoding mode
~File()
virtual CU_API castor::File::~File () virtual
Destructor, closes the file.
Member Function Documentation
copyFile()
static CU_API bool castor::File::copyFile (Path const & p_file, Path const & p_folder) static
Copy a file into a folder.
Parameters
[in] p_file File name and path
[in] p_folder The destination folder
Returns
true if file has been correctly copied
Referenced by castor::TextWriter< RgbaColourT< ComponentType > >::copyFile().
deleteFile()
static CU_API bool castor::File::deleteFile (Path const & p_file) static
Deletes a file.
Parameters
[in] p_file File name and path
Returns
true if file has been correctly deleted
directoryCreate()
static CU_API bool castor::File::directoryCreate (Path const & p_path, FlagCombination< CreateMode > const & p_flags = CreateMode::eAllRWX) static
Creates a directory.
Parameters
[in] p_path Directory path
[in] p_flags User rights
Returns
true if the directory has been created
Referenced by castor::TextWriter< RgbaColourT< ComponentType > >::copyFile().
directoryDelete()
static CU_API bool castor::File::directoryDelete (Path const & p_path) static
Deletes an empty directory.
Parameters
[in] p_path Directory path
Returns
true if the directory has been deleted
directoryExists()
static CU_API bool castor::File::directoryExists (Path const & p_path) static
Tests directory existence.
Parameters
[in] p_path Directory path
Returns
true if directory is found
Referenced by castor::TextWriter< RgbaColourT< ComponentType > >::copyFile().
doRead()
CU_API uint64_t castor::File::doRead (uint8_t * p_buffer, uint64_t p_uiSize) protected
Referenced by getFileName().
doWrite()
CU_API uint64_t castor::File::doWrite (uint8_t const * p_buffer, uint64_t p_uiSize) protected
Referenced by getFileName().
fileExists()
static CU_API bool castor::File::fileExists (Path const & p_pathFile) static
Tests file existence.
Parameters
[in] p_pathFile File name and path
Returns
true if file is found
getExecutableDirectory()
static CU_API Path castor::File::getExecutableDirectory () static
Gives the current directory (id est where the execution is)
Returns
The directory
getFileFullPath()
Path const& castor::File::getFileFullPath () const inline
Retrieves the full file path, name and extension.
Returns
The value
References m_fileFullPath.
getFileName()
Path castor::File::getFileName () const inline
Retrieves the file name and extension.
Returns
The value
References CU_API, DECLARE_INVARIANT_BLOCK, doRead(), doWrite(), castor::Path::getFullFileName(), and m_fileFullPath.
getFilePath()
Path castor::File::getFilePath () const inline
Retrieves the full file path.
Returns
The value
References castor::Path::getPath(), and m_fileFullPath.
getLength()
CU_API long long castor::File::getLength ()
Retrieves the file size.
Returns
The value
getUserDirectory()
static CU_API Path castor::File::getUserDirectory () static
Gives the user home directory.
Returns
The directory
isOk()
CU_API bool castor::File::isOk () const
Tells if the file cursor is OK.
Returns
true if the file cursor is not in error and not EOF
listDirectoryFiles()
static CU_API bool castor::File::listDirectoryFiles (Path const & p_folderPath, PathArray & p_files, bool p_recursive = false) static
List all files in a directory, recursively or not.
Parameters
[in] p_folderPath The directory path
[out] p_files Receives the files list
[in] p_recursive Tells if search must be recursive
Returns
true if the directory is listed
seek()
CU_API int castor::File::seek (long long p_offset, OffsetMode p_origin = OffsetMode::eBeginning)
sets the cursor in the file according to the given offset and the given mode
Parameters
[in] p_offset The wanted offset
[in] p_origin The offset mode
Returns
0 if successful
tell()
CU_API long long castor::File::tell ()
Retrieves the file cursor position.
Returns
The value
Member Data Documentation
m_cursor
uint64_t castor::File::m_cursor { 0 } protected
The current cursor position in file.
m_encoding
EncodingMode castor::File::m_encoding { EncodingMode::eASCII } protected
The encoding mode.
m_file
FILE* castor::File::m_file { nullptr } protected
The file.
m_fileFullPath
Path castor::File::m_fileFullPath protected
The full file path.
Referenced by getFileFullPath(), getFileName(), and getFilePath().
m_length
uint64_t castor::File::m_length { 0 } protected
The total file length.
m_mode
FlagCombination< OpenMode > castor::File::m_mode { 0u } protected
The opening mode.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Data/File.hpp