CastorUtils: castor::ObjectPool< Object, MemDataType > Class Template Reference
castor::ObjectPool< Object, MemDataType > Class Template Reference
The objects pool.
Public Member Functions
ObjectPool (size_t p_count) noexcept
Constructor, initialises the pool with given elements count.
~ObjectPool () noexcept
Destructor.
void Reset () noexcept
Resets the pool.
template<typename ... TParams>
Object * allocate (TParams ... p_params)
Allocates and builds an object from the pool's memory.
bool deallocate (Object *p_object) noexcept
Deallocates an object (gives its memory back to the pool).
uint32_t getCount () noexcept
Detailed Description
template<typename Object, MemoryDataType MemDataType>
class castor::ObjectPool< Object, MemDataType >
The objects pool.
Author
Sylvain DOREMUS
Version
0.8.0
Date
08/01/2016
Remarks
Uses a policy to change behaviour easily.
Parameters
Object The pool objects type.
MemDataType The allocation/deallocation policy type.
Constructor & Destructor Documentation
ObjectPool()
template<typename Object , MemoryDataType MemDataType> castor::ObjectPool< Object, MemDataType >::ObjectPool (size_t p_count) inline explicit noexcept
Constructor, initialises the pool with given elements count.
Parameters
[in] p_count The elements count.
~ObjectPool()
template<typename Object , MemoryDataType MemDataType> castor::ObjectPool< Object, MemDataType >::~ObjectPool () inline noexcept
Destructor.
Member Function Documentation
allocate()
template<typename Object , MemoryDataType MemDataType> template<typename ... TParams> Object* castor::ObjectPool< Object, MemDataType >::allocate (TParams ... p_params) inline
Allocates and builds an object from the pool's memory.
Parameters
[in] p_params The object's constructor parameters.
Returns
The built object, or nullptr.
Referenced by castor::PoolManagedObject< Object, MemDataType >::operator new().
deallocate()
template<typename Object , MemoryDataType MemDataType> bool castor::ObjectPool< Object, MemDataType >::deallocate (Object * p_object) inline noexcept
Deallocates an object (gives its memory back to the pool).
Parameters
[in] p_object The object to deallocate.
Returns
true if the object came from the pool.
Referenced by castor::PoolManagedObject< Object, MemDataType >::operator delete(), and castor::PoolManagedObject< Object, MemDataType >::operator delete[]().
getCount()
template<typename Object , MemoryDataType MemDataType> uint32_t castor::ObjectPool< Object, MemDataType >::getCount () inline noexcept
Returns
The objects count.
Reset()
template<typename Object , MemoryDataType MemDataType> void castor::ObjectPool< Object, MemDataType >::Reset () inline noexcept
Resets the pool.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Pool/ObjectPool.hpp