CastorUtils: castor::Debug::Backtrace Struct Reference
castor::Debug::Backtrace Struct Reference
Public Member Functions
Backtrace (int p_toCapture=20, int p_toSkip=2)
Public Attributes
int const m_toCapture
int const m_toSkip
Constructor & Destructor Documentation
Backtrace()
castor::Debug::Backtrace::Backtrace (int p_toCapture = 20, int p_toSkip = 2) inline
References castor::Debug::cleanup(), CU_API, castor::Debug::initialise(), castor::Debug::loadModule(), castor::Debug::operator<<(), and castor::Debug::unloadModule().
Member Data Documentation
m_toCapture
int const castor::Debug::Backtrace::m_toCapture
m_toSkip
int const castor::Debug::Backtrace::m_toSkip
The documentation for this struct was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Miscellaneous/Debug.hpp