CastorUtils: castor::RgbColourT< ComponentType > Class Template Reference
castor::RgbColourT< ComponentType > Class Template Reference
RGB colour representation.
Classes
class TextLoader
RgbColourT text loader.
class TextWriter
RgbColourT text Writer.
Public Member Functions
RgbColourT ()
Default Constructor.
RgbColourT (RgbColourT< ComponentType > const &rhs)
Copy Constructor.
RgbColourT (RgbColourT< ComponentType > &&rhs)
Move Constructor.
RgbColourT< ComponentType > & operator= (RgbColourT< ComponentType > const &rhs)
Copy assignment operator.
RgbColourT< ComponentType > & operator= (RgbColourT< ComponentType > &&rhs)
Move assignment operator.
ColourComponentArrayIt begin ()
Retrieves an iterator to the first ColourComponent.
ColourComponentArrayConstIt begin () const
Retrieves a constant iterator to the first ColourComponent.
ColourComponentArrayIt end ()
Retrieves an iterator to beyond the last ColourComponent.
ColourComponentArrayConstIt end () const
Retrieves a constant iterator to beyond the last ColourComponent.
float const * constPtr () const
Retrieves a constant pointer to the colour values.
float * ptr ()
Retrieves a pointer to the colour values.
ComponentType & operator[] (RgbComponent component)
Retrieves the asked PixelComponents value.
ComponentType const & operator[] (RgbComponent component) const
Retrieves the asked PixelComponents value.
ComponentType & get (RgbComponent component)
Retrieves the asked PixelComponents value.
ComponentType const & get (RgbComponent component) const
Retrieves the asked PixelComponents value.
ComponentType & red ()
Retrieves the red PixelComponents value.
ComponentType const & red () const
Retrieves the red PixelComponents value.
ComponentType & green ()
Retrieves the green PixelComponents value.
ComponentType const & green () const
Retrieves the green PixelComponents value.
ComponentType & blue ()
Retrieves the blue PixelComponents value.
ComponentType const & blue () const
Retrieves the blue PixelComponents value.
RgbColourT< ComponentType > & operator+= (RgbColourT const &rhs)
addition assignment operator
RgbColourT< ComponentType > & operator-= (RgbColourT const &rhs)
Substraction assignment operator.
template<typename T >
RgbColourT< ComponentType > & operator+= (T scalar)
addition assignment operator
template<typename T >
RgbColourT< ComponentType > & operator-= (T scalar)
Substraction assignment operator.
template<typename T >
RgbColourT< ComponentType > & operator*= (T scalar)
Multiplication assignment operator.
template<typename T >
RgbColourT< ComponentType > & operator/= (T scalar)
Division assignment operator.
RgbColourT< ComponentType > & operator+= (ComponentType const &component)
addition assignment operator
RgbColourT< ComponentType > & operator-= (ComponentType const &component)
Substraction assignment operator.
RgbColourT< ComponentType > & operator*= (ComponentType const &component)
Multiplication assignment operator.
RgbColourT< ComponentType > & operator/= (ComponentType const &component)
Division assignment operator.
Static Public Member Functions
template<typename T1 , typename T2 , typename T3 >
static RgbColourT< ComponentType > fromComponents (T1 const &r, T2 const &g, T3 const &b)
Constructor from components.
static RgbColourT< ComponentType > fromPredefined (PredefinedRgbColour predefined)
Constructor from a predefined colour.
static RgbColourT< ComponentType > fromRGB (Point3ub const &colour)
Constructor from a point representing RGB components.
static RgbColourT< ComponentType > fromBGR (Point3ub const &colour)
Constructor from a point representing BGR components.
static RgbColourT< ComponentType > fromRGBA (Point4ub const &colour)
Constructor from a point representing RGBA components.
static RgbColourT< ComponentType > fromBGRA (Point4ub const &colour)
Constructor from a point representing BGRA components.
static RgbColourT< ComponentType > fromARGB (Point4ub const &colour)
Constructor from a point representing ARGB components.
static RgbColourT< ComponentType > fromABGR (Point4ub const &colour)
Constructor from a point representing ABGR components.
static RgbColourT< ComponentType > fromRGB (Point3f const &colour)
Constructor from a point representing RGB components.
static RgbColourT< ComponentType > fromBGR (Point3f const &colour)
Constructor from a point representing BGR components.
static RgbColourT< ComponentType > fromRGBA (Point4f const &colour)
Constructor from a point representing RGBA components.
static RgbColourT< ComponentType > fromARGB (Point4f const &colour)
Constructor from a point representing ARGB components.
static RgbColourT< ComponentType > fromABGR (Point4f const &colour)
Constructor from a point representing ABGR components.
static RgbColourT< ComponentType > fromBGRA (Point4f const &colour)
Constructor from a point representing BGRA components.
static RgbColourT< ComponentType > fromRGB (uint8_t const(&colour)[3])
Constructor from a point representing RGB components.
static RgbColourT< ComponentType > fromBGR (uint8_t const(&colour)[3])
Constructor from a point representing BGR components.
static RgbColourT< ComponentType > fromRGBA (uint8_t const(&colour)[4])
Constructor from a point representing RGBA components.
static RgbColourT< ComponentType > fromBGRA (uint8_t const(&colour)[4])
Constructor from a point representing BGRA components.
static RgbColourT< ComponentType > fromARGB (uint8_t const(&colour)[4])
Constructor from a point representing ARGB components.
static RgbColourT< ComponentType > fromABGR (uint8_t const(&colour)[4])
Constructor from a point representing ABGR components.
static RgbColourT< ComponentType > fromRGB (float const(&colour)[3])
Constructor from a point representing RGB components.
static RgbColourT< ComponentType > fromBGR (float const(&colour)[3])
Constructor from a point representing BGR components.
static RgbColourT< ComponentType > fromRGBA (float const(&colour)[4])
Constructor from a point representing RGBA components.
static RgbColourT< ComponentType > fromARGB (float const(&colour)[4])
Constructor from a point representing ARGB components.
static RgbColourT< ComponentType > fromABGR (float const(&colour)[4])
Constructor from a point representing ABGR components.
static RgbColourT< ComponentType > fromBGRA (float const(&colour)[4])
Constructor from a point representing BGRA components.
static RgbColourT< ComponentType > fromRGB (uint32_t colour)
Constructor from an uint32_t representing RGB components.
static RgbColourT< ComponentType > fromBGR (uint32_t colour)
Constructor from an uint32_t representing BGR components.
static RgbColourT< ComponentType > fromARGB (uint32_t colour)
Constructor from an uint32_t representing ARGB components.
static RgbColourT< ComponentType > fromRGBA (uint32_t colour)
Constructor from an uint32_t representing RGBA components.
static RgbColourT< ComponentType > fromABGR (uint32_t colour)
Constructor from an uint32_t representing ABGR components.
static RgbColourT< ComponentType > fromBGRA (uint32_t colour)
Constructor from an uint32_t representing BGRA components.
Detailed Description
template<typename ComponentType>
class castor::RgbColourT< ComponentType >
RGB colour representation.
Author
Sylvain DOREMUS
Date
14/08/2010
Remarks
Predefines numerous colours
Allows conversion to different colour formats (RGB, ARGB, BGR, ...) and different data types (long, float, char, ...)
Constructor & Destructor Documentation
RgbColourT() [1/3]
template<typename ComponentType> castor::RgbColourT< ComponentType >::RgbColourT () inline
Default Constructor.
RgbColourT() [2/3]
template<typename ComponentType> castor::RgbColourT< ComponentType >::RgbColourT (RgbColourT< ComponentType > const & rhs) inline
Copy Constructor.
Parameters
[in] rhs The object to copy
RgbColourT() [3/3]
template<typename ComponentType> castor::RgbColourT< ComponentType >::RgbColourT (RgbColourT< ComponentType > && rhs) inline
Move Constructor.
Parameters
[in] rhs The object to move
Member Function Documentation
begin() [1/2]
template<typename ComponentType> ColourComponentArrayIt castor::RgbColourT< ComponentType >::begin () inline
Retrieves an iterator to the first ColourComponent.
Returns
The iterator
begin() [2/2]
template<typename ComponentType> ColourComponentArrayConstIt castor::RgbColourT< ComponentType >::begin () const inline
Retrieves a constant iterator to the first ColourComponent.
Returns
The iterator
blue() [1/2]
template<typename ComponentType> ComponentType& castor::RgbColourT< ComponentType >::blue () inline
Retrieves the blue PixelComponents value.
Returns
The PixelComponents value
References castor::eBlue.
blue() [2/2]
template<typename ComponentType> ComponentType const& castor::RgbColourT< ComponentType >::blue () const inline
Retrieves the blue PixelComponents value.
Returns
The PixelComponents value
References castor::eBlue.
constPtr()
template<typename ComponentType> float const* castor::RgbColourT< ComponentType >::constPtr () const inline
Retrieves a constant pointer to the colour values.
Returns
The pointer
end() [1/2]
template<typename ComponentType> ColourComponentArrayIt castor::RgbColourT< ComponentType >::end () inline
Retrieves an iterator to beyond the last ColourComponent.
Returns
The iterator
end() [2/2]
template<typename ComponentType> ColourComponentArrayConstIt castor::RgbColourT< ComponentType >::end () const inline
Retrieves a constant iterator to beyond the last ColourComponent.
Returns
The iterator
fromABGR() [1/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromABGR (Point4ub const & colour) inline static
Constructor from a point representing ABGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromABGR() [2/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromABGR (Point4f const & colour) inline static
Constructor from a point representing ABGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromABGR() [3/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromABGR (uint8_t const(&) colour[4]) inline static
Constructor from a point representing ABGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromABGR() [4/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromABGR (float const(&) colour[4]) inline static
Constructor from a point representing ABGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromABGR() [5/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromABGR (uint32_t colour) inline static
Constructor from an uint32_t representing ABGR components.
Parameters
[in] colour The uint32_t containing the colour (0xAABBGGRR)
Returns
The built RgbColourT
fromARGB() [1/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromARGB (Point4ub const & colour) inline static
Constructor from a point representing ARGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromARGB() [2/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromARGB (Point4f const & colour) inline static
Constructor from a point representing ARGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromARGB() [3/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromARGB (uint8_t const(&) colour[4]) inline static
Constructor from a point representing ARGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromARGB() [4/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromARGB (float const(&) colour[4]) inline static
Constructor from a point representing ARGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromARGB() [5/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromARGB (uint32_t colour) inline static
Constructor from an uint32_t representing ARGB components.
Parameters
[in] colour The uint32_t containing the colour (0xAARRGGBB)
Returns
The built RgbColourT
fromBGR() [1/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGR (Point3ub const & colour) inline static
Constructor from a point representing BGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGR() [2/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGR (Point3f const & colour) inline static
Constructor from a point representing BGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGR() [3/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGR (uint8_t const(&) colour[3]) inline static
Constructor from a point representing BGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGR() [4/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGR (float const(&) colour[3]) inline static
Constructor from a point representing BGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGR() [5/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGR (uint32_t colour) inline static
Constructor from an uint32_t representing BGR components.
Parameters
[in] colour The uint32_t containing the colour (0x00BBGGRR)
Returns
The built RgbColourT
fromBGRA() [1/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGRA (Point4ub const & colour) inline static
Constructor from a point representing BGRA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGRA() [2/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGRA (Point4f const & colour) inline static
Constructor from a point representing BGRA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGRA() [3/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGRA (uint8_t const(&) colour[4]) inline static
Constructor from a point representing BGRA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGRA() [4/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGRA (float const(&) colour[4]) inline static
Constructor from a point representing BGRA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGRA() [5/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromBGRA (uint32_t colour) inline static
Constructor from an uint32_t representing BGRA components.
Parameters
[in] colour The uint32_t containing the colour (0xBBGGRRAA)
Returns
The built RgbColourT
fromComponents()
template<typename ComponentType> template<typename T1 , typename T2 , typename T3 > static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromComponents (T1 const & r, T2 const & g, T3 const & b) inline static
Constructor from components.
Parameters
[in] r,g,b The colour components
Returns
The built RgbColourT
References castor::eBlue, castor::eGreen, and castor::eRed.
fromPredefined()
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromPredefined (PredefinedRgbColour predefined) inline static
Constructor from a predefined colour.
Parameters
[in] predefined
Returns
The built RgbColourT
fromRGB() [1/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGB (Point3ub const & colour) inline static
Constructor from a point representing RGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGB() [2/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGB (Point3f const & colour) inline static
Constructor from a point representing RGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGB() [3/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGB (uint8_t const(&) colour[3]) inline static
Constructor from a point representing RGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGB() [4/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGB (float const(&) colour[3]) inline static
Constructor from a point representing RGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGB() [5/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGB (uint32_t colour) inline static
Constructor from an uint32_t representing RGB components.
Parameters
[in] colour The uint32_t containing the colour (0x00RRGGBB)
Returns
The built RgbColourT
fromRGBA() [1/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGBA (Point4ub const & colour) inline static
Constructor from a point representing RGBA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGBA() [2/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGBA (Point4f const & colour) inline static
Constructor from a point representing RGBA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGBA() [3/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGBA (uint8_t const(&) colour[4]) inline static
Constructor from a point representing RGBA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGBA() [4/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGBA (float const(&) colour[4]) inline static
Constructor from a point representing RGBA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGBA() [5/5]
template<typename ComponentType> static RgbColourT< ComponentType > castor::RgbColourT< ComponentType >::fromRGBA (uint32_t colour) inline static
Constructor from an uint32_t representing RGBA components.
Parameters
[in] colour The uint32_t containing the colour (0xRRGGBBAA)
Returns
The built RgbColourT
get() [1/2]
template<typename ComponentType> ComponentType& castor::RgbColourT< ComponentType >::get (RgbComponent component) inline
Retrieves the asked PixelComponents value.
Parameters
[in] component The asked PixelComponents
Returns
The PixelComponents value
get() [2/2]
template<typename ComponentType> ComponentType const& castor::RgbColourT< ComponentType >::get (RgbComponent component) const inline
Retrieves the asked PixelComponents value.
Parameters
[in] component The asked PixelComponents
Returns
The PixelComponents value
green() [1/2]
template<typename ComponentType> ComponentType& castor::RgbColourT< ComponentType >::green () inline
Retrieves the green PixelComponents value.
Returns
The PixelComponents value
References castor::eGreen.
green() [2/2]
template<typename ComponentType> ComponentType const& castor::RgbColourT< ComponentType >::green () const inline
Retrieves the green PixelComponents value.
Returns
The PixelComponents value
References castor::eGreen.
operator*=() [1/2]
template<typename ComponentType> template<typename T > RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator*= (T scalar) inline
Multiplication assignment operator.
Parameters
[in] scalar The value to multiply
Returns
Result of this * scalar
References castor::eCount, and castor::details::i.
operator*=() [2/2]
template<typename ComponentType> RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator*= (ComponentType const & component) inline
Multiplication assignment operator.
Parameters
[in] component The value to multiply
Returns
Result of this * component
operator+=() [1/3]
template<typename ComponentType> RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator+= (RgbColourT< ComponentType > const & rhs) inline
addition assignment operator
Parameters
[in] rhs The colours to add
Returns
Result of this + rhs
operator+=() [2/3]
template<typename ComponentType> template<typename T > RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator+= (T scalar) inline
addition assignment operator
Parameters
[in] scalar The value to add
Returns
Result of this + scalar
References castor::eCount, and castor::details::i.
operator+=() [3/3]
template<typename ComponentType> RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator+= (ComponentType const & component) inline
addition assignment operator
Parameters
[in] component The value to add
Returns
Result of this + component
operator-=() [1/3]
template<typename ComponentType> RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator-= (RgbColourT< ComponentType > const & rhs) inline
Substraction assignment operator.
Parameters
[in] rhs The colours to subtract
Returns
Result of this - rhs
operator-=() [2/3]
template<typename ComponentType> template<typename T > RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator-= (T scalar) inline
Substraction assignment operator.
Parameters
[in] scalar The value to subtract
Returns
Result of this - scalar
References castor::eCount, and castor::details::i.
operator-=() [3/3]
template<typename ComponentType> RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator-= (ComponentType const & component) inline
Substraction assignment operator.
Parameters
[in] component The value to subtract
Returns
Result of this - component
operator/=() [1/2]
template<typename ComponentType> template<typename T > RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator/= (T scalar) inline
Division assignment operator.
Parameters
[in] scalar The value to divide
Returns
Result of this / scalar
References castor::eCount, castor::details::i, castor::operator!=(), castor::operator+(), castor::operator-(), and castor::operator==().
operator/=() [2/2]
template<typename ComponentType> RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator/= (ComponentType const & component) inline
Division assignment operator.
Parameters
[in] component The value to divide
Returns
Result of this / component
operator=() [1/2]
template<typename ComponentType> RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator= (RgbColourT< ComponentType > const & rhs) inline
Copy assignment operator.
Parameters
[in] rhs The object to copy
Returns
A reference to this object
operator=() [2/2]
template<typename ComponentType> RgbColourT< ComponentType >& castor::RgbColourT< ComponentType >::operator= (RgbColourT< ComponentType > && rhs) inline
Move assignment operator.
Parameters
[in] rhs The object to copy
Returns
Reference to this colour
operator[]() [1/2]
template<typename ComponentType> ComponentType& castor::RgbColourT< ComponentType >::operator[] (RgbComponent component) inline
Retrieves the asked PixelComponents value.
Parameters
[in] component The asked PixelComponents
Returns
The PixelComponents value
operator[]() [2/2]
template<typename ComponentType> ComponentType const& castor::RgbColourT< ComponentType >::operator[] (RgbComponent component) const inline
Retrieves the asked PixelComponents value.
Parameters
[in] component The asked PixelComponents
Returns
The PixelComponents value
ptr()
template<typename ComponentType> float* castor::RgbColourT< ComponentType >::ptr () inline
Retrieves a pointer to the colour values.
Returns
The pointer
red() [1/2]
template<typename ComponentType> ComponentType& castor::RgbColourT< ComponentType >::red () inline
Retrieves the red PixelComponents value.
Returns
The PixelComponents value
References castor::eRed.
red() [2/2]
template<typename ComponentType> ComponentType const& castor::RgbColourT< ComponentType >::red () const inline
Retrieves the red PixelComponents value.
Returns
The PixelComponents value
References castor::eRed.
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/CastorUtilsPrerequisites.hpp
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/RgbColour.hpp