CastorUtils: castor::ArrayView< T > Class Template Reference
castor::ArrayView< T > Class Template Reference
Templated class that provide std::array style buffer view.
Public Types
using pointer = T *
using reference = T &
using const_reference = T const &
using iterator = T *
using const_iterator = T const *
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
ArrayView (pointer p_begin, pointer p_end) noexcept
template<size_t N>
ArrayView (T(&p_buffer)[N]) noexcept
ArrayView (T *p_buffer, size_t p_count) noexcept
reference operator[] (size_t p_index) noexcept
const_reference operator[] (size_t p_index) const noexcept
bool empty () const noexcept
size_t size () const noexcept
pointer data () noexcept
pointer const data () const noexcept
iterator begin () noexcept
reverse_iterator rbegin () noexcept
const_iterator begin () const noexcept
const_reverse_iterator rbegin () const noexcept
const_iterator cbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
iterator end () noexcept
reverse_iterator rend () noexcept
const_iterator end () const noexcept
const_reverse_iterator rend () const noexcept
const_iterator cend () const noexcept
const_reverse_iterator crend () const noexcept
Detailed Description
template<typename T>
class castor::ArrayView< T >
Templated class that provide std::array style buffer view.
Author
Sylvain DOREMUS
Version
0.9.0
Date
21/06/2016
Member Typedef Documentation
const_iterator
template<typename T> using castor::ArrayView< T >::const_iterator = T const *
const_reference
template<typename T> using castor::ArrayView< T >::const_reference = T const &
const_reverse_iterator
template<typename T> using castor::ArrayView< T >::const_reverse_iterator = std::reverse_iterator< const_iterator >
iterator
template<typename T> using castor::ArrayView< T >::iterator = T *
pointer
template<typename T> using castor::ArrayView< T >::pointer = T *
reference
template<typename T> using castor::ArrayView< T >::reference = T &
reverse_iterator
template<typename T> using castor::ArrayView< T >::reverse_iterator = std::reverse_iterator< iterator >
Constructor & Destructor Documentation
ArrayView() [1/3]
template<typename T> castor::ArrayView< T >::ArrayView (pointer p_begin, pointer p_end) inline noexcept
ArrayView() [2/3]
template<typename T> template<size_t N> castor::ArrayView< T >::ArrayView (T(&) p_buffer[N]) inline explicit noexcept
ArrayView() [3/3]
template<typename T> castor::ArrayView< T >::ArrayView (T * p_buffer, size_t p_count) inline noexcept
Member Function Documentation
begin() [1/2]
template<typename T> iterator castor::ArrayView< T >::begin () inline noexcept
Referenced by castor::ArrayView< T >::rend().
begin() [2/2]
template<typename T> const_iterator castor::ArrayView< T >::begin () const inline noexcept
cbegin()
template<typename T> const_iterator castor::ArrayView< T >::cbegin () const inline noexcept
Referenced by castor::ArrayView< T >::crend().
cend()
template<typename T> const_iterator castor::ArrayView< T >::cend () const inline noexcept
Referenced by castor::ArrayView< T >::crbegin().
crbegin()
template<typename T> const_reverse_iterator castor::ArrayView< T >::crbegin () const inline noexcept
References castor::ArrayView< T >::cend().
crend()
template<typename T> const_reverse_iterator castor::ArrayView< T >::crend () const inline noexcept
References castor::ArrayView< T >::cbegin().
data() [1/2]
template<typename T> pointer castor::ArrayView< T >::data () inline noexcept
data() [2/2]
template<typename T> pointer const castor::ArrayView< T >::data () const inline noexcept
empty()
template<typename T> bool castor::ArrayView< T >::empty () const inline noexcept
end() [1/2]
template<typename T> iterator castor::ArrayView< T >::end () inline noexcept
Referenced by castor::ArrayView< T >::rbegin().
end() [2/2]
template<typename T> const_iterator castor::ArrayView< T >::end () const inline noexcept
operator[]() [1/2]
template<typename T> reference castor::ArrayView< T >::operator[] (size_t p_index) inline noexcept
operator[]() [2/2]
template<typename T> const_reference castor::ArrayView< T >::operator[] (size_t p_index) const inline noexcept
rbegin() [1/2]
template<typename T> reverse_iterator castor::ArrayView< T >::rbegin () inline noexcept
References castor::ArrayView< T >::end().
rbegin() [2/2]
template<typename T> const_reverse_iterator castor::ArrayView< T >::rbegin () const inline noexcept
References castor::ArrayView< T >::end().
rend() [1/2]
template<typename T> reverse_iterator castor::ArrayView< T >::rend () inline noexcept
References castor::ArrayView< T >::begin().
rend() [2/2]
template<typename T> const_reverse_iterator castor::ArrayView< T >::rend () const inline noexcept
References castor::ArrayView< T >::begin().
size()
template<typename T> size_t castor::ArrayView< T >::size () const inline noexcept
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Design/ArrayView.hpp