CastorUtils: castor::ColourT< ComponentType > Class Template Reference
castor::ColourT< ComponentType > Class Template Reference
RGBA colour representation.
Classes
class TextLoader
ColourT text loader.
class TextWriter
ColourT text Writer.
Public Member Functions
ColourT ()
Default Constructor.
ColourT (ColourT< ComponentType > const &p_rhs)
Copy Constructor.
ColourT (ColourT< ComponentType > &&p_rhs)
Move Constructor.
ColourT< ComponentType > & operator= (ColourT< ComponentType > const &p_rhs)
Copy assignment operator.
ColourT< ComponentType > & operator= (ColourT< ComponentType > &&p_rhs)
Move assignment operator.
ColourComponentArrayIt begin ()
Retrieves an iterator to the first ColourComponent.
ColourComponentArrayConstIt begin () const
Retrieves a constant iterator to the first ColourComponent.
ColourComponentArrayIt end ()
Retrieves an iterator to beyond the last ColourComponent.
ColourComponentArrayConstIt end () const
Retrieves a constant iterator to beyond the last ColourComponent.
float const * constPtr () const
Retrieves a constant pointer to the colour values.
float * ptr ()
Retrieves a pointer to the colour values.
ComponentType & operator[] (Component p_eComponent)
Retrieves the asked PixelComponents value.
ComponentType const & operator[] (Component p_eComponent) const
Retrieves the asked PixelComponents value.
ComponentType & get (Component p_eComponent)
Retrieves the asked PixelComponents value.
ComponentType const & get (Component p_eComponent) const
Retrieves the asked PixelComponents value.
ComponentType & red ()
Retrieves the red PixelComponents value.
ComponentType const & red () const
Retrieves the red PixelComponents value.
ComponentType & green ()
Retrieves the green PixelComponents value.
ComponentType const & green () const
Retrieves the green PixelComponents value.
ComponentType & blue ()
Retrieves the blue PixelComponents value.
ComponentType const & blue () const
Retrieves the blue PixelComponents value.
ComponentType & alpha ()
Retrieves the alpha PixelComponents value.
ComponentType const & alpha () const
Retrieves the alpha PixelComponents value.
ColourT< ComponentType > & operator+= (ColourT const &p_clrB)
addition assignment operator
ColourT< ComponentType > & operator-= (ColourT const &p_clrB)
Substraction assignment operator.
template<typename T >
ColourT< ComponentType > & operator+= (T p_scalar)
addition assignment operator
template<typename T >
ColourT< ComponentType > & operator-= (T p_scalar)
Substraction assignment operator.
template<typename T >
ColourT< ComponentType > & operator*= (T p_scalar)
Multiplication assignment operator.
template<typename T >
ColourT< ComponentType > & operator/= (T p_scalar)
Division assignment operator.
ColourT< ComponentType > & operator+= (ComponentType const &p_component)
addition assignment operator
ColourT< ComponentType > & operator-= (ComponentType const &p_component)
Substraction assignment operator.
ColourT< ComponentType > & operator*= (ComponentType const &p_component)
Multiplication assignment operator.
ColourT< ComponentType > & operator/= (ComponentType const &p_component)
Division assignment operator.
Static Public Member Functions
template<typename T1 , typename T2 , typename T3 , typename T4 >
static ColourT< ComponentType > fromComponents (T1 const &p_r, T2 const &p_g, T3 const &p_b, T4 const &p_a)
Constructor from components.
static ColourT< ComponentType > fromPredefined (PredefinedColour p_ePredef)
Constructor from a predefined colour.
static ColourT< ComponentType > fromRGB (Point3ub const &p_ptColour)
Constructor from a point representing RGB components.
static ColourT< ComponentType > fromBGR (Point3ub const &p_ptColour)
Constructor from a point representing BGR components.
static ColourT< ComponentType > fromRGBA (Point4ub const &p_ptColour)
Constructor from a point representing RGBA components.
static ColourT< ComponentType > fromBGRA (Point4ub const &p_ptColour)
Constructor from a point representing BGRA components.
static ColourT< ComponentType > fromARGB (Point4ub const &p_ptColour)
Constructor from a point representing ARGB components.
static ColourT< ComponentType > fromABGR (Point4ub const &p_ptColour)
Constructor from a point representing ABGR components.
static ColourT< ComponentType > fromRGB (Point3f const &p_ptColour)
Constructor from a point representing RGB components.
static ColourT< ComponentType > fromBGR (Point3f const &p_ptColour)
Constructor from a point representing BGR components.
static ColourT< ComponentType > fromRGBA (Point4f const &p_ptColour)
Constructor from a point representing RGBA components.
static ColourT< ComponentType > fromARGB (Point4f const &p_ptColour)
Constructor from a point representing ARGB components.
static ColourT< ComponentType > fromABGR (Point4f const &p_ptColour)
Constructor from a point representing ABGR components.
static ColourT< ComponentType > fromBGRA (Point4f const &p_ptColour)
Constructor from a point representing BGRA components.
static ColourT< ComponentType > fromRGB (uint8_t const(&p_ptColour)[3])
Constructor from a point representing RGB components.
static ColourT< ComponentType > fromBGR (uint8_t const(&p_ptColour)[3])
Constructor from a point representing BGR components.
static ColourT< ComponentType > fromRGBA (uint8_t const(&p_ptColour)[4])
Constructor from a point representing RGBA components.
static ColourT< ComponentType > fromBGRA (uint8_t const(&p_ptColour)[4])
Constructor from a point representing BGRA components.
static ColourT< ComponentType > fromARGB (uint8_t const(&p_ptColour)[4])
Constructor from a point representing ARGB components.
static ColourT< ComponentType > fromABGR (uint8_t const(&p_ptColour)[4])
Constructor from a point representing ABGR components.
static ColourT< ComponentType > fromRGB (float const(&p_ptColour)[3])
Constructor from a point representing RGB components.
static ColourT< ComponentType > fromBGR (float const(&p_ptColour)[3])
Constructor from a point representing BGR components.
static ColourT< ComponentType > fromRGBA (float const(&p_ptColour)[4])
Constructor from a point representing RGBA components.
static ColourT< ComponentType > fromARGB (float const(&p_ptColour)[4])
Constructor from a point representing ARGB components.
static ColourT< ComponentType > fromABGR (float const(&p_ptColour)[4])
Constructor from a point representing ABGR components.
static ColourT< ComponentType > fromBGRA (float const(&p_ptColour)[4])
Constructor from a point representing BGRA components.
static ColourT< ComponentType > fromRGB (uint32_t p_colour)
Constructor from an uint32_t representing RGB components.
static ColourT< ComponentType > fromBGR (uint32_t p_colour)
Constructor from an uint32_t representing BGR components.
static ColourT< ComponentType > fromARGB (uint32_t p_colour)
Constructor from an uint32_t representing ARGB components.
static ColourT< ComponentType > fromRGBA (uint32_t p_colour)
Constructor from an uint32_t representing RGBA components.
static ColourT< ComponentType > fromABGR (uint32_t p_colour)
Constructor from an uint32_t representing ABGR components.
static ColourT< ComponentType > fromBGRA (uint32_t p_colour)
Constructor from an uint32_t representing BGRA components.
Detailed Description
template<typename ComponentType>
class castor::ColourT< ComponentType >
RGBA colour representation.
Author
Sylvain DOREMUS
Date
14/08/2010
Remarks
Predefines numerous colours
Allows conversion to different colour formats (RGB, ARGB, BGR, ...) and different data types (long, float, char, ...)
Constructor & Destructor Documentation
ColourT() [1/3]
template<typename ComponentType> castor::ColourT< ComponentType >::ColourT () inline
Default Constructor.
ColourT() [2/3]
template<typename ComponentType> castor::ColourT< ComponentType >::ColourT (ColourT< ComponentType > const & p_rhs) inline
Copy Constructor.
Parameters
[in] p_rhs The object to copy
ColourT() [3/3]
template<typename ComponentType> castor::ColourT< ComponentType >::ColourT (ColourT< ComponentType > && p_rhs) inline
Move Constructor.
Parameters
[in] p_rhs The object to move
Member Function Documentation
alpha() [1/2]
template<typename ComponentType> ComponentType& castor::ColourT< ComponentType >::alpha () inline
Retrieves the alpha PixelComponents value.
Returns
The PixelComponents value
References castor::eAlpha.
alpha() [2/2]
template<typename ComponentType> ComponentType const& castor::ColourT< ComponentType >::alpha () const inline
Retrieves the alpha PixelComponents value.
Returns
The PixelComponents value
References castor::eAlpha.
begin() [1/2]
template<typename ComponentType> ColourComponentArrayIt castor::ColourT< ComponentType >::begin () inline
Retrieves an iterator to the first ColourComponent.
Returns
The iterator
begin() [2/2]
template<typename ComponentType> ColourComponentArrayConstIt castor::ColourT< ComponentType >::begin () const inline
Retrieves a constant iterator to the first ColourComponent.
Returns
The iterator
blue() [1/2]
template<typename ComponentType> ComponentType& castor::ColourT< ComponentType >::blue () inline
Retrieves the blue PixelComponents value.
Returns
The PixelComponents value
References castor::eBlue.
blue() [2/2]
template<typename ComponentType> ComponentType const& castor::ColourT< ComponentType >::blue () const inline
Retrieves the blue PixelComponents value.
Returns
The PixelComponents value
References castor::eBlue.
constPtr()
template<typename ComponentType> float const* castor::ColourT< ComponentType >::constPtr () const inline
Retrieves a constant pointer to the colour values.
Returns
The pointer
end() [1/2]
template<typename ComponentType> ColourComponentArrayIt castor::ColourT< ComponentType >::end () inline
Retrieves an iterator to beyond the last ColourComponent.
Returns
The iterator
end() [2/2]
template<typename ComponentType> ColourComponentArrayConstIt castor::ColourT< ComponentType >::end () const inline
Retrieves a constant iterator to beyond the last ColourComponent.
Returns
The iterator
fromABGR() [1/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromABGR (Point4ub const & p_ptColour) inline static
Constructor from a point representing ABGR components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromABGR() [2/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromABGR (Point4f const & p_ptColour) inline static
Constructor from a point representing ABGR components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromABGR() [3/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromABGR (uint8_t const(&) p_ptColour[4]) inline static
Constructor from a point representing ABGR components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromABGR() [4/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromABGR (float const(&) p_ptColour[4]) inline static
Constructor from a point representing ABGR components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromABGR() [5/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromABGR (uint32_t p_colour) inline static
Constructor from an uint32_t representing ABGR components.
Parameters
[in] p_colour The uint32_t containing the colour (0xAABBGGRR)
Returns
The built ColourT
fromARGB() [1/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromARGB (Point4ub const & p_ptColour) inline static
Constructor from a point representing ARGB components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromARGB() [2/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromARGB (Point4f const & p_ptColour) inline static
Constructor from a point representing ARGB components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromARGB() [3/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromARGB (uint8_t const(&) p_ptColour[4]) inline static
Constructor from a point representing ARGB components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromARGB() [4/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromARGB (float const(&) p_ptColour[4]) inline static
Constructor from a point representing ARGB components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromARGB() [5/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromARGB (uint32_t p_colour) inline static
Constructor from an uint32_t representing ARGB components.
Parameters
[in] p_colour The uint32_t containing the colour (0xAARRGGBB)
Returns
The built ColourT
fromBGR() [1/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGR (Point3ub const & p_ptColour) inline static
Constructor from a point representing BGR components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromBGR() [2/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGR (Point3f const & p_ptColour) inline static
Constructor from a point representing BGR components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromBGR() [3/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGR (uint8_t const(&) p_ptColour[3]) inline static
Constructor from a point representing BGR components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromBGR() [4/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGR (float const(&) p_ptColour[3]) inline static
Constructor from a point representing BGR components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromBGR() [5/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGR (uint32_t p_colour) inline static
Constructor from an uint32_t representing BGR components.
Parameters
[in] p_colour The uint32_t containing the colour (0x00BBGGRR)
Returns
The built ColourT
fromBGRA() [1/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGRA (Point4ub const & p_ptColour) inline static
Constructor from a point representing BGRA components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromBGRA() [2/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGRA (Point4f const & p_ptColour) inline static
Constructor from a point representing BGRA components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromBGRA() [3/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGRA (uint8_t const(&) p_ptColour[4]) inline static
Constructor from a point representing BGRA components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromBGRA() [4/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGRA (float const(&) p_ptColour[4]) inline static
Constructor from a point representing BGRA components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromBGRA() [5/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromBGRA (uint32_t p_colour) inline static
Constructor from an uint32_t representing BGRA components.
Parameters
[in] p_colour The uint32_t containing the colour (0xBBGGRRAA)
Returns
The built ColourT
fromComponents()
template<typename ComponentType> template<typename T1 , typename T2 , typename T3 , typename T4 > static ColourT< ComponentType > castor::ColourT< ComponentType >::fromComponents (T1 const & p_r, T2 const & p_g, T3 const & p_b, T4 const & p_a) inline static
Constructor from components.
Parameters
[in] p_r,p_g,p_b,p_a The colour components
Returns
The built ColourT
References castor::eAlpha, castor::eBlue, castor::eGreen, and castor::eRed.
fromPredefined()
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromPredefined (PredefinedColour p_ePredef) inline static
Constructor from a predefined colour.
Parameters
[in] p_ePredef
Returns
The built ColourT
fromRGB() [1/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGB (Point3ub const & p_ptColour) inline static
Constructor from a point representing RGB components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromRGB() [2/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGB (Point3f const & p_ptColour) inline static
Constructor from a point representing RGB components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromRGB() [3/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGB (uint8_t const(&) p_ptColour[3]) inline static
Constructor from a point representing RGB components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromRGB() [4/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGB (float const(&) p_ptColour[3]) inline static
Constructor from a point representing RGB components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromRGB() [5/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGB (uint32_t p_colour) inline static
Constructor from an uint32_t representing RGB components.
Parameters
[in] p_colour The uint32_t containing the colour (0x00RRGGBB)
Returns
The built ColourT
fromRGBA() [1/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGBA (Point4ub const & p_ptColour) inline static
Constructor from a point representing RGBA components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromRGBA() [2/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGBA (Point4f const & p_ptColour) inline static
Constructor from a point representing RGBA components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromRGBA() [3/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGBA (uint8_t const(&) p_ptColour[4]) inline static
Constructor from a point representing RGBA components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromRGBA() [4/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGBA (float const(&) p_ptColour[4]) inline static
Constructor from a point representing RGBA components.
Parameters
[in] p_ptColour The point containing the colour components
Returns
The built ColourT
fromRGBA() [5/5]
template<typename ComponentType> static ColourT< ComponentType > castor::ColourT< ComponentType >::fromRGBA (uint32_t p_colour) inline static
Constructor from an uint32_t representing RGBA components.
Parameters
[in] p_colour The uint32_t containing the colour (0xRRGGBBAA)
Returns
The built ColourT
get() [1/2]
template<typename ComponentType> ComponentType& castor::ColourT< ComponentType >::get (Component p_eComponent) inline
Retrieves the asked PixelComponents value.
Parameters
[in] p_eComponent The asked PixelComponents
Returns
The PixelComponents value
get() [2/2]
template<typename ComponentType> ComponentType const& castor::ColourT< ComponentType >::get (Component p_eComponent) const inline
Retrieves the asked PixelComponents value.
Parameters
[in] p_eComponent The asked PixelComponents
Returns
The PixelComponents value
green() [1/2]
template<typename ComponentType> ComponentType& castor::ColourT< ComponentType >::green () inline
Retrieves the green PixelComponents value.
Returns
The PixelComponents value
References castor::eGreen.
green() [2/2]
template<typename ComponentType> ComponentType const& castor::ColourT< ComponentType >::green () const inline
Retrieves the green PixelComponents value.
Returns
The PixelComponents value
References castor::eGreen.
operator*=() [1/2]
template<typename ComponentType> template<typename T > ColourT< ComponentType >& castor::ColourT< ComponentType >::operator*= (T p_scalar) inline
Multiplication assignment operator.
Parameters
[in] p_scalar The value to multiply
Returns
Result of this * p_scalar
References castor::eCount, and castor::details::i.
operator*=() [2/2]
template<typename ComponentType> ColourT< ComponentType >& castor::ColourT< ComponentType >::operator*= (ComponentType const & p_component) inline
Multiplication assignment operator.
Parameters
[in] p_component The value to multiply
Returns
Result of this * p_component
operator+=() [1/3]
template<typename ComponentType> ColourT< ComponentType >& castor::ColourT< ComponentType >::operator+= (ColourT< ComponentType > const & p_clrB) inline
addition assignment operator
Parameters
[in] p_clrB The colours to add
Returns
Result of this + p_clrB
operator+=() [2/3]
template<typename ComponentType> template<typename T > ColourT< ComponentType >& castor::ColourT< ComponentType >::operator+= (T p_scalar) inline
addition assignment operator
Parameters
[in] p_scalar The value to add
Returns
Result of this + p_scalar
References castor::eCount, and castor::details::i.
operator+=() [3/3]
template<typename ComponentType> ColourT< ComponentType >& castor::ColourT< ComponentType >::operator+= (ComponentType const & p_component) inline
addition assignment operator
Parameters
[in] p_component The value to add
Returns
Result of this + p_component
operator-=() [1/3]
template<typename ComponentType> ColourT< ComponentType >& castor::ColourT< ComponentType >::operator-= (ColourT< ComponentType > const & p_clrB) inline
Substraction assignment operator.
Parameters
[in] p_clrB The colours to subtract
Returns
Result of this - p_clrB
operator-=() [2/3]
template<typename ComponentType> template<typename T > ColourT< ComponentType >& castor::ColourT< ComponentType >::operator-= (T p_scalar) inline
Substraction assignment operator.
Parameters
[in] p_scalar The value to subtract
Returns
Result of this - p_scalar
References castor::eCount, and castor::details::i.
operator-=() [3/3]
template<typename ComponentType> ColourT< ComponentType >& castor::ColourT< ComponentType >::operator-= (ComponentType const & p_component) inline
Substraction assignment operator.
Parameters
[in] p_component The value to subtract
Returns
Result of this - p_component
operator/=() [1/2]
template<typename ComponentType> template<typename T > ColourT< ComponentType >& castor::ColourT< ComponentType >::operator/= (T p_scalar) inline
Division assignment operator.
Parameters
[in] p_scalar The value to divide
Returns
Result of this / p_scalar
References castor::eCount, castor::details::i, castor::operator!=(), castor::operator+(), castor::operator-(), and castor::operator==().
operator/=() [2/2]
template<typename ComponentType> ColourT< ComponentType >& castor::ColourT< ComponentType >::operator/= (ComponentType const & p_component) inline
Division assignment operator.
Parameters
[in] p_component The value to divide
Returns
Result of this / p_component
operator=() [1/2]
template<typename ComponentType> ColourT< ComponentType >& castor::ColourT< ComponentType >::operator= (ColourT< ComponentType > const & p_rhs) inline
Copy assignment operator.
Parameters
[in] p_rhs The object to copy
Returns
A reference to this object
operator=() [2/2]
template<typename ComponentType> ColourT< ComponentType >& castor::ColourT< ComponentType >::operator= (ColourT< ComponentType > && p_rhs) inline
Move assignment operator.
Parameters
[in] p_rhs The object to copy
Returns
Reference to this colour
operator[]() [1/2]
template<typename ComponentType> ComponentType& castor::ColourT< ComponentType >::operator[] (Component p_eComponent) inline
Retrieves the asked PixelComponents value.
Parameters
[in] p_eComponent The asked PixelComponents
Returns
The PixelComponents value
operator[]() [2/2]
template<typename ComponentType> ComponentType const& castor::ColourT< ComponentType >::operator[] (Component p_eComponent) const inline
Retrieves the asked PixelComponents value.
Parameters
[in] p_eComponent The asked PixelComponents
Returns
The PixelComponents value
ptr()
template<typename ComponentType> float* castor::ColourT< ComponentType >::ptr () inline
Retrieves a pointer to the colour values.
Returns
The pointer
red() [1/2]
template<typename ComponentType> ComponentType& castor::ColourT< ComponentType >::red () inline
Retrieves the red PixelComponents value.
Returns
The PixelComponents value
References castor::eRed.
red() [2/2]
template<typename ComponentType> ComponentType const& castor::ColourT< ComponentType >::red () const inline
Retrieves the red PixelComponents value.
Returns
The PixelComponents value
References castor::eRed.
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/CastorUtilsPrerequisites.hpp
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/Colour.hpp