Castor3D: castor3d::AnimatedObject Class Reference
castor3d::AnimatedObject Class Reference abstract
Represents the animated objects.
Public Member Functions
C3D_API AnimatedObject (castor::String const &p_name)
Constructor.
C3D_API ~AnimatedObject ()
Destructor.
C3D_API AnimatedObject (AnimatedObject &&p_rhs)=default
Move constructor.
C3D_API AnimatedObject & operator= (AnimatedObject &&p_rhs)=default
Move assignment operator.
C3D_API AnimatedObject (AnimatedObject const &p_rhs)=delete
Copy constructor.
C3D_API AnimatedObject & operator= (AnimatedObject const &p_rhs)=delete
Copy assignment operator.
C3D_API void addAnimation (castor::String const &p_name)
adds the animation to the list
C3D_API void startAnimation (castor::String const &p_name)
Starts the animation identified by the given name.
C3D_API void stopAnimation (castor::String const &p_name)
Stops the animation identified by the given name.
C3D_API void pauseAnimation (castor::String const &p_name)
Pauses the animation identified by the given name.
C3D_API void startAllAnimations ()
Starts all animations.
C3D_API void stopAllAnimations ()
Stops all animations.
C3D_API void pauseAllAnimations ()
Pauses all animations.
C3D_API bool hasAnimation (castor::String const &p_name)
Checks if an animation with given name exists.
C3D_API AnimationInstance & getAnimation (castor::String const &p_name)
Retrieves an animation.
virtual C3D_API void update (castor::Milliseconds const &p_tslf)=0
Updates the animations of the object, given the time since the last frame.
virtual C3D_API bool isPlayingAnimation () const =0
AnimationInstancePtrStrMap const & getAnimations () const
Protected Attributes
AnimationInstancePtrStrMap m_animations
Detailed Description
Represents the animated objects.
Author
Sylvain DOREMUS
Version
0.7.0
Date
10/12/2013
Constructor & Destructor Documentation
AnimatedObject() [1/3]
C3D_API castor3d::AnimatedObject::AnimatedObject (castor::String const & p_name) explicit
Constructor.
Parameters
[in] p_name The object name
~AnimatedObject()
C3D_API castor3d::AnimatedObject::~AnimatedObject ()
Destructor.
AnimatedObject() [2/3]
C3D_API castor3d::AnimatedObject::AnimatedObject (AnimatedObject && p_rhs) default
Move constructor.
AnimatedObject() [3/3]
C3D_API castor3d::AnimatedObject::AnimatedObject (AnimatedObject const & p_rhs) delete
Copy constructor.
Member Function Documentation
addAnimation()
C3D_API void castor3d::AnimatedObject::addAnimation (castor::String const & p_name)
adds the animation to the list
Parameters
[in] p_name The animation to add
Ajoute une animation à la liste
Parameters
[in] p_name L'animation à ajouter
getAnimation()
C3D_API AnimationInstance& castor3d::AnimatedObject::getAnimation (castor::String const & p_name)
Retrieves an animation.
Parameters
[in] p_name The animation name
Returns
The animation
Referenced by hasAnimation().
getAnimations()
AnimationInstancePtrStrMap const& castor3d::AnimatedObject::getAnimations () const inline
Returns
The animations for this object.
References m_animations.
hasAnimation()
C3D_API bool castor3d::AnimatedObject::hasAnimation (castor::String const & p_name) inline
Checks if an animation with given name exists.
Parameters
[in] p_name The animation name.
References C3D_API, getAnimation(), isPlayingAnimation(), m_animations, and update().
isPlayingAnimation()
virtual C3D_API bool castor3d::AnimatedObject::isPlayingAnimation () const pure virtual
Returns
true if the object is playing an animation.
Implemented in castor3d::AnimatedSkeleton, and castor3d::AnimatedMesh.
Referenced by hasAnimation().
operator=() [1/2]
C3D_API AnimatedObject& castor3d::AnimatedObject::operator= (AnimatedObject && p_rhs) default
Move assignment operator.
operator=() [2/2]
C3D_API AnimatedObject& castor3d::AnimatedObject::operator= (AnimatedObject const & p_rhs) delete
Copy assignment operator.
pauseAllAnimations()
C3D_API void castor3d::AnimatedObject::pauseAllAnimations ()
Pauses all animations.
pauseAnimation()
C3D_API void castor3d::AnimatedObject::pauseAnimation (castor::String const & p_name)
Pauses the animation identified by the given name.
Parameters
[in] p_name The name of the animation
startAllAnimations()
C3D_API void castor3d::AnimatedObject::startAllAnimations ()
Starts all animations.
startAnimation()
C3D_API void castor3d::AnimatedObject::startAnimation (castor::String const & p_name)
Starts the animation identified by the given name.
Parameters
[in] p_name The name of the animation
stopAllAnimations()
C3D_API void castor3d::AnimatedObject::stopAllAnimations ()
Stops all animations.
stopAnimation()
C3D_API void castor3d::AnimatedObject::stopAnimation (castor::String const & p_name)
Stops the animation identified by the given name.
Parameters
[in] p_name The name of the animation
update()
virtual C3D_API void castor3d::AnimatedObject::update (castor::Milliseconds const & p_tslf) pure virtual
Updates the animations of the object, given the time since the last frame.
Parameters
[in] p_tslf Time elapsed since the last frame
Implemented in castor3d::AnimatedSkeleton, and castor3d::AnimatedMesh.
Referenced by hasAnimation().
Member Data Documentation
m_animations
AnimationInstancePtrStrMap castor3d::AnimatedObject::m_animations protected
All animations.
Referenced by getAnimations(), and hasAnimation().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Scene/Animation/AnimatedObject.hpp