CastorUtils: castor::Image Class Reference
castor::Image Class Reference
Image resource.
Classes
class BinaryLoader
Image resource loader.
class BinaryWriter
Image resource loader.
Public Member Functions
CU_API Image (String const &name, Size const &size, PixelFormat format, ByteArray const &buffer, PixelFormat bufferFormat)
Creates the image with given params.
CU_API Image (String const &name, Size const &size, PixelFormat format=PixelFormat::eA8R8G8B8, uint8_t const *buffer=nullptr, PixelFormat bufferFormat=PixelFormat::eA8R8G8B8)
Creates the image with given params.
CU_API Image (String const &name, PxBufferBase const &buffer)
Creates the image with given params.
template<PixelFormat PFSrc, PixelFormat PFDst>
Image (String const &name, Size const &size, uint8_t const *buffer=nullptr)
Creates the image with given params.
CU_API Image (String const &name, Path const &pathFile)
Creates the image from a file.
CU_API Image (Image const &image)
Copy Constructor.
CU_API Image (Image &&image)
Move Constructor.
CU_API Image & operator= (Image const &image)
Copy assignment operator.
CU_API Image & operator= (Image &&image)
Move assignment operator.
CU_API ~Image ()
Destructor.
CU_API Image & resample (Size const &size)
Resizes the image to the given resolution.
CU_API Image & fill (RgbColour const &colour)
Fills all image pixels with the given colour.
CU_API Image & fill (RgbaColour const &colour)
Fills all image pixels with the given colour.
CU_API Image & setPixel (uint32_t x, uint32_t y, uint8_t const *pixel, PixelFormat format)
Fills the wanted pixel with the given buffer.
CU_API Image & setPixel (uint32_t x, uint32_t y, RgbColour const &colour)
sets the colour of the wanted pixel to the given one
CU_API Image & setPixel (uint32_t x, uint32_t y, RgbaColour const &colour)
sets the colour of the wanted pixel to the given one
template<PixelFormat PF>
Image & setPixel (uint32_t x, uint32_t y, Pixel< PF > const &pixel)
set the wanted pixel to the given pixel
template<PixelFormat PF>
void getPixel (uint32_t x, uint32_t y, Pixel< PF > &pixel) const
Retrieves the pixel at given coordinates.
CU_API void getPixel (uint32_t x, uint32_t y, uint8_t *pixel, PixelFormat format) const
Retrieves the wanted pixel and puts it in the buffer to the given format.
CU_API RgbaColour getPixel (uint32_t x, uint32_t y) const
Retrieves the pixel colour.
CU_API Image & copyImage (Image const &src)
Copies the given image into this one.
CU_API Image subImage (Rectangle const &rect) const
Gives the sub-image contained in the given rectangle.
CU_API Image & flip ()
Swaps the image lines.
CU_API Image & mirror ()
Swaps the image columns.
Size const & getDimensions () const
Retrieves the image dimensions.
std::size_t getSize () const
Retrieves the image data length.
uint32_t getWidth () const
Retrieves the image width.
uint32_t getHeight () const
Retrieves the image height.
Path getPath () const
Retrieves the image path.
uint8_t * getBuffer ()
Retrieves the image data.
uint8_t const * getBuffer () const
Retrieves the image data.
PxBufferBaseSPtr getPixels ()
Retrieves the image data.
PxBufferBaseSPtr getPixels () const
Retrieves the image data.
PixelFormat getPixelFormat () const
Retrieves the image pixel format.
Public Member Functions inherited from castor::Resource< Image >
Resource (Resource const &p_other)
Copy Constructor.
Resource (Resource &&p_other)
Move Constructor.
Resource & operator= (Resource const &p_other)
Copy assignment operator.
Resource & operator= (Resource &&p_other)
Move assignment operator.
void changeName (String const &p_name)
Defines the resource name.
Public Member Functions inherited from castor::NamedBase< T >
NamedBase (T const &p_name)
Constructor.
NamedBase (NamedBase const &p_named)=default
Copy Constructor.
NamedBase (NamedBase &&p_named)=default
Move Constructor.
~NamedBase ()=default
Destructor.
NamedBase & operator= (NamedBase const &p_named)=default
Copy Constructor.
NamedBase & operator= (NamedBase &&p_named)=default
Move Constructor.
T const & getName () const
Retrieves the name.
void setName (T const &p_name)
sets the name
Static Public Member Functions
static CU_API void initialiseImageLib ()
Initialises the image loading library.
static CU_API void cleanupImageLib ()
Cleans up the image loading library.
Friends
class Font
class Image::BinaryLoader
Additional Inherited Members
Protected Types inherited from castor::Resource< Image >
typedef Collection< Image, String > collection
Protected Member Functions inherited from castor::Resource< Image >
Resource (String const &p_name)
Constructor.
~Resource ()
Destructor.
Protected Attributes inherited from castor::NamedBase< T >
T m_name
Detailed Description
Image resource.
Author
Sylvain DOREMUS
Date
14/02/2010
Constructor & Destructor Documentation
Image() [1/7]
CU_API castor::Image::Image (String const & name, Size const & size, PixelFormat format, ByteArray const & buffer, PixelFormat bufferFormat)
Creates the image with given params.
Parameters
[in] name The resource name
[in] size The wanted image dimensions
[in] format The wanted image pixel format
[in] buffer A buffer containing pixels
[in] bufferFormat The buffer pixel format
Referenced by Image().
Image() [2/7]
CU_API castor::Image::Image (String const & name, Size const & size, PixelFormat format = PixelFormat::eA8R8G8B8, uint8_t const * buffer = nullptr, PixelFormat bufferFormat = PixelFormat::eA8R8G8B8)
Creates the image with given params.
Parameters
[in] name The resource name
[in] size The wanted image dimensions
[in] format The wanted image pixel format
[in] buffer A buffer containing pixels
[in] bufferFormat The buffer pixel format
Image() [3/7]
CU_API castor::Image::Image (String const & name, PxBufferBase const & buffer)
Creates the image with given params.
Parameters
[in] name The resource name
[in] buffer A buffer containing pixels
Image() [4/7]
template<PixelFormat PFSrc, PixelFormat PFDst> castor::Image::Image (String const & name, Size const & size, uint8_t const * buffer = nullptr) inline
Creates the image with given params.
Remarks
The wanted pixel format and buffer pixel format are the template params
Parameters
[in] name The resource name
[in] size The wanted image dimensions
[in] buffer A buffer containing pixels
References CHECK_INVARIANTS, CU_API, fill(), Image(), resample(), setPixel(), and ~Image().
Image() [5/7]
CU_API castor::Image::Image (String const & name, Path const & pathFile)
Creates the image from a file.
Parameters
[in] name The resource name
[in] pathFile The file path
Image() [6/7]
CU_API castor::Image::Image (Image const & image)
Copy Constructor.
Parameters
[in] image The Image object to copy
Image() [7/7]
CU_API castor::Image::Image (Image && image)
Move Constructor.
Parameters
[in] image The Image object to move
~Image()
CU_API castor::Image::~Image ()
Destructor.
Referenced by Image().
Member Function Documentation
cleanupImageLib()
static CU_API void castor::Image::cleanupImageLib () static
Cleans up the image loading library.
Referenced by getPixel().
copyImage()
CU_API Image& castor::Image::copyImage (Image const & src)
Copies the given image into this one.
Parameters
[in] src The image to copy
Returns
A reference to the image
Referenced by getPixel().
fill() [1/2]
CU_API Image& castor::Image::fill (RgbColour const & colour)
Fills all image pixels with the given colour.
Parameters
[in] colour The fill colour
Returns
A reference to the image
Referenced by Image().
fill() [2/2]
CU_API Image& castor::Image::fill (RgbaColour const & colour)
Fills all image pixels with the given colour.
Parameters
[in] colour The fill colour
Returns
A reference to the image
flip()
CU_API Image& castor::Image::flip ()
Swaps the image lines.
Returns
A reference to the image
Referenced by getPixel().
getBuffer() [1/2]
uint8_t* castor::Image::getBuffer () inline
Retrieves the image data.
Returns
The image data
getBuffer() [2/2]
uint8_t const* castor::Image::getBuffer () const inline
Retrieves the image data.
Returns
The image data
getDimensions()
Size const& castor::Image::getDimensions () const inline
Retrieves the image dimensions.
Returns
The image dimensions
getHeight()
uint32_t castor::Image::getHeight () const inline
Retrieves the image height.
Returns
The image height
Referenced by getPixel(), and setPixel().
getPath()
Path castor::Image::getPath () const inline
Retrieves the image path.
Returns
The image path
getPixel() [1/3]
template<PixelFormat PF> void castor::Image::getPixel (uint32_t x, uint32_t y, Pixel< PF > & pixel) const inline
Retrieves the pixel at given coordinates.
Parameters
[in] x,y The pixel coordinates
[out] pixel Receives the pixel
References CHECK_INVARIANTS, cleanupImageLib(), castor::PF::convertPixel(), copyImage(), CU_API, flip(), getHeight(), getPixelFormat(), getWidth(), initialiseImageLib(), mirror(), castor::Pixel< FT >::ptr(), REQUIRE, and subImage().
getPixel() [2/3]
CU_API void castor::Image::getPixel (uint32_t x, uint32_t y, uint8_t * pixel, PixelFormat format) const
Retrieves the wanted pixel and puts it in the buffer to the given format.
Parameters
[in] x,y The pixel coordinates
[out] pixel Receives the pixel in given format
[in] format The wanted format for the pixel buffer
getPixel() [3/3]
CU_API RgbaColour castor::Image::getPixel (uint32_t x, uint32_t y) const
Retrieves the pixel colour.
Parameters
[in] x,y The pixel coordinates
Returns
The pixel colour
getPixelFormat()
PixelFormat castor::Image::getPixelFormat () const inline
Retrieves the image pixel format.
Returns
The image pixel format
Referenced by getPixel(), and setPixel().
getPixels() [1/2]
PxBufferBaseSPtr castor::Image::getPixels () inline
Retrieves the image data.
Returns
The image data
getPixels() [2/2]
PxBufferBaseSPtr castor::Image::getPixels () const inline
Retrieves the image data.
Returns
The image data
getSize()
std::size_t castor::Image::getSize () const inline
Retrieves the image data length.
Returns
The image data length
getWidth()
uint32_t castor::Image::getWidth () const inline
Retrieves the image width.
Returns
The image width
Referenced by getPixel(), and setPixel().
initialiseImageLib()
static CU_API void castor::Image::initialiseImageLib () static
Initialises the image loading library.
Referenced by getPixel().
mirror()
CU_API Image& castor::Image::mirror ()
Swaps the image columns.
Returns
A reference to the image
Referenced by getPixel().
operator=() [1/2]
CU_API Image& castor::Image::operator= (Image const & image)
Copy assignment operator.
Parameters
[in] image The Image object to copy
Returns
A reference to this Image object
operator=() [2/2]
CU_API Image& castor::Image::operator= (Image && image)
Move assignment operator.
Parameters
[in] image The Image object to move
Returns
A reference to this Image object
resample()
CU_API Image& castor::Image::resample (Size const & size)
Resizes the image to the given resolution.
Parameters
[in] size The new resolution
Returns
A reference to the image
Referenced by Image().
setPixel() [1/4]
CU_API Image& castor::Image::setPixel (uint32_t x, uint32_t y, uint8_t const * pixel, PixelFormat format)
Fills the wanted pixel with the given buffer.
Parameters
[in] x,y The pixel coordinates
[in] pixel The buffer
[in] format The buffer's pixel format
Returns
A reference to the image
Referenced by Image().
setPixel() [2/4]
CU_API Image& castor::Image::setPixel (uint32_t x, uint32_t y, RgbColour const & colour)
sets the colour of the wanted pixel to the given one
Parameters
[in] x,y The pixel coordinates
[in] colour The colour
Returns
A reference to the image
setPixel() [3/4]
CU_API Image& castor::Image::setPixel (uint32_t x, uint32_t y, RgbaColour const & colour)
sets the colour of the wanted pixel to the given one
Parameters
[in] x,y The pixel coordinates
[in] colour The colour
Returns
A reference to the image
setPixel() [4/4]
template<PixelFormat PF> Image& castor::Image::setPixel (uint32_t x, uint32_t y, Pixel< PF > const & pixel) inline
set the wanted pixel to the given pixel
Parameters
[in] x,y The pixel coordinates
[in] pixel The pixel
Returns
A reference to the image
References CHECK_INVARIANTS, castor::Pixel< FT >::constPtr(), castor::PF::convertPixel(), getHeight(), getPixelFormat(), getWidth(), and REQUIRE.
subImage()
CU_API Image castor::Image::subImage (Rectangle const & rect) const
Gives the sub-image contained in the given rectangle.
Parameters
[in] rect The sub-image rectangle
Returns
The sub-image
Referenced by getPixel().
Friends And Related Function Documentation
Font
friend class Font friend
Image::BinaryLoader
friend class Image::BinaryLoader friend
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/Image.hpp