Castor3D: castor3d::Geometry Class Reference
castor3d::Geometry Class Reference
Geometry handler class.
Classes
class TextWriter
Geometry loader.
Public Member Functions
C3D_API Geometry (castor::String const &name, Scene &scene, SceneNodeSPtr node, MeshSPtr mesh=nullptr)
Constructor.
virtual C3D_API ~Geometry ()
Destructor.
C3D_API void cleanup ()
Cleans all the object owned and created by the geometry.
C3D_API void createBuffers (uint32_t &nbFaces, uint32_t &nbVertex)
virtual C3D_API void render ()
Renders the geometry in a given display mode.
virtual C3D_API void endRender ()
End render function, dummy.
C3D_API void setMesh (MeshSPtr mesh)
Defines this geometry's mesh.
C3D_API MaterialSPtr getMaterial (Submesh const &submesh) const
Retrieves the submesh material.
C3D_API void setMaterial (Submesh &submesh, MaterialSPtr material, bool updateSubmesh=true)
Defines a submesh material.
MeshSPtr getMesh () const
Retrieves the mesh.
Public Member Functions inherited from castor3d::MovableObject
C3D_API MovableObject (castor::String const &p_name, Scene &p_scene, MovableType p_type, SceneNodeSPtr p_sn)
Constructor.
virtual C3D_API ~MovableObject ()
Destructor.
C3D_API void detach ()
Detaches the movable object from it's parent.
virtual C3D_API void attachTo (SceneNodeSPtr p_node)
Attaches the movable object to a node.
SceneNodeSPtr getParent () const
Retrieves the parent node.
MovableType getType () const
Retrieves the object type.
Public Member Functions inherited from castor3d::Animable
C3D_API void cleanupAnimations ()
Empties the animations map.
C3D_API bool hasAnimation (castor::String const &p_name) const
Retrieves an animation.
C3D_API Animation const & getAnimation (castor::String const &p_name) const
Retrieves an animation.
C3D_API Animation & getAnimation (castor::String const &p_name)
Retrieves an animation.
AnimationPtrStrMap const & getAnimations () const
Public Member Functions inherited from castor3d::RenderedObject
bool isVisible () const
void setVisible (bool p_value)
Defines the visibility status.
bool isShadowCaster () const
void setShadowCaster (bool p_value)
Defines the shadow caster status.
bool isShadowReceiver () const
void setShadowReceiver (bool p_value)
Defines the shadow receiving status.
Protected Attributes
MeshWPtr m_mesh
castor::String m_strMeshName
bool m_changed { true }
bool m_listCreated { false }
std::map< Submesh const *, MaterialWPtr > m_submeshesMaterials
Protected Attributes inherited from castor3d::MovableObject
MovableType m_type
castor::String m_strNodeName
SceneNodeWPtr m_sceneNode
SceneNode::OnChanged::connection m_notifyIndex
Protected Attributes inherited from castor3d::Animable
AnimationPtrStrMap m_animations
Additional Inherited Members
Protected Member Functions inherited from castor3d::Animable
Animable (Scene &p_scene)
Constructor.
virtual ~Animable ()
Destructor.
C3D_API Animable (Animable &&p_rhs)=default
Move constructor.
C3D_API Animable & operator= (Animable &&p_rhs)=default
Move assignment operator.
C3D_API Animable (Animable const &p_rhs)=delete
Copy constructor.
C3D_API Animable & operator= (Animable const &p_rhs)=delete
Copy assignment operator.
void doAddAnimation (AnimationSPtr &&p_animation)
adds an animation.
template<typename Type >
Type & doGetAnimation (castor::String const &p_name)
Retrieves an animation.
Detailed Description
Geometry handler class.
Author
Sylvain DOREMUS
Date
09/02/2010
Version
0.1
Constructor & Destructor Documentation
Geometry()
C3D_API castor3d::Geometry::Geometry (castor::String const & name, Scene & scene, SceneNodeSPtr node, MeshSPtr mesh = nullptr)
Constructor.
Parameters
[in] name The geometry name.
[in] scene The parent scene.
[in] mesh The mesh, default is nullptr.
[in] node The scene node to which the geometry is attached.
~Geometry()
virtual C3D_API castor3d::Geometry::~Geometry () virtual
Destructor.
Member Function Documentation
cleanup()
C3D_API void castor3d::Geometry::cleanup ()
Cleans all the object owned and created by the geometry.
createBuffers()
C3D_API void castor3d::Geometry::createBuffers (uint32_t & nbFaces, uint32_t & nbVertex)
brief Creates the mesh buffers
Parameters
[out] nbFaces Used to retrieve the faces number
[out] nbVertex Used to retrieve the vertexes number
endRender()
virtual C3D_API void castor3d::Geometry::endRender () inline virtual
End render function, dummy.
References C3D_API, getMaterial(), setMaterial(), and setMesh().
getMaterial()
C3D_API MaterialSPtr castor3d::Geometry::getMaterial (Submesh const & submesh) const
Retrieves the submesh material.
Parameters
[in] submesh The submesh.
Returns
The material.
Referenced by endRender().
getMesh()
MeshSPtr castor3d::Geometry::getMesh () const inline
Retrieves the mesh.
Returns
The mesh
References m_mesh.
render()
virtual C3D_API void castor3d::Geometry::render () virtual
Renders the geometry in a given display mode.
setMaterial()
C3D_API void castor3d::Geometry::setMaterial (Submesh & submesh, MaterialSPtr material, bool updateSubmesh = true)
Defines a submesh material.
Parameters
[in] submesh The submesh.
[in] material The material.
[in] updateSubmesh Tells if the submesh's buffers need to be updated.
Referenced by endRender().
setMesh()
C3D_API void castor3d::Geometry::setMesh (MeshSPtr mesh)
Defines this geometry's mesh.
Parameters
[in] mesh The mesh.
Referenced by endRender().
Member Data Documentation
m_changed
bool castor3d::Geometry::m_changed { true } protected
Tells if the geometry has changed. Tells if the mesh buffers are generated.
m_listCreated
bool castor3d::Geometry::m_listCreated { false } protected
m_mesh
MeshWPtr castor3d::Geometry::m_mesh protected
The mesh.
Referenced by getMesh().
m_strMeshName
castor::String castor3d::Geometry::m_strMeshName protected
The mesh name
m_submeshesMaterials
std::map< Submesh const *, MaterialWPtr > castor3d::Geometry::m_submeshesMaterials protected
The submeshes materials.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Scene/Geometry.hpp