Castor3D: castor3d::ReflectionPass Class Reference
castor3d::ReflectionPass Class Reference
The post lighting reflection pass.
Public Member Functions
ReflectionPass (Engine &engine, castor::Size const &size, SceneUbo &sceneUbo, GpInfoUbo &gpInfoUbo, SsaoConfig const &config)
Constructor.
~ReflectionPass ()
Destructor.
void render (GeometryPassResult &gp, TextureUnit const &lightDiffuse, TextureUnit const &lightSpecular, Scene const &scene, FrameBuffer const &frameBuffer, RenderInfo &info)
Renders the reflection mapping.
TextureLayout const & getSsao () const
Detailed Description
The post lighting reflection pass.
Author
Sylvain DOREMUS
Version
0.10.0
Date
06/04/2017
Constructor & Destructor Documentation
ReflectionPass()
castor3d::ReflectionPass::ReflectionPass (Engine & engine, castor::Size const & size, SceneUbo & sceneUbo, GpInfoUbo & gpInfoUbo, SsaoConfig const & config)
Constructor.
Parameters
[in] engine The engine.
[in] size The render size.
[in] sceneUbo The scene UBO.
[in] gpInfoUbo The geometry pass UBO.
[in] config The SSAO configuration.
~ReflectionPass()
castor3d::ReflectionPass::~ReflectionPass ()
Destructor.
Member Function Documentation
getSsao()
TextureLayout const& castor3d::ReflectionPass::getSsao () const inline
Returns
The SSAO texture.
References castor3d::SsaoPass::getResult(), castor3d::TextureUnit::getTexture(), and render().
render()
void castor3d::ReflectionPass::render (GeometryPassResult & gp, TextureUnit const & lightDiffuse, TextureUnit const & lightSpecular, Scene const & scene, FrameBuffer const & frameBuffer, RenderInfo & info)
Renders the reflection mapping.
Parameters
[in] gp The geometry pass result.
[in] lightDiffuse The diffuse result of the lighting pass.
[in] lightSpecular The specular result of the lighting pass.
[in] scene The rendered scene.
[in] frameBuffer The target frame buffer.
[out] info The render informations.
Referenced by getSsao().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Technique/Opaque/ReflectionPass.hpp