CastorUtils: castor::UniqueObjectPool< Object, MemDataType > Class Template Reference
castor::UniqueObjectPool< Object, MemDataType > Class Template Reference
Unique pool instance.
Static Public Member Functions
static MyObjectPool & get ()
static void create (uint32_t p_count=256u)
Creates the unique object pool instance.
static void destroy ()
Destroys the unique object pool instance.
Detailed Description
template<typename Object, MemoryDataType MemDataType>
class castor::UniqueObjectPool< Object, MemDataType >
Unique pool instance.
Author
Sylvain DOREMUS
Version
0.8.0
Date
08/01/2016
Parameters
Object The pool objects type.
MemDataType The allocation/deallocation policy type.
Member Function Documentation
create()
template<typename Object , MemoryDataType MemDataType> static void castor::UniqueObjectPool< Object, MemDataType >::create (uint32_t p_count = 256u) inline static
Creates the unique object pool instance.
Parameters
[in] p_count The object pool initial objects count.
destroy()
template<typename Object , MemoryDataType MemDataType> static void castor::UniqueObjectPool< Object, MemDataType >::destroy () inline static
Destroys the unique object pool instance.
get()
template<typename Object , MemoryDataType MemDataType> static MyObjectPool& castor::UniqueObjectPool< Object, MemDataType >::get () inline static
Returns
The unique object pool instance.
Referenced by castor::PoolManagedObject< Object, MemDataType >::operator delete(), castor::PoolManagedObject< Object, MemDataType >::operator delete[](), and castor::PoolManagedObject< Object, MemDataType >::operator new().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Pool/UniqueObjectPool.hpp