Castor3D: castor3d::ColourSkybox Class Reference
castor3d::ColourSkybox Class Reference
A skybox with no image but a colour.
Public Member Functions
C3D_API ColourSkybox (Engine &engine)
Constructor.
virtual C3D_API ~ColourSkybox ()
Destructor.
C3D_API bool initialise () override
Initialisation function.
C3D_API void render (Camera const &camera) override
Renders the skybox.
C3D_API void update ()
Updates the skybox.
C3D_API void setColour (castor::Colour const &value)
Defines the skybox's colour.
void setColour (castor::HdrColour const &value)
Defines the skybox's colour.
Public Member Functions inherited from castor3d::Skybox
C3D_API Skybox (Engine &engine)
Constructor.
virtual C3D_API ~Skybox ()
Destructor.
virtual C3D_API void cleanup ()
Cleanup function.
C3D_API void setEquiTexture (TextureLayoutSPtr texture, castor::Size const &size)
castor::Path const & getEquiTexturePath () const
TextureLayout & getTexture ()
TextureLayoutSPtr getTexture () const
IblTextures const & getIbl () const
void setTexture (TextureLayoutSPtr texture)
void setScene (Scene &scene)
Additional Inherited Members
Protected Member Functions inherited from castor3d::Skybox
virtual ShaderProgram & doInitialiseShader ()
bool doInitialiseTexture ()
void doInitialiseEquiTexture ()
bool doInitialiseVertexBuffer ()
bool doInitialisePipeline (ShaderProgram &program)
Protected Attributes inherited from castor3d::Skybox
SceneRPtr m_scene { nullptr }
RenderPipelineUPtr m_pipeline
TextureLayoutSPtr m_equiTexture
castor::Path m_equiTexturePath
castor::Size m_equiSize
TextureLayoutSPtr m_texture
SamplerWPtr m_sampler
MatrixUbo m_matrixUbo
ModelMatrixUbo m_modelMatrixUbo
HdrConfigUbo m_configUbo
VertexBufferSPtr m_vertexBuffer { nullptr }
GeometryBuffersSPtr m_geometryBuffers { nullptr }
castor3d::BufferDeclaration m_declaration
std::array< castor3d::BufferElementGroupSPtr, 36 > m_arrayVertex
std::array< castor::real, 108 > m_bufferVertex
6 * 6 * [3(vertex position)].
castor::Matrix4x4r m_mtxModel
std::unique_ptr< IblTextures > m_ibl
bool m_hdr { false }
Detailed Description
A skybox with no image but a colour.
Author
Sylvain DOREMUS
Version
0.9.0
Date
21/05/2016
Constructor & Destructor Documentation
ColourSkybox()
C3D_API castor3d::ColourSkybox::ColourSkybox (Engine & engine) explicit
Constructor.
Parameters
[in] engine The engine.
~ColourSkybox()
virtual C3D_API castor3d::ColourSkybox::~ColourSkybox () virtual
Destructor.
Member Function Documentation
initialise()
C3D_API bool castor3d::ColourSkybox::initialise () override virtual
Initialisation function.
Returns
true if ok.
Reimplemented from castor3d::Skybox.
render()
C3D_API void castor3d::ColourSkybox::render (Camera const & camera) override virtual
Renders the skybox.
Parameters
[in] camera The scene's camera.
Reimplemented from castor3d::Skybox.
setColour() [1/2]
C3D_API void castor3d::ColourSkybox::setColour (castor::Colour const & value)
Defines the skybox's colour.
Parameters
[in] value The new value.
setColour() [2/2]
void castor3d::ColourSkybox::setColour (castor::HdrColour const & value) inline
Defines the skybox's colour.
Parameters
[in] value The new value.
References castor3d::Skybox::cleanup(), castor3d::Skybox::getEquiTexturePath(), castor3d::Skybox::getIbl(), castor3d::Skybox::getTexture(), castor3d::Skybox::setEquiTexture(), castor3d::Skybox::setScene(), and castor3d::Skybox::setTexture().
update()
C3D_API void castor3d::ColourSkybox::update ()
Updates the skybox.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Scene/ColourSkybox.hpp