CastorUtils: castor::FileParser Class Reference
castor::FileParser Class Reference abstract
"Brace file" parser base class.
Classes
struct ParserFunctionAndParams
Public Types
typedef std::map< uint32_t, AttributeParserMap > AttributeParsersBySection
Public Member Functions
DECLARE_MAP (String, ParserFunctionAndParams, AttributeParser)
CU_API FileParser (uint32_t rootSectionId)
Constructor.
virtual CU_API ~FileParser ()
Destructor.
CU_API bool parseFile (Path const &path)
Parsing function.
CU_API bool parseFile (Path const &path, String const &content)
Parsing function.
CU_API void parseError (String const &error)
Logs an error in the log file.
CU_API void parseWarning (String const &warning)
Logs a warning in the log file.
CU_API bool checkParams (String const &params, ParserParameterArray const &expected, ParserParameterArray &received)
Tests if the params given to the function will be appropriate.
CU_API void addParser (uint32_t section, String const &name, ParserFunction function, ParserParameterArray &&params=ParserParameterArray())
adds a parser function to the parsers list.
bool isIgnored () const
Tells if the read lines are to be ignored.
void ignore ()
Increments ignore level.
FileParserContextSPtr getContext ()
Protected Member Functions
virtual CU_API void doInitialiseParser (castor::Path const &path)=0
Specific initialisation function.
virtual CU_API void doCleanupParser ()=0
Specific cleanup.
virtual CU_API bool doDelegateParser (String const &line)=0
Function called when current section is out of bounds.
virtual CU_API bool doDiscardParser (String const &p_error)=0
Function called when no parser is found for the line.
virtual CU_API void doValidate ()=0
Function called when file parsing is completed with no error.
virtual CU_API castor::String doGetSectionName (uint32_t p_section)=0
Gives the name associated to section ID.
Protected Attributes
AttributeParsersBySection m_parsers
The map holding the parsers, sorted by section.
FileParserContextSPtr m_context
Th parser context.
bool m_ignored
Tells the lines parsed are to be ignored.
Detailed Description
"Brace file" parser base class.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Member Typedef Documentation
AttributeParsersBySection
typedef std::map< uint32_t, AttributeParserMap > castor::FileParser::AttributeParsersBySection
Constructor & Destructor Documentation
FileParser()
CU_API castor::FileParser::FileParser (uint32_t rootSectionId)
Constructor.
Parameters
[in] rootSectionId The root section id.
~FileParser()
virtual CU_API castor::FileParser::~FileParser () virtual
Destructor.
Member Function Documentation
addParser()
CU_API void castor::FileParser::addParser (uint32_t section, String const & name, ParserFunction function, ParserParameterArray && params = ParserParameterArray())
adds a parser function to the parsers list.
Parameters
[in] section The parser section.
[in] name The parser name.
[in] function The parser function.
[in] params The expected parameters.
checkParams()
CU_API bool castor::FileParser::checkParams (String const & params, ParserParameterArray const & expected, ParserParameterArray & received)
Tests if the params given to the function will be appropriate.
Parameters
[in] params The given parameters.
[in] expected The expected parameters.
[in] received The filled parameters.
Returns
false if p_params doesn't contain all expected parameters types.
DECLARE_MAP()
castor::FileParser::DECLARE_MAP (String , ParserFunctionAndParams , AttributeParser)
doCleanupParser()
virtual CU_API void castor::FileParser::doCleanupParser () protected pure virtual
Specific cleanup.
Referenced by getContext().
doDelegateParser()
virtual CU_API bool castor::FileParser::doDelegateParser (String const & line) protected pure virtual
Function called when current section is out of bounds.
Parameters
[in] line The current line.
Returns
true if a brace is opened after this line, false if not.
Referenced by getContext().
doDiscardParser()
virtual CU_API bool castor::FileParser::doDiscardParser (String const & p_error) protected pure virtual
Function called when no parser is found for the line.
Parameters
[in] p_error The error text.
Returns
false if the line must be ignored.
Referenced by getContext().
doGetSectionName()
virtual CU_API castor::String castor::FileParser::doGetSectionName (uint32_t p_section) protected pure virtual
Gives the name associated to section ID.
Parameters
[in] p_section The section ID.
Returns
The name.
Referenced by getContext().
doInitialiseParser()
virtual CU_API void castor::FileParser::doInitialiseParser (castor::Path const & path) protected pure virtual
Specific initialisation function.
Parameters
[in] path The file access path.
Referenced by getContext().
doValidate()
virtual CU_API void castor::FileParser::doValidate () protected pure virtual
Function called when file parsing is completed with no error.
Referenced by getContext().
getContext()
FileParserContextSPtr castor::FileParser::getContext () inline
Returns
The parser context.
References CU_API, doCleanupParser(), doDelegateParser(), doDiscardParser(), doGetSectionName(), doInitialiseParser(), doValidate(), and m_context.
ignore()
void castor::FileParser::ignore () inline
Increments ignore level.
References m_ignored.
isIgnored()
bool castor::FileParser::isIgnored () const inline
Tells if the read lines are to be ignored.
References m_ignored.
parseError()
CU_API void castor::FileParser::parseError (String const & error)
Logs an error in the log file.
Parameters
[in] error The error text.
parseFile() [1/2]
CU_API bool castor::FileParser::parseFile (Path const & path)
Parsing function.
Parameters
[in] path The file access path.
Returns
true if OK.
parseFile() [2/2]
CU_API bool castor::FileParser::parseFile (Path const & path, String const & content)
Parsing function.
Parameters
[in] path The file access path.
[in] content The file content.
Returns
true if OK.
parseWarning()
CU_API void castor::FileParser::parseWarning (String const & warning)
Logs a warning in the log file.
Parameters
[in] warning The warning text.
Member Data Documentation
m_context
FileParserContextSPtr castor::FileParser::m_context protected
Th parser context.
Referenced by getContext().
m_ignored
bool castor::FileParser::m_ignored protected
Tells the lines parsed are to be ignored.
Referenced by ignore(), and isIgnored().
m_parsers
AttributeParsersBySection castor::FileParser::m_parsers protected
The map holding the parsers, sorted by section.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/FileParser/FileParser.hpp