CastorUtils: castor::format::BasicPrefixBuffer< prefix_type, char_type, traits > Struct Template Reference
castor::format::BasicPrefixBuffer< prefix_type, char_type, traits > Struct Template Reference
Stream buffer used by streams to indent lines.
Public Types
typedef traits::int_type int_type
typedef traits::pos_type pos_type
typedef traits::off_type off_type
Public Member Functions
BasicPrefixBuffer (std::basic_streambuf< char_type, traits > *sbuf)
Constructor.
~BasicPrefixBuffer ()
Destructor.
std::streambuf * sbuf () const
Retrieves the stream buffer.
Detailed Description
template<typename prefix_type, typename char_type, typename traits = std::char_traits< char_type >>
struct castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >
Stream buffer used by streams to indent lines.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
02/09/2014
Member Typedef Documentation
int_type
template<typename prefix_type , typename char_type , typename traits = std::char_traits< char_type >> typedef traits::int_type castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >::int_type
off_type
template<typename prefix_type , typename char_type , typename traits = std::char_traits< char_type >> typedef traits::off_type castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >::off_type
pos_type
template<typename prefix_type , typename char_type , typename traits = std::char_traits< char_type >> typedef traits::pos_type castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >::pos_type
Constructor & Destructor Documentation
BasicPrefixBuffer()
template<typename prefix_type , typename char_type , typename traits = std::char_traits< char_type >> castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >::BasicPrefixBuffer (std::basic_streambuf< char_type, traits > * sbuf) inline explicit
Constructor.
Referenced by castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >::sbuf().
~BasicPrefixBuffer()
template<typename prefix_type , typename char_type , typename traits = std::char_traits< char_type >> castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >::~BasicPrefixBuffer () inline
Destructor.
Member Function Documentation
sbuf()
template<typename prefix_type , typename char_type , typename traits = std::char_traits< char_type >> std::streambuf* castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >::sbuf () const inline
Retrieves the stream buffer.
Returns
The buffer
References castor::format::BasicPrefixBuffer< prefix_type, char_type, traits >::BasicPrefixBuffer(), castor::details::c, and castor::string::toString().
The documentation for this struct was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Stream/StreamPrefixBuffer.hpp