CastorUtils: castor::DynamicLibrary Class Reference
castor::DynamicLibrary Class Reference
Platform independant library.
Public Member Functions
CU_API DynamicLibrary () throw ()
Default constructor.
CU_API DynamicLibrary (DynamicLibrary const &p_lib) throw ()
Copy constructor.
CU_API DynamicLibrary (DynamicLibrary &&p_lib) throw ()
Move constructor.
CU_API ~DynamicLibrary () throw ()
Destructor.
CU_API DynamicLibrary & operator= (DynamicLibrary const &p_lib)
Copy assignment operator.
CU_API DynamicLibrary & operator= (DynamicLibrary &&p_lib)
Move assignment operator.
CU_API bool open (xchar const *p_szPath) throw ()
Opens a library from a path.
CU_API bool open (String const &p_strPath) throw ()
Opens a library from a path.
CU_API bool open (Path const &p_pathFile) throw ()
Opens a library from a path.
template<typename FuncType >
bool getFunction (FuncType &p_pfnFunction, char const *p_szName) throw ()
Retrieves a function.
template<typename FuncType >
bool getFunction (FuncType &p_pfnFunction, wchar_t const *p_wszName) throw ()
Retrieves a function.
template<typename FuncType >
bool getFunction (FuncType &p_pfnFunction, String const &p_name) throw ()
Retrieves a function.
bool isOpen () const
Tells if the DynamicLibrary is opened (loaded)
Path const & getPath () const
Retrieves the file path.
Detailed Description
Platform independant library.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Remarks
Loads a library and gives access to it's functions in a platform independant way
Constructor & Destructor Documentation
DynamicLibrary() [1/3]
CU_API castor::DynamicLibrary::DynamicLibrary () throw ()
Default constructor.
DynamicLibrary() [2/3]
CU_API castor::DynamicLibrary::DynamicLibrary (DynamicLibrary const & p_lib) throw ()
Copy constructor.
Parameters
[in] p_lib The DynamicLibrary to copy
DynamicLibrary() [3/3]
CU_API castor::DynamicLibrary::DynamicLibrary (DynamicLibrary && p_lib) throw ()
Move constructor.
Parameters
[in] p_lib The DynamicLibrary to move
~DynamicLibrary()
CU_API castor::DynamicLibrary::~DynamicLibrary () throw ()
Destructor.
Member Function Documentation
getFunction() [1/3]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (FuncType & p_pfnFunction, char const * p_szName) throw () inline
Retrieves a function.
Parameters
[in] p_pfnFunction Receives the function
[in] p_szName The function name
Returns
true if the function was correctly retrieved
Referenced by getFunction().
getFunction() [2/3]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (FuncType & p_pfnFunction, wchar_t const * p_wszName) throw () inline
Retrieves a function.
Parameters
[in] p_pfnFunction Receives the function
[in] p_wszName The function name
Returns
true if the function was correctly retrieved
References getFunction().
getFunction() [3/3]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (FuncType & p_pfnFunction, String const & p_name) throw () inline
Retrieves a function.
Parameters
[in] p_pfnFunction Receives the function
[in] p_name The function name
Returns
true if the function was correctly retrieved
getPath()
Path const& castor::DynamicLibrary::getPath () const inline
Retrieves the file path.
Returns
The file path
References CU_API, and castor::DECLARE_SMART_PTR().
isOpen()
bool castor::DynamicLibrary::isOpen () const inline
Tells if the DynamicLibrary is opened (loaded)
Returns
true if it is opened, false if not
open() [1/3]
CU_API bool castor::DynamicLibrary::open (xchar const * p_szPath) throw ()
Opens a library from a path.
Parameters
[in] p_szPath The file path
Returns
true if library was successfully loaded
open() [2/3]
CU_API bool castor::DynamicLibrary::open (String const & p_strPath) throw ()
Opens a library from a path.
Parameters
[in] p_strPath The file path
Returns
true if library was successfully loaded
open() [3/3]
CU_API bool castor::DynamicLibrary::open (Path const & p_pathFile) throw ()
Opens a library from a path.
Parameters
[in] p_pathFile The file path
Returns
true if library was successfully loaded
operator=() [1/2]
CU_API DynamicLibrary& castor::DynamicLibrary::operator= (DynamicLibrary const & p_lib)
Copy assignment operator.
Parameters
[in] p_lib The DynamicLibrary to copy
Returns
A reference to this DynamicLibrary
operator=() [2/2]
CU_API DynamicLibrary& castor::DynamicLibrary::operator= (DynamicLibrary && p_lib)
Move assignment operator.
Parameters
[in] p_lib The DynamicLibrary to move
Returns
A reference to this DynamicLibrary
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Miscellaneous/DynamicLibrary.hpp