CastorUtils: castor::manip Namespace Reference
castor::manip Namespace Reference
Classes
struct BaseNumPut
A custom number output facet.
struct BasicBaseManip
Defines a base manipulator type, its what the built-in stream manipulators do when they take parameters, only they return an opaque type.
Typedefs
typedef BasicBaseManip< char > BaseManip
typedef BasicBaseManip< wchar_t > WBaseManip
typedef BasicBaseManip< xchar > XBaseManip
Functions
BaseManip base (int b)
Stream operator.
WBaseManip wbase (int b)
Stream operator.
XBaseManip xbase (int b)
Stream operator.
std::ostream & operator<< (std::ostream &stream, const manip::BaseManip &manip)
Stream operator.
std::wostream & operator<< (std::wostream &stream, const manip::WBaseManip &manip)
Stream operator.
Typedef Documentation
BaseManip
typedef BasicBaseManip< char > castor::manip::BaseManip
WBaseManip
typedef BasicBaseManip< wchar_t > castor::manip::WBaseManip
XBaseManip
typedef BasicBaseManip< xchar > castor::manip::XBaseManip
Function Documentation
base()
BaseManip castor::manip::base (int b) inline
Stream operator.
Remarks
Creates a manipulator, to be able to use it in a stream
Parameters
[in] b The base
Referenced by castor::manip::BaseNumPut< CharType >::doPutHelper().
operator<<() [1/2]
std::ostream& castor::manip::operator<< (std::ostream & stream, const manip::BaseManip & manip) inline
Stream operator.
Remarks
We need this so we can apply our custom stream manipulator to the stream.
Parameters
[in] stream The stream
[in] manip The manipulator
References castor::manip::BasicBaseManip< CharType >::apply().
operator<<() [2/2]
std::wostream& castor::manip::operator<< (std::wostream & stream, const manip::WBaseManip & manip) inline
Stream operator.
Remarks
We need this so we can apply our custom stream manipulator to the stream.
Parameters
[in] stream The stream
[in] manip The manipulator
References castor::manip::BasicBaseManip< CharType >::apply().
wbase()
WBaseManip castor::manip::wbase (int b) inline
Stream operator.
Remarks
Creates a manipulator, to be able to use it in a stream
Parameters
[in] b The base
xbase()
XBaseManip castor::manip::xbase (int b) inline
Stream operator.
Remarks
Creates a manipulator, to be able to use it in a stream
Parameters
[in] b The base