CastorUtils: castor::Pixel< FT > Class Template Reference
castor::Pixel< FT > Class Template Reference
Pixel definition.
Public Types
using iterator = uint8_t *
using const_iterator = uint8_t const *
Public Member Functions
Pixel (bool p_init=false)
Constructor.
Pixel (uint8_t *p_components)
Constructor.
Pixel (Pixel const &p_pxl)
Copy Constructor.
Pixel (Pixel &&p_pxl)
Move Constructor.
template<PixelFormat FU>
Pixel (std::array< uint8_t, PixelDefinitions< FU >::Size > const &p_components)
Constructor.
template<PixelFormat FU>
Pixel (Pixel< FU > const &p_pxl)
Constructor.
virtual ~Pixel ()
Destructor.
Pixel & operator= (Pixel &&p_pxl)
Copy assignment operator.
Pixel & operator= (Pixel const &p_pxl)
Move assignment operator.
template<PixelFormat FU>
Pixel & operator= (Pixel< FU > const &p_pxl)
Copy assignment operator.
template<typename U >
void sum (U &p_result) const
Computes the sum of all components.
template<PixelFormat FU>
Pixel< FU > mul (Pixel< FU > const &p_px) const
Multiplication function.
template<PixelFormat FU>
Pixel< FU > mul (uint8_t const &p_byVal) const
Multiplication function.
void clear ()
deallocate components
void link (uint8_t *p_components)
Links the data pointer to the one given in parameter.
void unlink ()
Unlinks the data pointer from the ones previously given.
template<PixelFormat FU>
void set (std::array< uint8_t, PixelDefinitions< FU >::Size > const &p_components)
Converts given data and copies it into this pixel's components.
template<PixelFormat FU>
void set (uint8_t const *p_components)
Converts given data and copies it into this pixel's components.
template<PixelFormat FU>
void set (Pixel< FU > const &p_px)
Converts given pixel and copies it into this pixel's components.
component_ref operator[] (uint8_t p_index)
Retrieves the data at given index.
component_const_ref operator[] (uint8_t p_index) const
Retrieves the data at given index.
component_const_ptr constPtr () const
Retrieves the pointer on constant datas.
component_ptr ptr ()
Retrieves the pointer on datas.
iterator begin ()
Retrieves an iterator to the first element.
const_iterator begin () const
Retrieves a constant iterator to the first element.
iterator end ()
Retrieves an iterator to the last element.
const_iterator end () const
Retrieves a constant iterator to the last element.
Arithmetic member operators.
template<PixelFormat FU>
Pixel & operator+= (Pixel< FU > const &p_px)
template<PixelFormat FU>
Pixel & operator-= (Pixel< FU > const &p_px)
template<PixelFormat FU>
Pixel & operator*= (Pixel< FU > const &p_px)
template<PixelFormat FU>
Pixel & operator/= (Pixel< FU > const &p_px)
template<typename U >
Pixel & operator+= (U const &p_t)
template<typename U >
Pixel & operator-= (U const &p_t)
template<typename U >
Pixel & operator*= (U const &p_t)
template<typename U >
Pixel & operator/= (U const &p_t)
Static Public Member Functions
static PixelFormat getFormat ()
Retrieves the pixel format.
static uint32_t getSize ()
Retrieves the pixel size.
Protected Types
using component_ptr = uint8_t *
using component_const_ptr = uint8_t const *
using component_ref = uint8_t &
using component_const_ref = uint8_t const &
Detailed Description
template<PixelFormat FT>
class castor::Pixel< FT >
Pixel definition.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
29/08/2011
Remarks
Takes a PixelFormat as a template argument to determine size anf format.
Member Typedef Documentation
component_const_ptr
template<PixelFormat FT> using castor::Pixel< FT >::component_const_ptr = uint8_t const * protected
component_const_ref
template<PixelFormat FT> using castor::Pixel< FT >::component_const_ref = uint8_t const & protected
component_ptr
template<PixelFormat FT> using castor::Pixel< FT >::component_ptr = uint8_t * protected
component_ref
template<PixelFormat FT> using castor::Pixel< FT >::component_ref = uint8_t & protected
const_iterator
template<PixelFormat FT> using castor::Pixel< FT >::const_iterator = uint8_t const *
Constant iterator on the pixel's data.
iterator
template<PixelFormat FT> using castor::Pixel< FT >::iterator = uint8_t *
Iterator on the pixel's data.
Constructor & Destructor Documentation
Pixel() [1/6]
template<PixelFormat FT> castor::Pixel< FT >::Pixel (bool p_init = false)
Constructor.
Parameters
[in] p_init Tells if the data are initialised
Pixel() [2/6]
template<PixelFormat FT> castor::Pixel< FT >::Pixel (uint8_t * p_components)
Constructor.
Remarks
This Pixel doesn't own it's data
Parameters
[in] p_components Initialises the data to this one
Pixel() [3/6]
template<PixelFormat FT> castor::Pixel< FT >::Pixel (Pixel< FT > const & p_pxl)
Copy Constructor.
Parameters
[in] p_pxl The Pixel object to copy
Pixel() [4/6]
template<PixelFormat FT> castor::Pixel< FT >::Pixel (Pixel< FT > && p_pxl)
Move Constructor.
Parameters
[in] p_pxl The Pixel object to move
Pixel() [5/6]
template<PixelFormat FT> template<PixelFormat FU> castor::Pixel< FT >::Pixel (std::array< uint8_t, PixelDefinitions< FU >::Size > const & p_components)
Constructor.
Remarks
This Pixel owns it's data
Parameters
[in] p_components Initialises the data to this one
Pixel() [6/6]
template<PixelFormat FT> template<PixelFormat FU> castor::Pixel< FT >::Pixel (Pixel< FU > const & p_pxl)
Constructor.
Parameters
[in] p_pxl The Pixel object to copy
~Pixel()
template<PixelFormat FT> virtual castor::Pixel< FT >::~Pixel () virtual
Destructor.
Member Function Documentation
begin() [1/2]
template<PixelFormat FT> iterator castor::Pixel< FT >::begin () inline
Retrieves an iterator to the first element.
Returns
The iterator
begin() [2/2]
template<PixelFormat FT> const_iterator castor::Pixel< FT >::begin () const inline
Retrieves a constant iterator to the first element.
Returns
The iterator
clear()
template<PixelFormat FT> void castor::Pixel< FT >::clear ()
deallocate components
constPtr()
template<PixelFormat FT> component_const_ptr castor::Pixel< FT >::constPtr () const inline
Retrieves the pointer on constant datas.
Returns
The pointer
Referenced by castor::Image::setPixel().
end() [1/2]
template<PixelFormat FT> iterator castor::Pixel< FT >::end () inline
Retrieves an iterator to the last element.
Returns
The iterator
end() [2/2]
template<PixelFormat FT> const_iterator castor::Pixel< FT >::end () const inline
Retrieves a constant iterator to the last element.
Returns
The iterator
getFormat()
template<PixelFormat FT> static PixelFormat castor::Pixel< FT >::getFormat () inline static
Retrieves the pixel format.
Returns
The pixel format
getSize()
template<PixelFormat FT> static uint32_t castor::Pixel< FT >::getSize () inline static
Retrieves the pixel size.
Returns
The size
link()
template<PixelFormat FT> void castor::Pixel< FT >::link (uint8_t * p_components)
Links the data pointer to the one given in parameter.
Remarks
The pixel loses ownership of it's data
Referenced by castor::PixelIterator< PF >::operator!=().
mul() [1/2]
template<PixelFormat FT> template<PixelFormat FU> Pixel< FU > castor::Pixel< FT >::mul (Pixel< FU > const & p_px) const
Multiplication function.
Parameters
[in] p_px The pixel to multiply
Returns
The multiplication result
mul() [2/2]
template<PixelFormat FT> template<PixelFormat FU> Pixel< FU > castor::Pixel< FT >::mul (uint8_t const & p_byVal) const
Multiplication function.
Parameters
[in] p_byVal The value
Returns
The multiplication result
operator*=() [1/2]
template<PixelFormat FT> template<PixelFormat FU> Pixel& castor::Pixel< FT >::operator*= (Pixel< FU > const & p_px)
Referenced by castor::Pixel< PF >::getSize().
operator*=() [2/2]
template<PixelFormat FT> template<typename U > Pixel& castor::Pixel< FT >::operator*= (U const & p_t)
operator+=() [1/2]
template<PixelFormat FT> template<PixelFormat FU> Pixel& castor::Pixel< FT >::operator+= (Pixel< FU > const & p_px)
Referenced by castor::Pixel< PF >::getSize().
operator+=() [2/2]
template<PixelFormat FT> template<typename U > Pixel& castor::Pixel< FT >::operator+= (U const & p_t)
operator-=() [1/2]
template<PixelFormat FT> template<PixelFormat FU> Pixel& castor::Pixel< FT >::operator-= (Pixel< FU > const & p_px)
Referenced by castor::Pixel< PF >::getSize().
operator-=() [2/2]
template<PixelFormat FT> template<typename U > Pixel& castor::Pixel< FT >::operator-= (U const & p_t)
operator/=() [1/2]
template<PixelFormat FT> template<PixelFormat FU> Pixel& castor::Pixel< FT >::operator/= (Pixel< FU > const & p_px)
Referenced by castor::Pixel< PF >::getSize().
operator/=() [2/2]
template<PixelFormat FT> template<typename U > Pixel& castor::Pixel< FT >::operator/= (U const & p_t)
operator=() [1/3]
template<PixelFormat FT> Pixel& castor::Pixel< FT >::operator= (Pixel< FT > && p_pxl)
Copy assignment operator.
Parameters
[in] p_pxl The Pixel object to copy
Returns
A reference to this Pixel object
operator=() [2/3]
template<PixelFormat FT> Pixel& castor::Pixel< FT >::operator= (Pixel< FT > const & p_pxl)
Move assignment operator.
Parameters
[in] p_pxl The Pixel object to move
Returns
A reference to this Pixel object
operator=() [3/3]
template<PixelFormat FT> template<PixelFormat FU> Pixel& castor::Pixel< FT >::operator= (Pixel< FU > const & p_pxl)
Copy assignment operator.
Parameters
[in] p_pxl The Pixel object to copy
Returns
A reference to this Pixel object
operator[]() [1/2]
template<PixelFormat FT> component_ref castor::Pixel< FT >::operator[] (uint8_t p_index) inline
Retrieves the data at given index.
Remarks
No check is made, if you make an index error, expect a crash
Returns
A reference on data at wanted index
operator[]() [2/2]
template<PixelFormat FT> component_const_ref castor::Pixel< FT >::operator[] (uint8_t p_index) const inline
Retrieves the data at given index.
Remarks
No check is made, if you make an index error, expect a crash
Returns
A constant reference on data at wanted index
ptr()
template<PixelFormat FT> component_ptr castor::Pixel< FT >::ptr () inline
Retrieves the pointer on datas.
Returns
The pointer
Referenced by castor::Image::getPixel().
set() [1/3]
template<PixelFormat FT> template<PixelFormat FU> void castor::Pixel< FT >::set (std::array< uint8_t, PixelDefinitions< FU >::Size > const & p_components)
Converts given data and copies it into this pixel's components.
Parameters
[in] p_components Data to convert
set() [2/3]
template<PixelFormat FT> template<PixelFormat FU> void castor::Pixel< FT >::set (uint8_t const * p_components)
Converts given data and copies it into this pixel's components.
Parameters
[in] p_components Data to convert
set() [3/3]
template<PixelFormat FT> template<PixelFormat FU> void castor::Pixel< FT >::set (Pixel< FU > const & p_px)
Converts given pixel and copies it into this pixel's components.
Parameters
[in] p_px Pixel to convert
sum()
template<PixelFormat FT> template<typename U > void castor::Pixel< FT >::sum (U & p_result) const
Computes the sum of all components.
Parameters
[out] p_result Receives the sum
unlink()
template<PixelFormat FT> void castor::Pixel< FT >::unlink ()
Unlinks the data pointer from the ones previously given.
Remarks
The pixel regains ownership of it's data
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/CastorUtilsPrerequisites.hpp
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/Pixel.hpp