CastorUtils: Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Data/MiniZip/crypt.h File Reference
crypt.h File Reference
Macros
#define CRC32(c, b) ((*(pcrc_32_tab+(((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))
#define zdecode(pkeys, pcrc_32_tab, c) (update_keys(pkeys,pcrc_32_tab,c ^= decrypt_byte(pkeys,pcrc_32_tab)))
#define zencode(pkeys, pcrc_32_tab, c, t) (t=decrypt_byte(pkeys,pcrc_32_tab), update_keys(pkeys,pcrc_32_tab,c), t^(c))
Functions
static int decrypt_byte (unsigned long *pkeys, const unsigned long *pcrc_32_tab)
static int update_keys (unsigned long *pkeys, const unsigned long *pcrc_32_tab, int c)
static void init_keys (const char *passwd, unsigned long *pkeys, const unsigned long *pcrc_32_tab)
Macro Definition Documentation
CRC32
#define CRC32 (c, b) ((*(pcrc_32_tab+(((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))
Referenced by update_keys().
zdecode
#define zdecode (pkeys, pcrc_32_tab, c) (update_keys(pkeys,pcrc_32_tab,c ^= decrypt_byte(pkeys,pcrc_32_tab)))
zencode
#define zencode (pkeys, pcrc_32_tab, c, t) (t=decrypt_byte(pkeys,pcrc_32_tab), update_keys(pkeys,pcrc_32_tab,c), t^(c))
Function Documentation
decrypt_byte()
static int decrypt_byte (unsigned long * pkeys, const unsigned long * pcrc_32_tab) static
init_keys()
static void init_keys (const char * passwd, unsigned long * pkeys, const unsigned long * pcrc_32_tab) static
References update_keys().
update_keys()
static int update_keys (unsigned long * pkeys, const unsigned long * pcrc_32_tab, int c) static
References castor::details::c, CRC32, and int().
Referenced by init_keys().