CastorUtils: castor::ContainerBox< Dimension > Class Template Reference
castor::ContainerBox< Dimension > Class Template Reference abstract
Box container class.
Public Member Functions
ContainerBox ()
Default constructor.
ContainerBox (ContainerBox const &p_container)
Copy constructor.
ContainerBox (ContainerBox &&p_container)
Move constructor.
ContainerBox (Point< real, Dimension > const &p_ptCenter)
Constructor from center.
ContainerBox & operator= (ContainerBox const &p_container)
Copy assignment operator.
ContainerBox & operator= (ContainerBox &&p_container)
Move assignment operator.
virtual CU_API bool isWithin (Point< real, Dimension > const &p_v)=0
Tests if a vertex is within the container, id est inside it but not on it's limits.
virtual CU_API bool isOnLimits (Point< real, Dimension > const &p_v)=0
Tests if a vertex is on the limits of this container, and not within.
Point< real, Dimension > const & getCenter () const
Retrieves the center of this container.
Protected Attributes
Point< real, Dimension > m_ptCenter
The center of the container.
Detailed Description
template<uint8_t Dimension>
class castor::ContainerBox< Dimension >
Box container class.
Author
Sylvain DOREMUS
Date
14/02/2010
Remarks
A container will be a simple object which surrounds a graphic object (2D or 3D)
It can be a parallelepiped, a sphere or other.
Constructor & Destructor Documentation
ContainerBox() [1/4]
template<uint8_t Dimension> castor::ContainerBox< Dimension >::ContainerBox () inline
Default constructor.
ContainerBox() [2/4]
template<uint8_t Dimension> castor::ContainerBox< Dimension >::ContainerBox (ContainerBox< Dimension > const & p_container) inline
Copy constructor.
Parameters
[in] p_container The container to copy
ContainerBox() [3/4]
template<uint8_t Dimension> castor::ContainerBox< Dimension >::ContainerBox (ContainerBox< Dimension > && p_container) inline
Move constructor.
Parameters
[in] p_container The container to move
ContainerBox() [4/4]
template<uint8_t Dimension> castor::ContainerBox< Dimension >::ContainerBox (Point< real, Dimension > const & p_ptCenter) inline explicit
Constructor from center.
Parameters
[in] p_ptCenter The center
Member Function Documentation
getCenter()
template<uint8_t Dimension> Point< real, Dimension > const& castor::ContainerBox< Dimension >::getCenter () const inline
Retrieves the center of this container.
Returns
A constant reference to the center
References castor::ContainerBox< Dimension >::m_ptCenter.
isOnLimits()
template<uint8_t Dimension> virtual CU_API bool castor::ContainerBox< Dimension >::isOnLimits (Point< real, Dimension > const & p_v) pure virtual
Tests if a vertex is on the limits of this container, and not within.
Parameters
[in] p_v The vertex to test
Returns
true if the vertex is on the limits of the container, false if not
Referenced by castor::ContainerBox< Dimension >::operator=().
isWithin()
template<uint8_t Dimension> virtual CU_API bool castor::ContainerBox< Dimension >::isWithin (Point< real, Dimension > const & p_v) pure virtual
Tests if a vertex is within the container, id est inside it but not on it's limits.
Parameters
[in] p_v The vertex to test
Returns
true if the vertex is within the container, false if not
Referenced by castor::ContainerBox< Dimension >::operator=().
operator=() [1/2]
template<uint8_t Dimension> ContainerBox& castor::ContainerBox< Dimension >::operator= (ContainerBox< Dimension > const & p_container) inline
Copy assignment operator.
Parameters
[in] p_container The container to copy
Returns
A reference to this container
References castor::ContainerBox< Dimension >::m_ptCenter.
operator=() [2/2]
template<uint8_t Dimension> ContainerBox& castor::ContainerBox< Dimension >::operator= (ContainerBox< Dimension > && p_container) inline
Move assignment operator.
Parameters
[in] p_container The container to copy
Returns
A reference to this container
References CU_API, castor::ContainerBox< Dimension >::isOnLimits(), castor::ContainerBox< Dimension >::isWithin(), and castor::ContainerBox< Dimension >::m_ptCenter.
Member Data Documentation
m_ptCenter
template<uint8_t Dimension> Point< real, Dimension > castor::ContainerBox< Dimension >::m_ptCenter protected
The center of the container.
Referenced by castor::ContainerBox< Dimension >::getCenter(), and castor::ContainerBox< Dimension >::operator=().
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/CastorUtilsPrerequisites.hpp
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/ContainerBox.hpp