CastorUtils: castor::Path Class Reference
castor::Path Class Reference
Path management class.
Public Member Functions
CU_API Path ()
CU_API Path (char const *p_data)
Constructor from a char array.
CU_API Path (wchar_t const *p_data)
Constructor from a wchar_t array.
CU_API Path (String const &p_data)
Constructor from a String.
CU_API Path (Path const &p_data)
Copy Constructor.
CU_API Path (Path &&p_data)
Move Constructor.
CU_API Path & operator= (Path const &p_data)
Copy assignment operator.
CU_API Path & operator= (Path &&p_data)
Move assignment operator.
CU_API Path & operator/= (Path const &p_path)
Appends a path to the current path. adds the separator if needed.
CU_API Path & operator/= (String const &p_string)
adds a string to the current path. Adds the separator if needed
CU_API Path & operator/= (char const *p_buffer)
adds a MBCS C string to the current path. Adds the separator if needed
CU_API Path & operator/= (wchar_t const *p_buffer)
adds a Unicode C string to the current path. Adds the separator if needed
CU_API Path & operator+= (Path const &p_path)
Appends a path to the current path.
CU_API Path & operator+= (String const &p_string)
adds a string to the current path.
CU_API Path & operator+= (char const *p_buffer)
adds a MBCS C string to the current path.
CU_API Path & operator+= (wchar_t const *p_buffer)
adds a Unicode C string to the current path.
CU_API Path getPath () const
Retrieves the parent path.
CU_API Path getFileName (bool p_withExtension=false) const
Retrieves the leaf of this path (filename and extension for files).
CU_API Path getFullFileName () const
Retrieves the full path and leaf.
CU_API String getExtension () const
Retrieves the extension of the file name, if any.
Static Public Attributes
static const xchar Separator
Path separator (OS dependant)
Detailed Description
Path management class.
Author
Sylvain DOREMUS
Date
09/02/2010
Remarks
Defines platform dependant paths.
Constructor & Destructor Documentation
Path() [1/6]
CU_API castor::Path::Path ()
Path() [2/6]
CU_API castor::Path::Path (char const * p_data) explicit
Constructor from a char array.
Parameters
[in] p_data The char array
Path() [3/6]
CU_API castor::Path::Path (wchar_t const * p_data) explicit
Constructor from a wchar_t array.
Parameters
[in] p_data The wchar_t array
Path() [4/6]
CU_API castor::Path::Path (String const & p_data) explicit
Constructor from a String.
Parameters
[in] p_data The String
Path() [5/6]
CU_API castor::Path::Path (Path const & p_data)
Copy Constructor.
Parameters
[in] p_data The Path object to copy
Path() [6/6]
CU_API castor::Path::Path (Path && p_data)
Move Constructor.
Parameters
[in] p_data The Path object to move
Member Function Documentation
getExtension()
CU_API String castor::Path::getExtension () const
Retrieves the extension of the file name, if any.
Returns
The extension
getFileName()
CU_API Path castor::Path::getFileName (bool p_withExtension = false) const
Retrieves the leaf of this path (filename and extension for files).
Parameters
[in] p_withExtension Tells if we want extension or not, for files.
Returns
The leaf.
Referenced by castor::TextWriter< RgbaColourT< ComponentType > >::copyFile().
getFullFileName()
CU_API Path castor::Path::getFullFileName () const
Retrieves the full path and leaf.
Returns
The full path and leaf
Referenced by castor::File::getFileName().
getPath()
CU_API Path castor::Path::getPath () const
Retrieves the parent path.
Returns
The parent path
Referenced by castor::File::getFilePath().
operator+=() [1/4]
CU_API Path& castor::Path::operator+= (Path const & p_path)
Appends a path to the current path.
Parameters
[in] p_path The path to add
operator+=() [2/4]
CU_API Path& castor::Path::operator+= (String const & p_string)
adds a string to the current path.
Parameters
[in] p_string The path to add
operator+=() [3/4]
CU_API Path& castor::Path::operator+= (char const * p_buffer)
adds a MBCS C string to the current path.
Parameters
[in] p_buffer The path to add
operator+=() [4/4]
CU_API Path& castor::Path::operator+= (wchar_t const * p_buffer)
adds a Unicode C string to the current path.
Parameters
[in] p_buffer The path to add
operator/=() [1/4]
CU_API Path& castor::Path::operator/= (Path const & p_path)
Appends a path to the current path. adds the separator if needed.
Parameters
[in] p_path The path to add
operator/=() [2/4]
CU_API Path& castor::Path::operator/= (String const & p_string)
adds a string to the current path. Adds the separator if needed
Parameters
[in] p_string The path to add
operator/=() [3/4]
CU_API Path& castor::Path::operator/= (char const * p_buffer)
adds a MBCS C string to the current path. Adds the separator if needed
Parameters
[in] p_buffer The path to add
operator/=() [4/4]
CU_API Path& castor::Path::operator/= (wchar_t const * p_buffer)
adds a Unicode C string to the current path. Adds the separator if needed
Parameters
[in] p_buffer The path to add
operator=() [1/2]
CU_API Path& castor::Path::operator= (Path const & p_data)
Copy assignment operator.
Parameters
[in] p_data The Path object to copy
Returns
A reference to this Path object
operator=() [2/2]
CU_API Path& castor::Path::operator= (Path && p_data)
Move assignment operator.
Parameters
[in] p_data The Path object to move
Returns
A reference to this Path object
Member Data Documentation
Separator
const xchar castor::Path::Separator static
Path separator (OS dependant)
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Data/Path.hpp