CastorUtils: castor::PixelIterator< PF > Struct Template Reference
castor::PixelIterator< PF > Struct Template Reference
Public Types
using pixel_type = Pixel< PF >
using array_type = PxBufferBase::px_array
using internal_type = array_type::iterator
using const_internal_type = array_type::const_iterator
Public Member Functions
PixelIterator (array_type const &p_array, internal_type const &p_iter)
PixelIterator (PixelIterator const &p_iter)
PixelIterator (PixelIterator &&p_iter)
PixelIterator & operator= (PixelIterator const &p_it)
PixelIterator & operator= (PixelIterator &&p_it)
PixelIterator & operator+= (size_t p_offset)
PixelIterator & operator-= (size_t p_offset)
PixelIterator & operator++ ()
PixelIterator operator++ (int)
PixelIterator & operator-- ()
PixelIterator operator-- (int)
pixel_type const & operator* () const
pixel_type & operator* ()
pixel_type * operator-> ()
bool operator== (PixelIterator const &p_it) const
bool operator!= (PixelIterator const &p_it) const
Member Typedef Documentation
array_type
template<PixelFormat PF> using castor::PixelIterator< PF >::array_type = PxBufferBase::px_array
const_internal_type
template<PixelFormat PF> using castor::PixelIterator< PF >::const_internal_type = array_type::const_iterator
internal_type
template<PixelFormat PF> using castor::PixelIterator< PF >::internal_type = array_type::iterator
pixel_type
template<PixelFormat PF> using castor::PixelIterator< PF >::pixel_type = Pixel< PF >
Constructor & Destructor Documentation
PixelIterator() [1/3]
template<PixelFormat PF> castor::PixelIterator< PF >::PixelIterator (array_type const & p_array, internal_type const & p_iter) inline
PixelIterator() [2/3]
template<PixelFormat PF> castor::PixelIterator< PF >::PixelIterator (PixelIterator< PF > const & p_iter) inline
PixelIterator() [3/3]
template<PixelFormat PF> castor::PixelIterator< PF >::PixelIterator (PixelIterator< PF > && p_iter) inline
Member Function Documentation
operator!=()
template<PixelFormat PF> bool castor::PixelIterator< PF >::operator!= (PixelIterator< PF > const & p_it) const inline
References castor::Pixel< FT >::link().
operator*() [1/2]
template<PixelFormat PF> pixel_type const& castor::PixelIterator< PF >::operator* () const inline
References REQUIRE.
operator*() [2/2]
template<PixelFormat PF> pixel_type& castor::PixelIterator< PF >::operator* () inline
References REQUIRE.
operator++() [1/2]
template<PixelFormat PF> PixelIterator& castor::PixelIterator< PF >::operator++ () inline
References castor::PixelIterator< PF >::operator+=().
operator++() [2/2]
template<PixelFormat PF> PixelIterator castor::PixelIterator< PF >::operator++ (int) inline
operator+=()
template<PixelFormat PF> PixelIterator& castor::PixelIterator< PF >::operator+= (size_t p_offset) inline
Referenced by castor::PixelIterator< PF >::operator++(), and castor::ConstPixelIterator< PF >::operator++().
operator--() [1/2]
template<PixelFormat PF> PixelIterator& castor::PixelIterator< PF >::operator-- () inline
References castor::PixelIterator< PF >::operator-=().
operator--() [2/2]
template<PixelFormat PF> PixelIterator castor::PixelIterator< PF >::operator-- (int) inline
operator-=()
template<PixelFormat PF> PixelIterator& castor::PixelIterator< PF >::operator-= (size_t p_offset) inline
Referenced by castor::PixelIterator< PF >::operator--(), and castor::ConstPixelIterator< PF >::operator--().
operator->()
template<PixelFormat PF> pixel_type* castor::PixelIterator< PF >::operator-> () inline
References REQUIRE.
operator=() [1/2]
template<PixelFormat PF> PixelIterator& castor::PixelIterator< PF >::operator= (PixelIterator< PF > const & p_it) inline
operator=() [2/2]
template<PixelFormat PF> PixelIterator& castor::PixelIterator< PF >::operator= (PixelIterator< PF > && p_it) inline
operator==()
template<PixelFormat PF> bool castor::PixelIterator< PF >::operator== (PixelIterator< PF > const & p_it) const inline
The documentation for this struct was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/PixelBuffer.hpp