CastorUtils: castor::Connection< SignalT > Class Template Reference
castor::Connection< SignalT > Class Template Reference
Connection to a signal.
Public Member Functions
Connection ()
Constructor.
Connection (uint32_t connection, my_signal &signal)
Constructor.
Connection (Connection< my_signal > &&rhs)
Move constructor.
Connection & operator= (Connection< my_signal > &&rhs)
Move assignment operator.
~Connection ()
Destructor.
bool disconnect ()
Disconnects the function from the signal.
Detailed Description
template<typename SignalT>
class castor::Connection< SignalT >
Connection to a signal.
Author
Sylvain doremus
Version
0.9.0
Date
01/03/2017
Constructor & Destructor Documentation
Connection() [1/3]
template<typename SignalT > castor::Connection< SignalT >::Connection () inline
Constructor.
Connection() [2/3]
template<typename SignalT > castor::Connection< SignalT >::Connection (uint32_t connection, my_signal & signal) inline
Constructor.
Parameters
[in] connection The connection to the signal.
[in] signal The signal.
Connection() [3/3]
template<typename SignalT > castor::Connection< SignalT >::Connection (Connection< my_signal > && rhs) inline
Move constructor.
Parameters
[in,out] rhs The object to move.
~Connection()
template<typename SignalT > castor::Connection< SignalT >::~Connection () inline
Destructor.
Remarks
Disconnects the function from the signal.
References castor::Connection< SignalT >::disconnect().
Member Function Documentation
disconnect()
template<typename SignalT > bool castor::Connection< SignalT >::disconnect () inline
Disconnects the function from the signal.
Referenced by castor::Signal< std::function< void(WorkerThread &) > >::operator()(), castor::Connection< SignalT >::operator=(), and castor::Connection< SignalT >::~Connection().
operator=()
template<typename SignalT > Connection& castor::Connection< SignalT >::operator= (Connection< my_signal > && rhs) inline
Move assignment operator.
Parameters
[in,out] rhs The object to move.
References castor::Connection< SignalT >::disconnect().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Design/Signal.hpp