Castor3D: castor3d::OverlayCategory::TextWriter Class Reference
castor3d::OverlayCategory::TextWriter Class Reference
OverlayCategory loader.
Public Member Functions
C3D_API TextWriter (castor::String const &tabs)
Constructor.
C3D_API bool operator() (OverlayCategory const &overlay, castor::TextFile &file) override
Saves an overlay into a text file.
virtual C3D_API bool writeInto (castor::TextFile &file)
Writes a OverlayCategory into a text file.
Detailed Description
OverlayCategory loader.
Author
Sylvain DOREMUS
Date
14/02/2010
Remarks
Loads and saves overlays from/into a file
Constructor & Destructor Documentation
TextWriter()
C3D_API castor3d::OverlayCategory::TextWriter::TextWriter (castor::String const & tabs) explicit
Constructor.
Member Function Documentation
operator()()
C3D_API bool castor3d::OverlayCategory::TextWriter::operator() (OverlayCategory const & overlay, castor::TextFile & file) override
Saves an overlay into a text file.
Parameters
[in] file the file to save the overlay in.
[in] overlay the overlay to save.
Returns
true if everything is OK.
writeInto()
virtual C3D_API bool castor3d::OverlayCategory::TextWriter::writeInto (castor::TextFile & file) inline virtual
Writes a OverlayCategory into a text file.
Parameters
[in] file The file.
Returns
true if everything is OK.
Reimplemented in castor3d::TextOverlay::TextWriter, castor3d::BorderPanelOverlay::TextWriter, and castor3d::PanelOverlay::TextWriter.
References C3D_API, castor3d::OverlayCategory::createTextWriter(), castor3d::OverlayCategory::getAbsolutePosition(), castor3d::OverlayCategory::getAbsoluteSize(), castor3d::OverlayCategory::getOverlayName(), castor3d::OverlayCategory::getRenderRatio(), castor3d::OverlayCategory::isPositionChanged(), castor3d::OverlayCategory::isSizeChanged(), castor3d::OverlayCategory::OverlayCategory(), castor3d::OverlayCategory::render(), castor3d::OverlayCategory::setMaterial(), castor3d::OverlayCategory::update(), and castor3d::OverlayCategory::~OverlayCategory().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Overlay/OverlayCategory.hpp