CastorUtils: castor::Font Class Reference
castor::Font Class Reference
Font resource.
Classes
class BinaryLoader
Font loader.
struct SFontImpl
Structure used to load glyphs on demand.
class TextWriter
Font text loader.
Public Member Functions
DECLARE_VECTOR (Glyph, Glyph)
CU_API Font (String const &p_name, uint32_t p_height)
Constructor.
CU_API Font (String const &p_name, uint32_t p_height, Path const &p_path)
Constructor.
CU_API ~Font ()
Destructor.
CU_API void loadGlyph (char32_t p_char)
Loads wanted glyph.
bool hasGlyphAt (char32_t p_char) const
Tells if the font already has load ed the wanted glyph.
Glyph const & getGlyphAt (char32_t p_char) const
Retrieves the glyph of wanted chaaracter.
Glyph & getGlyphAt (char32_t p_char)
Retrieves the glyph of wanted chaaracter.
Glyph const & operator[] (char32_t p_char) const
Retrieves the glyph of wanted chaaracter.
Glyph & operator[] (char32_t p_char)
Retrieves the glyph of wanted chaaracter.
uint32_t getHeight () const
Retrieves the height of the font.
uint32_t getMaxHeight () const
Retrieves the max height of the glyphs.
uint32_t getMaxWidth () const
Retrieves the max width of the glyphs.
void setMaxHeight (uint32_t p_iHeight)
sets the max height of the glyphs
void setMaxWidth (uint32_t p_iWidth)
sets the max width of the glyphs
void setGlyphLoader (std::unique_ptr< SFontImpl > &&p_loader)
sets the glyph loader
bool hasGlyphLoader ()
Tells if the font has a glyph loader.
SFontImpl & getGlyphLoader ()
Retrieves the glyph loader.
auto begin ()
Retrieves an iterator on the first glyph.
auto begin () const
Retrieves an iterator on the first glyph.
auto end ()
Retrieves an iterator on the glyph array end.
auto end () const
Retrieves an iterator on the glyph array end.
void setFaceName (String const &p_name)
sets The font face name
String const & getFaceName () const
Retrieves The font face name.
Path const & getFilePath () const
Retrieves The font file path.
Public Member Functions inherited from castor::Resource< Font >
Resource (Resource const &p_other)
Copy Constructor.
Resource (Resource &&p_other)
Move Constructor.
Resource & operator= (Resource const &p_other)
Copy assignment operator.
Resource & operator= (Resource &&p_other)
Move assignment operator.
void changeName (String const &p_name)
Defines the resource name.
Public Member Functions inherited from castor::NamedBase< T >
NamedBase (T const &p_name)
Constructor.
NamedBase (NamedBase const &p_named)=default
Copy Constructor.
NamedBase (NamedBase &&p_named)=default
Move Constructor.
~NamedBase ()=default
Destructor.
NamedBase & operator= (NamedBase const &p_named)=default
Copy Constructor.
NamedBase & operator= (NamedBase &&p_named)=default
Move Constructor.
T const & getName () const
Retrieves the name.
void setName (T const &p_name)
sets the name
Additional Inherited Members
Protected Types inherited from castor::Resource< Font >
typedef Collection< Font, String > collection
Protected Member Functions inherited from castor::Resource< Font >
Resource (String const &p_name)
Constructor.
~Resource ()
Destructor.
Protected Attributes inherited from castor::NamedBase< T >
T m_name
Detailed Description
Font resource.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
17/01/2011
Remarks
Representation of a font : face, precision, and others
The generated font will be put in an image
Constructor & Destructor Documentation
Font() [1/2]
CU_API castor::Font::Font (String const & p_name, uint32_t p_height)
Constructor.
Parameters
[in] p_name The font name
[in] p_height The font char height
Font() [2/2]
CU_API castor::Font::Font (String const & p_name, uint32_t p_height, Path const & p_path)
Constructor.
Parameters
[in] p_path The font file path
[in] p_name The font name
[in] p_height The font char height
~Font()
CU_API castor::Font::~Font ()
Destructor.
Member Function Documentation
begin() [1/2]
auto castor::Font::begin () inline
Retrieves an iterator on the first glyph.
Returns
The iterator
begin() [2/2]
auto castor::Font::begin () const inline
Retrieves an iterator on the first glyph.
Returns
The iterator
DECLARE_VECTOR()
castor::Font::DECLARE_VECTOR (Glyph , Glyph)
end() [1/2]
auto castor::Font::end () inline
Retrieves an iterator on the glyph array end.
Returns
The iterator
end() [2/2]
auto castor::Font::end () const inline
Retrieves an iterator on the glyph array end.
Returns
The iterator
getFaceName()
String const& castor::Font::getFaceName () const inline
Retrieves The font face name.
Returns
The value
getFilePath()
Path const& castor::Font::getFilePath () const inline
Retrieves The font file path.
Returns
The value.
getGlyphAt() [1/2]
Glyph const& castor::Font::getGlyphAt (char32_t p_char) const inline
Retrieves the glyph of wanted chaaracter.
Parameters
[in] p_char The wanted character
Returns
A constant reference on the glyph
getGlyphAt() [2/2]
Glyph& castor::Font::getGlyphAt (char32_t p_char) inline
Retrieves the glyph of wanted chaaracter.
Parameters
[in] p_char The wanted character
Returns
A reference on the glyph
getGlyphLoader()
SFontImpl& castor::Font::getGlyphLoader () inline
Retrieves the glyph loader.
Returns
The loader
getHeight()
uint32_t castor::Font::getHeight () const inline
Retrieves the height of the font.
Returns
The font height
getMaxHeight()
uint32_t castor::Font::getMaxHeight () const inline
Retrieves the max height of the glyphs.
Returns
The glyphs max height
getMaxWidth()
uint32_t castor::Font::getMaxWidth () const inline
Retrieves the max width of the glyphs.
Returns
The glyphs max width
hasGlyphAt()
bool castor::Font::hasGlyphAt (char32_t p_char) const inline
Tells if the font already has load ed the wanted glyph.
Parameters
[in] p_char The character.
Returns
false if not.
Referenced by operator[]().
hasGlyphLoader()
bool castor::Font::hasGlyphLoader () inline
Tells if the font has a glyph loader.
Returns
The status
loadGlyph()
CU_API void castor::Font::loadGlyph (char32_t p_char)
Loads wanted glyph.
Parameters
[in] p_char The character.
operator[]() [1/2]
Glyph const& castor::Font::operator[] (char32_t p_char) const inline
Retrieves the glyph of wanted chaaracter.
Parameters
[in] p_char The wanted character
Returns
A reference on the glyph
References ENSURE, and hasGlyphAt().
operator[]() [2/2]
Glyph& castor::Font::operator[] (char32_t p_char) inline
Retrieves the glyph of wanted chaaracter.
Parameters
[in] p_char The wanted character
Returns
A reference on the glyph
References ENSURE, and hasGlyphAt().
setFaceName()
void castor::Font::setFaceName (String const & p_name) inline
sets The font face name
Parameters
[in] p_name The value
setGlyphLoader()
void castor::Font::setGlyphLoader (std::unique_ptr< SFontImpl > && p_loader) inline
sets the glyph loader
Parameters
[in] p_loader The value
setMaxHeight()
void castor::Font::setMaxHeight (uint32_t p_iHeight) inline
sets the max height of the glyphs
Parameters
[in] p_iHeight The new height
setMaxWidth()
void castor::Font::setMaxWidth (uint32_t p_iWidth) inline
sets the max width of the glyphs
Parameters
[in] p_iWidth The new width
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/CastorUtils/Src/Graphics/Font.hpp